BattleDome_Text_Potential1::
.string "Meilleur candidat au titre !$"

BattleDome_Text_Potential2::
.string "Ira au moins jusqu’en demi-finale.$"

BattleDome_Text_Potential3::
.string "Finira sûrement dans le trio gagnant.$"

BattleDome_Text_Potential4::
.string "Candidat potentiel à la première place.$"

BattleDome_Text_Potential5::
.string "Équipe à très fort potentiel.$"

BattleDome_Text_Potential6::
.string "Équipe dont on ne sait rien.$"

BattleDome_Text_Potential7::
.string "Équipe au-dessus de la moyenne.$"

BattleDome_Text_Potential8::
.string "Équipe dans la moyenne.$"

BattleDome_Text_Potential9::
.string "Équipe à potentiel moyen.$"

BattleDome_Text_Potential10::
.string "Équipe en dessous de la moyenne.$"

BattleDome_Text_Potential11::
.string "Équipe n’ayant encore jamais gagné.$"

BattleDome_Text_Potential12::
.string "Une victoire les rendrait très fiers.$"

BattleDome_Text_Potential13::
.string "Équipe assez faible dans l’ensemble.$"

BattleDome_Text_Potential14::
.string "Équipe à potentiel très faible.$"

BattleDome_Text_Potential15::
.string "Équipe qui n’ira sûrement pas en finale.$"

BattleDome_Text_Potential16::
.string "Équipe au potentiel le plus faible.$"

BattleDome_Text_PotentialDomeAceTucker::
.string "Superstar incontestée et invincible !$"

BattleDome_Text_StyleRiskDisaster::
.string "N’hésite pas à prendre des risques.$"

BattleDome_Text_StyleEndureLongBattles::
.string "Fait preuve d’endurance au combat.$"

BattleDome_Text_StyleVariesTactics::
.string "Change de tactique selon l’adversaire.$"

BattleDome_Text_StyleToughWinningPattern::
.string "Profil de gagnant très prononcé.$"

BattleDome_Text_StyleUsesVeryRareMove::
.string "Utilise parfois de très rares attaques.$"

BattleDome_Text_StyleUsesStartlingMoves::
.string "Aime faire sursauter et déranger.$"

BattleDome_Text_StyleConstantlyWatchesHP::
.string "Observe tout le temps les PV au combat.$"

BattleDome_Text_StyleStoresAndLoosesPower::
.string "Stocke puis relâche de la puissance.$"

BattleDome_Text_StyleEnfeeblesFoes::
.string "Sait bien affaiblir l’adversaire.$"

BattleDome_Text_StylePrefersLuckTactics::
.string "S’en remet souvent à la chance.$"

BattleDome_Text_StyleRegalAtmosphere::
.string "Attaque de façon majestueuse.$"

BattleDome_Text_StylePowerfulLowPPMoves::
.string "Capacités puissantes à faibles PP.$"

BattleDome_Text_StyleEnfeebleThenAttack::
.string "Affaiblit d’abord, attaque ensuite.$"

BattleDome_Text_StyleBattlesWhileEnduring::
.string "Grande résistance aux attaques.$"

BattleDome_Text_StyleUpsetsFoesEmotionally::
.string "Aime énerver les ennemis.$"

BattleDome_Text_StyleStrongAndStraightforward::
.string "Capacités puissantes et directes.$"

BattleDome_Text_StyleAggressivelyStrongMoves::
.string "Agressif, capacités puissantes.$"

BattleDome_Text_StyleCleverlyDodgesAttacks::
.string "Se bat en esquivant les attaques.$"

BattleDome_Text_StyleUsesUpsettingMoves::
.string "Aime contrarier l’adversaire.$"

BattleDome_Text_StyleUsesPopularMoves::
.string "Aime les capacités connues.$"

BattleDome_Text_StyleHasPowerfulComboMoves::
.string "Capacités aux combinaisons puissantes.$"

BattleDome_Text_StyleUsesHighProbabilityMoves::
.string "Attaques à fort taux de réussite.$"

BattleDome_Text_StyleAggressivelySpectacularMoves::
.string "Capacités spectaculaires, agressif.$"

BattleDome_Text_StyleEmphasizesOffenseOverDefense::
.string "Préfère l’attaque à la défense.$"

BattleDome_Text_StyleEmphasizesDefenseOverOffense::
.string "Préfère la défense à l’attaque.$"

BattleDome_Text_StyleAttacksQuicklyStrongMoves::
.string "Rapide, capacités puissantes.$"

BattleDome_Text_StyleUsesAddedEffectMoves::
.string "Aime les capacités à effets ajoutés.$"

BattleDome_Text_StyleUsesBalancedMixOfMoves::
.string "Éventail de capacités bien équilibré.$"

BattleDome_Text_StyleSampleMessage1::
.string "C’est le message d’essai 1.$"

BattleDome_Text_StyleSampleMessage2::
.string "C’est le message d’essai 2.$"

BattleDome_Text_StyleSampleMessage3::
.string "C’est le message d’essai 3.$"

BattleDome_Text_StyleSampleMessage4::
.string "C’est le message d’essai 4.$"

BattleDome_Text_EmphasizesHPAndAtk::
.string "Favorise les PV et l’Attaque.$"

BattleDome_Text_EmphasizesHPAndDef::
.string "Favorise les PV et la Défense.$"

BattleDome_Text_EmphasizesHPAndSpeed::
.string "Favorise les PV et la Vitesse.$"

BattleDome_Text_EmphasizesHPAndSpAtk::
.string "Favorise les PV et l’Atq. Spé.$"

BattleDome_Text_EmphasizesHPAndSpDef::
.string "Favorise les PV et la Déf. Spé.$"

BattleDome_Text_EmphasizesAtkAndDef::
.string "Favorise l’Attaque et la Défense.$"

BattleDome_Text_EmphasizesAtkAndSpeed::
.string "Favorise l’Attaque et la Vitesse.$"

BattleDome_Text_EmphasizesAtkAndSpAtk::
.string "Favorise l’Attaque et l’Atq. Spé.$"

BattleDome_Text_EmphasizesAtkAndSpDef::
.string "Favorise l’Attaque et la Déf. Spé.$"

BattleDome_Text_EmphasizesDefAndSpeed::
.string "Favorise la Défense et la Vitesse.$"

BattleDome_Text_EmphasizesDefAndSpAtk::
.string "Favorise la Défense et l’Atq. Spé.$"

BattleDome_Text_EmphasizesDefAndSpDef::
.string "Favorise la Défense et la Déf. Spé.$"

BattleDome_Text_EmphasizesSpeedAndSpAtk::
.string "Favorise la Vitesse et l’Atq. Spé.$"

BattleDome_Text_EmphasizesSpeedAndSpDef::
.string "Favorise la Vitesse et la Déf. Spé.$"

BattleDome_Text_EmphasizesSpAtkAndSpDef::
.string "Favorise l’Atq. Spé. et la Déf. Spé.$"

BattleDome_Text_EmphasizesHP::
.string "Favorise les PV.$"

BattleDome_Text_EmphasizesAtk::
.string "Favorise l’Attaque.$"

BattleDome_Text_EmphasizesDef::
.string "Favorise la Défense.$"

BattleDome_Text_EmphasizesSpeed::
.string "Favorise la Vitesse.$"

BattleDome_Text_EmphasizesSpAtk::
.string "Favorise l’Atq. Spé.$"

BattleDome_Text_EmphasizesSpDef::
.string "Favorise la Déf. Spé.$"

BattleDome_Text_NeglectsHPAndAtk::
.string "Néglige les PV et l’Attaque.$"

BattleDome_Text_NeglectsHPAndDef::
.string "Néglige les PV et la Défense.$"

BattleDome_Text_NeglectsHPAndSpeed::
.string "Néglige les PV et la Vitesse.$"

BattleDome_Text_NeglectsHPAndSpAtk::
.string "Néglige les PV et l’Atq. Spé.$"

BattleDome_Text_NeglectsHPAndSpDef::
.string "Néglige les PV et la Déf. Spé.$"

BattleDome_Text_NeglectsAtkAndDef::
.string "Néglige l’Attaque et la Défense.$"

BattleDome_Text_NeglectsAtkAndSpeed::
.string "Néglige l’Attaque et la Vitesse.$"

BattleDome_Text_NeglectsAtkAndSpAtk::
.string "Néglige l’Attaque et l’Atq. Spé.$"

BattleDome_Text_NeglectsAtkAndSpDef::
.string "Néglige l’Attaque et la Déf. Spé.$"

BattleDome_Text_NeglectsDefAndSpeed::
.string "Néglige la Défense et la Vitesse.$"

BattleDome_Text_NeglectsDefAndSpAtk::
.string "Néglige la Défense et l’Atq. Spé.$"

BattleDome_Text_NeglectsDefAndSpDef::
.string "Néglige la Défense et la Déf. Spé.$"

BattleDome_Text_NeglectsSpeedAndSpAtk::
.string "Néglige la Vitesse et l’Atq. Spé.$"

BattleDome_Text_NeglectsSpeedAndSpDef::
.string "Néglige la Vitesse et la Déf. Spé.$"

BattleDome_Text_NeglectsSpAtkAndSpDef::
.string "Néglige l’Atq. Spé. et la Déf. Spé.$"

BattleDome_Text_NeglectsHP::
.string "Néglige les PV.$"

BattleDome_Text_NeglectsAtk::
.string "Néglige l’Attaque.$"

BattleDome_Text_NeglectsDef::
.string "Néglige la Défense.$"

BattleDome_Text_NeglectsSpeed::
.string "Néglige la Vitesse.$"

BattleDome_Text_NeglectsSpAtk::
.string "Néglige l’Atq. Spé.$"

BattleDome_Text_NeglectsSpDef::
.string "Néglige la Déf. Spé.$"

BattleDome_Text_RaisesMonsWellBalanced::
.string "Élève ses Pokémon de façon équilibrée.$"

BattleDome_Text_LetTheBattleBegin::
.string "Que le combat commence !$"

BattleDome_Text_TrainerWonUsingMove::
.string "{STR_VAR_1} a gagné avec {STR_VAR_2}!$"

BattleDome_Text_TrainerBecameChamp::
.string "{STR_VAR_1} a le titre de champion !$"

BattleDome_Text_TrainerWonByDefault::
.string "{STR_VAR_1} a gagné par forfait !$"

BattleDome_Text_TrainerWonOutrightByDefault::
.string "{STR_VAR_1} a gagné par forfait !$"

BattleDome_Text_TrainerWonNoMoves::
.string "{STR_VAR_1} a gagné sans rien faire !$"

BattleDome_Text_TrainerWonOutrightNoMoves::
.string "{STR_VAR_1} a gagné sans rien faire !$"

BattleDome_Text_Round1Match1::
.string "1{SUPER_ER} tour, combat nº 1$"

BattleDome_Text_Round1Match2::
.string "1{SUPER_ER} tour, combat nº 2$"

BattleDome_Text_Round1Match3::
.string "1{SUPER_ER} tour, combat nº 3$"

BattleDome_Text_Round1Match4::
.string "1{SUPER_ER} tour, combat nº 4$"

BattleDome_Text_Round1Match5::
.string "1{SUPER_ER} tour, combat nº 5$"

BattleDome_Text_Round1Match6::
.string "1{SUPER_ER} tour, combat nº 6$"

BattleDome_Text_Round1Match7::
.string "1{SUPER_ER} tour, combat nº 7$"

BattleDome_Text_Round1Match8::
.string "1{SUPER_ER} tour, combat nº 8$"

BattleDome_Text_Round2Match1::
.string "2{SUPER_E} tour, combat nº 1$"

BattleDome_Text_Round2Match2::
.string "2{SUPER_E} tour, combat nº 2$"

BattleDome_Text_Round2Match3::
.string "2{SUPER_E} tour, combat nº 3$"

BattleDome_Text_Round2Match4::
.string "2{SUPER_E} tour, combat nº 4$"

BattleDome_Text_SemifinalMatch1::
.string "Demi-finale, combat nº 1$"

BattleDome_Text_SemifinalMatch2::
.string "Demi-finale, combat nº 2$"

BattleDome_Text_FinalMatch::
.string "Finale$"