FallarborTown_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "Bienvenue dans la Tente de Combat\n"
	.string "d’Autéquia !\p"
	.string "Je serai votre guide pour le\n"
	.string "Tournoi K.O. !$"

FallarborTown_BattleTentLobby_Text_TakeChallenge:
	.string "Voulez-vous participer à un\n"
	.string "Tournoi K.O., oui ou non ?$"

FallarborTown_BattleTentLobby_Text_AwaitAnotherChallenge:
	.string "Nous espérons que vous relèverez\n"
	.string "bientôt notre défi !$"

FallarborTown_BattleTentLobby_Text_ExplainFallarborTent:
	.string "Dans la Tente de Combat d’Autéquia,\n"
	.string "vous participez à un Tournoi K.O.\p"
	.string "Les participants s’inscrivent avec une\n"
	.string "équipe de trois Pokémon.\p"
	.string "Ces Pokémon doivent être placés dans\n"
	.string "l’ordre dans lequel ils apparaîtront.\p"
	.string "Pendant un combat, ils apparaîtront\n"
	.string "l’un après l’autre dans l’ordre\l"
	.string "prédéfini.\p"
	.string "Un Pokémon qui entre au combat doit\n"
	.string "y rester jusqu’à la fin.\p"
	.string "S’il n’y a pas de vainqueur au bout de\n"
	.string "trois tours, l’Arbitre intervient.\p"
	.string "Si vous voulez interrompre le défi,\n"
	.string "veuillez sauvegarder la partie.\p"
	.string "Si vous ne sauvegardez pas, vous ne\n"
	.string "pourrez pas reprendre ce défi.\p"
	.string "Si vous mettez K.O. trois Dresseurs de\n"
	.string "suite, nous vous remettons un prix.$"

FallarborTown_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "Avant de me suivre dans la Tente De\n"
	.string "Combat, vous devez sauvegarder. OK ?$"

@ Unused
FallarborTown_BattleTentLobby_Text_WhichLevelMode:
	.string "We offer two levels of challenge,\n"
	.string "Level 50 and Open Level.\l"
	.string "Which is your choice ?$"

FallarborTown_BattleTentLobby_Text_SelectThreeMons:
	.string "Veuillez choisir les trois Pokémon que\n"
	.string "vous souhaitez inscrire.$"

FallarborTown_BattleTentLobby_Text_NotEnoughValidMonsLv50:
	.string "Je regrette, cher Dresseur !\p"
	.string "Vous n’avez pas trois Pokémon\n"
	.string "aptes à participer.\p"
	.string "Ils doivent aussi tenir des objets\n"
	.string "différents.\p"
	.string "Les Œufs{STR_VAR_1} inaptes au combat.\p"
	.string "Revenez me voir quand vous aurez\n"
	.string "ce qu’il faut.$"

FallarborTown_BattleTentLobby_Text_NotEnoughValidMonsLvOpen:
	.string "Je regrette, cher Dresseur !\p"
	.string "Vous n’avez pas trois Pokémon\n"
	.string "aptes à participer.\p"
	.string "Il vous faut trois Pokémon différents\n"
	.string "pour participer.\p"
	.string "Ils doivent aussi tenir des objets\n"
	.string "différents.\p"
	.string "Les Œufs{STR_VAR_1} inaptes au combat.\p"
	.string "Revenez me voir quand vous aurez\n"
	.string "ce qu’il faut.$"

FallarborTown_BattleTentLobby_Text_GuideYouToBattleTent:
	.string "Je vais vous guider dans la\n"
	.string "Tente de Combat.$"

FallarborTown_BattleTentLobby_Text_DidntSaveBeforeQuitting:
	.string "Je regrette, cher Dresseur !\p"
	.string "Vous n’avez pas sauvegardé avant de\n"
	.string "quitter votre dernier défi.\p"
	.string "Dans ce cas, c’est la disqualification.\n"
	.string "Quel dommage !\p"
	.string "Bien entendu, vous pouvez recommencer\n"
	.string "un autre défi.$"

FallarborTown_BattleTentLobby_Text_BeatThreeTrainers:
	.string "Splendide ! Vous avez battu trois\n"
	.string "Dresseurs à la suite !$"

FallarborTown_BattleTentLobby_Text_WaitWhileSaveGame:
	.string "Votre résultat va être sauvegardé.\n"
	.string "Veuillez patienter.$"

FallarborTown_BattleTentLobby_Text_PresentYouWithPrize:
	.string "Pour récompenser ces trois victoires\n"
	.string "consécutives, voici un prix.$"

FallarborTown_BattleTentLobby_Text_ReceivedPrize:
	.string "{PLAYER} reçoit {STR_VAR_1}\n"
	.string "en récompense.$"

FallarborTown_BattleTentLobby_Text_BagFullReturnForPrize:
	.string "Oh, votre Sac est plein.\p"
	.string "Veuillez faire de la place dans votre\n"
	.string "Sac et revenez ensuite me voir.$"

FallarborTown_BattleTentLobby_Text_ThankYouWaitWhileSaving:
	.string "Merci d’avoir participé !\p"
	.string "Votre résultat va être sauvegardé.\n"
	.string "Veuillez patienter.$"

FallarborTown_BattleTentLobby_Text_AwaitAnotherChallenge2:
	.string "Nous attendrons votre prochain défi\n"
	.string "avec impatience.$"

FallarborTown_BattleTentLobby_Text_LookingForwardToArrival:
	.string "Nous vous attendions !\p"
	.string "Vous devez sauvegarder avant d’aller\n"
	.string "plus loin. Veuillez patienter.$"

VerdanturfTown_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "Bienvenue dans la Tente de Combat\n"
	.string "de Vergazon !\p"
	.string "Nous testons la confiance des\n"
	.string "Dresseurs envers leurs Pokémon.$"

VerdanturfTown_BattleTentLobby_Text_TakeChallenge:
	.string "Voulez-vous relever le défi de la\n"
	.string "Tente de Combat de Vergazon ?$"

VerdanturfTown_BattleTentLobby_Text_ExplainVerdanturfTent:
	.string "Dans la Tente de Combat de Vergazon,\n"
	.string "une règle importante est ajoutée.\p"
	.string "Les Dresseurs peuvent seulement\n"
	.string "faire entrer et sortir leurs Pokémon.\p"
	.string "Les Dresseurs ne peuvent pas donner\n"
	.string "d’autres ordres à leurs Pokémon.\p"
	.string "Les Pokémon agiront conformément\n"
	.string "à leur nature et se battront seuls.\p"
	.string "Vous devez placer votre confiance en\n"
	.string "vos Pokémon et les regarder.\p"
	.string "Si vous réalisez l’exploit de battre\n"
	.string "trois Dresseurs à la suite, vous\l"
	.string "recevrez un prix.\p"
	.string "Si vous voulez interrompre le défi,\n"
	.string "veuillez sauvegarder la partie.\p"
	.string "Assurez-vous de bien sauvegarder, ou\n"
	.string "vous ne pourrez pas reprendre le défi.$"

VerdanturfTown_BattleTentLobby_Text_ReturnFortified:
	.string "Revenez quand vous aurez fortifié\n"
	.string "votre esprit et vos Pokémon.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_WhichLevelMode:
	.string "There are two levels of difficulty,\n"
	.string "Level 50 and Open Level.\l"
	.string "Which is your choice of a challenge ?$"

VerdanturfTown_BattleTentLobby_Text_NotEnoughValidMonsLv50:
	.string "Je regrette !\p"
	.string "Vous n’avez pas trois Pokémon\n"
	.string "aptes à participer.\p"
	.string "Il vous faut trois Pokémon différents\n"
	.string "pour participer.\p"
	.string "Ils doivent aussi tenir des objets\n"
	.string "différents.\p"
	.string "Les Œufs{STR_VAR_1} inaptes au combat.\p"
	.string "Revenez me voir quand vous aurez\n"
	.string "ce qu’il faut.$"

VerdanturfTown_BattleTentLobby_Text_NotEnoughValidMonsLvOpen:
	.string "Je regrette !\p"
	.string "Vous n’avez pas trois Pokémon\n"
	.string "aptes à participer.\p"
	.string "Il vous faut trois Pokémon différents\n"
	.string "pour participer.\p"
	.string "Ils doivent aussi tenir des objets\n"
	.string "différents.\p"
	.string "Les Œufs{STR_VAR_1} inaptes au combat.\p"
	.string "Revenez me voir quand vous aurez\n"
	.string "ce qu’il faut.$"

VerdanturfTown_BattleTentLobby_Text_SelectThreeMons:
	.string "Très bien. Maintenant, veuillez choisir\n"
	.string "vos trois Pokémon.$"

VerdanturfTown_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "Avant d’entrer dans la Tente de Combat,\n"
	.string "votre partie doit être sauvegardée. OK ?$"

VerdanturfTown_BattleTentLobby_Text_NowFollowMe:
	.string "Très bien.\n"
	.string "Suivez-moi, je vous prie.$"

VerdanturfTown_BattleTentLobby_Text_ResultsWillBeRecorded:
	.string "Ce fut un privilège de pouvoir assister\n"
	.string "à un tel combat.\p"
	.string "Votre résultat va être sauvegardé.\n"
	.string "Veuillez patienter.$"

VerdanturfTown_BattleTentLobby_Text_AchievedThreeWinStreak:
	.string "Trois victoires consécutives…\p"
	.string "Les liens qui unissent votre esprit à\n"
	.string "vos Pokémon sont solides et sincères.$"

VerdanturfTown_BattleTentLobby_Text_FeatWillBeRecorded:
	.string "Votre résultat va être sauvegardé.\n"
	.string "Je vous demande de patienter un peu.$"

VerdanturfTown_BattleTentLobby_Text_PresentYouWithPrize:
	.string "Pour récompenser ces trois victoires\n"
	.string "consécutives, voici un prix.$"

SlateportCity_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "Bienvenue dans la Tente de Combat\n"
	.string "de Poivressel !\p"
	.string "Je serai votre guide pour le Tournoi\n"
	.string "Combat Échange.$"

SlateportCity_BattleTentLobby_Text_TakeChallenge:
	.string "Voulez-vous relever le défi du\n"
	.string "Combat Échange ?$"

SlateportCity_BattleTentLobby_Text_ExplainSlateportTent:
	.string "Dans la Tente de Combat de Poivressel\n"
	.string "ont lieu des Combats Échange avec des\l"
	.string "Pokémon de location.\p"
	.string "Vous devez choisir trois Pokémon parmi\n"
	.string "les Pokémon de location.\p"
	.string "Ensuite, vous faites des Combats\n"
	.string "Solo avec ces Pokémon.\p"
	.string "Si vous gagnez, vous pouvez échanger\n"
	.string "l’un des Pokémon de location.\p"
	.string "Si vous gagnez trois combats à la suite,\n"
	.string "vous remportez un prix.\p"
	.string "Si vous voulez interrompre le défi,\n"
	.string "veuillez sauvegarder la partie.\p"
	.string "Si vous ne sauvegardez pas,\n"
	.string "c’est la disqualification.$"

SlateportCity_BattleTentLobby_Text_LookForwardToNextVisit:
	.string "Nous espérons vous compter parmi\n"
	.string "nos participants une prochaine fois.$"

@ Unused
SlateportCity_BattleTentLobby_Text_WhichLevelMode:
	.string "Which level do you wish to challenge ?\n"
	.string "Level 50 or Level 100 ?$"

SlateportCity_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "Avant de commencer, votre partie doit\n"
	.string "être sauvegardée. OK ?$"

@ Unused
SlateportCity_BattleTentLobby_Text_HoldMonsForSafekeeping:
	.string "Okay, I will hold your Pokémon for\n"
	.string "safekeeping while you compete.$"

SlateportCity_BattleTentLobby_Text_StepThisWay:
	.string "Entrez, je vous en prie.$"

SlateportCity_BattleTentLobby_Text_ReturnRentalMonsSaveResults:
	.string "Merci d’avoir joué !\p"
	.string "Je vous rends vos Pokémon et reprends\n"
	.string "les Pokémon de location.\p"
	.string "Je dois sauvegarder vos données.\n"
	.string "Veuillez patienter.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReturnMonsExchangeRentals:
	.string "I will return your Pokémon in exchange\n"
	.string "for our rental Pokémon.$"

SlateportCity_BattleTentLobby_Text_WonThreeMatchesReturnMons:
	.string "Félicitations ! Vous avez gagné trois\n"
	.string "Combats Échange à la suite !\p"
	.string "Je vous rends vos Pokémon et reprends\n"
	.string "les Pokémon de location.\p"
	.string "Je dois sauvegarder vos données.\n"
	.string "Veuillez patienter.$"

SlateportCity_BattleTentLobby_Text_AwardYouThisPrize:
	.string "Pour récompenser ces trois victoires\n"
	.string "consécutives, voici un prix.$"

SlateportCity_BattleTentLobby_Text_NoRoomInBagMakeRoom:
	.string "Oh ?\n"
	.string "On dirait que vous n’avez plus de place.\p"
	.string "Faites de la place dans votre Sac et\n"
	.string "revenez me voir.$"

SlateportCity_BattleTentLobby_Text_BeenWaitingForYou:
	.string "Nous vous attendions !\p"
	.string "Avant de reprendre votre défi, vous\n"
	.string "devez sauvegarder la partie.$"

SlateportCity_BattleTentLobby_Text_DidntSaveBeforeQuitting:
	.string "Je regrette !\p"
	.string "Vous n’avez pas sauvegardé avant de\n"
	.string "quitter votre dernier défi.\p"
	.string "Dans ce cas, c’est la disqualification.\n"
	.string "C’est dommage !$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReturnPersonalMons:
	.string "We’ll return your personal Pokémon.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReceivedPrize:
	.string "{PLAYER} received the prize\n"
	.string "{STR_VAR_1}.$"

@ Unused
SlateportCity_BattleTentLobby_Text_RulesAreListed:
	.string "The Battle Swap rules are listed.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReadWhichHeading:
	.string "Which heading do you want to read ?$"

SlateportCity_BattleTentLobby_Text_ExplainBasicRules:
	.string "Au Combat Échange, vous ne pouvez\n"
	.string "utiliser que trois Pokémon.\p"
	.string "Qu’ils aient été prêtés ou échangés,\n"
	.string "votre équipe ne peut pas avoir deux\l"
	.string "fois le même Pokémon.$"

SlateportCity_BattleTentLobby_Text_ExplainSwapPartnerRules:
	.string "Vous pouvez échanger un Pokémon avec\n"
	.string "le Dresseur que vous venez de battre.\p"
	.string "Vous ne pouvez obtenir que les Pokémon\n"
	.string "se trouvant dans son équipe.$"

SlateportCity_BattleTentLobby_Text_ExplainSwapNumberRules:
	.string "A chaque fois que vous gagnez, vous\n"
	.string "pouvez échanger l’un de vos Pokémon\l"
	.string "avec l’un de ceux de votre adversaire.\p"
	.string "Vous ne pouvez pas faire d’échange\n"
	.string "avec le troisième Dresseur.$"

SlateportCity_BattleTentLobby_Text_ExplainSwapNotes:
	.string "Voici deux choses à savoir sur les\n"
	.string "échanges de Pokémon.\p"
	.string "Avant l’échange, vous ne pouvez pas\n"
	.string "connaître les stats du Pokémon\l"
	.string "que vous voulez recevoir.\p"
	.string "Les Pokémon de votre équipe sont\n"
	.string "alignés dans l’ordre où vous les avez\l"
	.string "loués.\p"
	.string "Cet ordre reste le même lorsque vous\n"
	.string "échangez des Pokémon.$"

SlateportCity_BattleTentLobby_Text_ExplainMonRules:
	.string "Tous les Pokémon de la Tente de Combat\n"
	.string "de Poivressel sont prêtés.\p"
	.string "Les Pokémon sont tous de niveau 30.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_RulesAreListed2:
	.string "The Verdanturf Battle Tent\n"
	.string "rules are listed.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ReadWhichHeading:
	.string "Which heading do you want to read ?$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainBasicRules:
	.string "Here at the Verdanturf Battle Tent,\n"
	.string "Pokémon are required to think and\l"
	.string "battle by themselves.\p"
	.string "Unlike in the wild, Pokémon that live\n"
	.string "with people behave differently\l"
	.string "depending on their nature.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainNatureRules:
	.string "Depending on its nature, a Pokémon\n"
	.string "may prefer to attack no matter what.\p"
	.string "Another Pokémon may prefer to protect\n"
	.string "itself from any harm.\p"
	.string "Yet another may enjoy vexing or\n"
	.string "confounding its foes.\p"
	.string "Depending on its nature, a Pokémon\n"
	.string "will have favorite moves that it is good\l"
	.string "at using.\p"
	.string "It may also dislike certain moves that\n"
	.string "it has trouble using.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainMoveRules:
	.string "There are offensive moves that inflict\n"
	.string "direct damage on the foe.\p"
	.string "There are defensive moves that are\n"
	.string "used to prepare for enemy attacks or\l"
	.string "used to heal HP and so on.\p"
	.string "There are also other somewhat-odd\n"
	.string "moves that may enfeeble the foes with\l"
	.string "stat problems including poison and \l"
	.string "paralysis.\p"
	.string "Pokémon will consider using moves in\n"
	.string "these three categories.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainUnderpoweredRules:
	.string "When not under command by its Trainer,\n"
	.string "a Pokémon may be unable to effectively\l"
	.string "use certain moves.\p"
	.string "A Pokémon is not good at using any\n"
	.string "move that it dislikes.\p"
	.string "If a Pokémon only knows moves that\n"
	.string "do not match its nature, it will often\l"
	.string "be unable to live up to its potential.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainWhenInDangerRules:
	.string "Depending on its nature, a Pokémon may\n"
	.string "start using moves that don’t match its\l"
	.string "nature when it is in trouble.\p"
	.string "If a Pokémon begins behaving oddly\n"
	.string "in a pinch, watch it carefully.$"

BattleTentLobby_Text_ExplainLevelRules:
	.string "Dans cette Tente de Combat, le niveau\n"
	.string "de vos adversaires est ajusté en\l"
	.string "fonction du niveau de vos Pokémon.\p"
	.string "Cependant, aucun des Dresseurs que\n"
	.string "vous affronterez n’aura de Pokémon\l"
	.string "de niveau inférieur à 30.$"

VerdanturfTown_BattleTentLobby_Text_RulesAreListed:
	.string "Règles de la Tente de Combat de\n"
	.string "Vergazon.$"
