gText_Birch_Welcome::
	.string "Salut ! Désolé de l'attente !\p"
	.string "Bienvenue dans le monde des Pokémon !\p"
	.string "Mon nom est Chen.\p"
	.string "Mais on m'appelle\n"
	.string "le Professeur Pokémon.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "Voici ce qu'on appelle un “Pokémon”.\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "Ce monde est peuplé de créatures\n"
	.string "appelées Pokémon.\p"
	.string "Humains et Pokémon vivent en\n"
	.string "parfaite harmonie…\p"
	.string "Certains jouent avec les Pokémon,\n"
	.string "d'autres font des combats avec eux.\p"
	.string "Mais il reste beaucoup à apprendre\n"
	.string "sur nos amis les Pokémon.\p"
	.string "De nombreux mystères planent à\n"
	.string "leur sujet.\p"
    .string "Et c'est pourquoi j'étudie\n"
	.string "les Pokémon tous les jours.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Et toi, qui es-tu ?$"

gText_Birch_BoyOrGirl::
	.string "Êtes-vous un garçon ou une fille ?\n"
    .string "$"

gText_Birch_Difficulty::
	.string "Ah…\p"
	.string "Et… comment penses-tu que cette\n"
	.string "aventure va se dérouler ?$"

gText_Birch_LockDifficulty::
	.string "Si tu dois changer la difficulté,\n"
	.string "tu peux ouvrir le menu Options et\l"
	.string "la modifier depuis ce menu.\p"
	.string "Tu peux aussi la verrouiller si tu\n"
	.string "le souhaites. Verrouiller la\l"
	.string "difficulté choisie ?\p"
	.string "Ce choix sera définitif.$"

gText_Birch_Challenge::
	.string "Oh, vraiment ?\p"
	.string "Très bien, ceci étant dit…\n"
	.string "T'attends-tu à des défis\l"
	.string "durant ton voyage ?\p"
	.string "Et quel est ton nom ?$"

gText_Birch_WhatsYourName::
	.string "Heu… C'est quoi ton nom ?$"

gText_Birch_SoItsPlayer::
	.string "Oh ! Tu es donc {PLAYER} ?$"

gText_Birch_YourePlayer::
	.string "{PLAYER}, on y va ?\p"
	.string "Ta quête est sur le point\n"
	.string "de commencer.\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Joies et périls paveront ta route…\p"
	.string "Un monde de rêves, de danger et\n"
	.string "de Pokémon t'attend !\p"
	.string "En avant !\p"
	.string "…\n"
    .string "À plus tard\p"
	.string "$"