BerryBlender_Text_BlendWithTheBlendMaster:
	.string "Maitre Mixeur : C’est moi !\n"
	.string "Je suis le Maitre Mixeur !\p"
	.string "Mixe avec moi et tu verras le\n"
	.string "maître à l’œuvre !$"

BerryBlender_Text_SeeMyMasteryInAction:
	.string "Maitre Mixeur : Hum ! Alors comme ça,\n"
	.string "tu veux voir le maître à l’œuvre ?$"

BerryBlender_Text_TooBusyNowIsee:
	.string "Hum !\p"
	.string "Tu n’as pas le temps, je vois !\p"
	.string "Mais ne crains rien !\n"
	.string "Je ne bouge pas d’ici aujourd’hui !\l"
	.string "Reviens vite !$"

BerryBlender_Text_BlendMasterNoBerries:
	.string "Hum !\p"
	.string "Tu n’as pas une seule Baie !\p"
	.string "Je ne bouge pas d’ici aujourd’hui !\n"
	.string "Reviens vite !$"

BerryBlender_Text_BlendMasterKnowHowToMakePokeblocks:
	.string "Bien sûr !\n"
	.string "Bien sûr !\p"
	.string "Au fait…\n"
	.string "Tu sais comment mixer des Baies\l"
	.string "pour faire des {POKEBLOCK}s ?$"

BerryBlender_Text_BlendMasterExplainBerryBlending:
	.string "Hum !\p"
	.string "C’est simple comme bonjour !\p"
	.string "Lorsque la flèche du Mixeur passe\n"
	.string "devant ton marqueur, appuie simplement\l"
	.string "sur le bouton A.\p"
	.string "C’est tout.\p"
	.string "Quand tu me verras appuyer sur le\n"
	.string "bouton A, tu comprendras comme\l"
	.string "c’est facile.$"

BerryBlender_Text_BlendMasterLetsBerryBlender:
	.string "Bien !\p"
	.string "Dans ce cas, allons-y !\p"
	.string "C’est parti pour le Mixeur,\n"
	.string "avec le Maitre Mixeur !$"

BerryBlender_Text_BlendMasterNoPokeblockCase:
	.string "Hum !\p"
	.string "On dirait que tu n’as pas encore\n"
	.string "de Boîte {POKEBLOCK}s !\p"
	.string "Je ne bouge pas d’ici aujourd’hui !\n"
	.string "Trouve vite une Boîte {POKEBLOCK}s !$"

BerryBlender_Text_BlendMasterPokeblockCaseFull:
	.string "Hum !\p"
	.string "Ta Boîte {POKEBLOCK}s est pleine !\p"
	.string "Je ne bouge pas d’ici aujourd’hui !\n"
	.string "Utilise quelques {POKEBLOCK}s et reviens !$"

BerryBlender_Text_WhoaAwesome:
	.string "Waouh !\n"
	.string "Joli !$"

BerryBlender_Text_WickedlyFast:
	.string "Super rapide !$"

BerryBlender_Text_WhatAnExpert:
	.string "Formidable !$"

BerryBlender_Text_MadeAmazingPokeblocksWithMaster:
	.string "J’ai mixé avec le Maitre Mixeur et on\n"
	.string "a fait de superbes {POKEBLOCK}s !$"

BerryBlender_Text_QualitiesOfBlendMaster:
	.string "Des yeux de lynx qui suivent la\n"
	.string "flèche au centième de millimètre près…\p"
	.string "Une main qui appuie sur le bouton A\n"
	.string "avec la précision d’un métronome…\p"
	.string "C’est ça qui fait le succès du\n"
	.string "Maitre Mixeur.$"

BerryBlender_Text_MasterWorksOnSkillsInMountains:
	.string "Le Maitre Mixeur passe tout son\n"
	.string "temps à s’entraîner dans la montagne.\p"
	.string "Parfois, il nous fait l’honneur de venir\n"
	.string "à Nénucrique pour y mixer des Baies.$"
