Text_PictureBookShelf:
    .string "Ce sont des albums de Pokémon.$"

Text_BookShelf:
	.string "Il y a toutes sortes de livres.$"

Text_PokemonCenterBookShelf:
    .string "Des magazines Pokémon !\n"
    .string "NOS AMIS LES POKéMON…\p"
    .string "MANUEL POKéMON…\n"
    .string "GRAINE DE POKéMON…$"

Text_Vase:
    .string "Ce vase semble avoir de la valeur !\p"
    .string "En regardant à l’intérieur, on\n"
    .string "s’aperçoit qu’il est vide.$"

Text_EmptyTrashCan:
	.string "C’est vide.$"

Text_ShopShelf:
    .string "Les étagères regorgent de toutes\n"
    .string "sortes de produits Pokémon.$"

Text_Blueprint:
    .string "Voilà un curieux plan !\n"
    .string "Ça a l’air compliqué.$"
