LilycoveCity_DepartmentStore_1F_Text_LotteryCornerDrawTicket:
	.string "Vous êtes à la Loterie Pokémon.\p"
	.string "Si le numéro sur le Billet de Loterie\n"
	.string "correspond au numéro ID d’un de vos\l"
	.string "Pokémon, vous recevrez un beau cadeau.\p"
	.string "Voulez-vous retirer un Billet De\n"
	.string "Loterie Pokémon ?$"

LilycoveCity_DepartmentStore_1F_Text_ComeBackTomorrow:
	.string "Revenez demain.$"

LilycoveCity_DepartmentStore_1F_Text_PleaseVisitAgain:
	.string "A bientôt.$"

LilycoveCity_DepartmentStore_1F_Text_PleasePickTicket:
    .string "Veuillez prendre un Billet de Loterie.\n"
	.string "…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

LilycoveCity_DepartmentStore_1F_Text_TicketNumberIsXPleaseWait:
	.string "Le numéro du Billet de Loterie est\n"
	.string "{STR_VAR_1}.\p"
	.string "Je vais voir si ce numéro correspond\n"
	.string "à l’un des numéros ID de vos Pokémon.\p"
	.string "Veuillez patienter.$"

LilycoveCity_DepartmentStore_1F_Text_TicketMatchesPartyMon:
	.string "Félicitations !\p"
	.string "Le numéro ID de {STR_VAR_1}, qui est\n"
	.string "dans votre équipe, correspond à celui\l"
	.string "du Billet de Loterie !$"

LilycoveCity_DepartmentStore_1F_Text_TicketMatchesPCMon:
	.string "Félicitations !\p"
	.string "Le numéro ID de {STR_VAR_1}, qui est\n"
	.string "stocké sur le PC, correspond à\l"
	.string "celui du Billet de Loterie !$"

LilycoveCity_DepartmentStore_1F_Text_NoNumbersMatched:
	.string "Quel dommage !\n"
	.string "Aucun des numéros ne correspond.$"

LilycoveCity_DepartmentStore_1F_Text_TwoDigitsMatched:
	.string "Deux chiffres correspondent, vous\n"
	.string "remportez le troisième prix !\p"
	.string "Vous avez gagné {STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_ThreeDigitsMatched:
	.string "Trois chiffres correspondent, vous\n"
	.string "remportez le deuxième prix !\p"
	.string "Vous avez gagné {STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_FourDigitsMatched:
	.string "Quatre chiffres correspondent, vous\n"
	.string "remportez le premier prix !\p"
	.string "Vous avez gagné {STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_AllFiveDigitsMatched:
	.string "Magnifique, tous les chiffres\n"
	.string "correspondent !\p"
	.string "Vous avez gagné le super prix !\n"
	.string "Vous avez gagné {STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_NoRoomForThis:
	.string "Oh ?\n"
	.string "On dirait que vous n’avez plus de place.\p"
	.string "Faites de la place dans votre Sac et\n"
	.string "revenez me voir.$"

LilycoveCity_DepartmentStore_1F_Text_PrizeWeveBeenHolding:
	.string "{PLAYER}?\n"
	.string "Oui, je vous attendais.\p"
	.string "Nous vous avons gardé votre prix.$"

LilycoveCity_DepartmentStore_1F_Text_PleaseVisitAgain2:
	.string "A bientôt.$"
