MoveRelearner_Text_WouldLearnNewMoves:
.string "Bonjour ! Je suis Maître Capacités.\n"
.string "Tu veux apprendre une capacité ?$"

MoveRelearner_Text_LevelUpMoves:
.string "Capacités Niveau$"

MoveRelearner_Text_EggMoves:
.string "Capacités Œuf$"

MoveRelearner_Text_TMMoves:
.string "Capacités CT$"

MoveRelearner_Text_TutormoveMoves:
.string "Capacités Tuteur$"

MoveRelearner_Text_SeeYa:
.string "Au revoir !$"

MoveRelearner_Text_AnythingElse:
.string "Désires-tu autre chose ?$"

MoveRelearner_Text_ChoosePkmn:
.string "Choisis ton Pokémon.$"

MoveRelearner_Text_HaveNoPkmn:
.string "Tu n'as aucun Pokémon.$"

MoveRelearner_Text_CantTeachMoveToEgg:
.string "Désolé…\n"
.string "Un Œuf ne peut pas apprendre.$"

MoveRelearner_Text_CantTeachMoveToPkmn:
.string "Désolé…\p"
.string "Je n'ai aucune capacité à enseigner\n"
.string "à ce Pokémon.$"

MoveRelearner_Text_LevelUpMoveLWR::
.string "capacité de niveau$"

MoveRelearner_Text_EggMoveLWR::
.string "capacité œuf$"

MoveRelearner_Text_TMMoveLWR::
.string "capacité CT$"

MoveRelearner_Text_TutorMoveLWR::
.string "capacité tuteur$"

MoveRelearner_Text_WhichXmoveShouldTeach:
.string "Quelle {STR_VAR_3} enseigner ?$"

MoveRelearner_Text_ThankYouComeAgain:
.string "Merci d'avoir utilisé nos services.\n"
.string "À la prochaine !$"
