MoveTutor_Text_ThisMoveCanOnlyBeLearnedOnce:
	.string "Are you ready to learn this move ?$"
	.string "It will cost you 5.000¥.$"

MoveTutor_Text_ThisMoveCanOnlyBeLearnedOnceFinite:
	.string "This move can be learned only\n"
	.string "once. Is that okay ?$"

MoveTutor_Text_SwaggerTeach:
	.string "Hé ! Mon Pokémon, c’est de la balle !\n"
	.string "C’est le plus cool de tous les Pokémon !\p"
	.string "L’autre jour, j’ai dit ça devant le\n"
	.string "Président et je me suis fait\l"
	.string "remonter les bretelles.\p"
	.string "Du coup, j’essaie de me vanter un peu\n"
	.string "moins.\p"
	.string "Mais si tu veux, je peux apprendre\n"
	.string "Vantardise à un de tes Pokémon.$"

MoveTutor_Text_SwaggerDeclined:
	.string "Non ? Alors toi, tu ne comprends\n"
	.string "carrément rien aux Pokémon !$"

MoveTutor_Text_SwaggerWhichMon:
	.string "Cool. A quel Pokémon tu veux que\n"
	.string "j’enseigne Vantardise ?$"

MoveTutor_Text_SwaggerTaught:
	.string "Dorénavant, je complimenterai mes\n"
	.string "Pokémon et j’arrêterai de me vanter.$"

MoveTutor_Text_RolloutTeach:
	.string "Tu sais que si tu vas dans cette\n"
	.string "direction, tu peux avancer longtemps\l"
	.string "sans avoir à tourner ?\p"
	.string "Je suis sûr qu’on peut même y aller\n"
	.string "en roulant.\p"
	.string "Tiens, tu crois que tes Pokémon\n"
	.string "aimeraient rouler, eux aussi ?\p"
	.string "Je pourrais enseigner Roulade à\n"
	.string "l’un d’entre eux, si tu veux.$"

MoveTutor_Text_RolloutDeclined:
	.string "Je vois, tu es timide.\n"
	.string "Pas de problème, ça roule !$"

MoveTutor_Text_RolloutWhichMon:
	.string "Super ! Ce que j’aimerais que les\n"
	.string "Pokémon me ressemblent.$"

MoveTutor_Text_RolloutTaught:
	.string "Rouler dans l’herbe me met toujours\n"
	.string "de bonne humeur ! Ça roule !!!$"

MoveTutor_Text_FuryCutterTeach:
	.string "Il existe une capacité qui gagne en\n"
	.string "puissance quand on l’utilise plusieurs\l"
	.string "fois de suite.\p"
	.string "C’est une super capacité de type\n"
	.string "Insecte.\p"
	.string "Elle s’appelle Taillade.\n"
	.string "Je l’enseigne à un de tes Pokémon ?$"

MoveTutor_Text_FuryCutterDeclined:
	.string "On n’est pas sur la même longueur\n"
	.string "d’ondes.$"

MoveTutor_Text_FuryCutterWhichMon:
	.string "Super !\n"
	.string "Quel Pokémon est l’heureux élu ?$"

MoveTutor_Text_FuryCutterTaught:
	.string "Rien n’est plus beau qu’un Pokémon\n"
	.string "utilisant encore et encore cette\l"
	.string "capacité !$"

MoveTutor_MimicTeach:
	.string "Je suis jeune, mais j’aime copier le\n"
	.string "style des personnes âgées de la ville.\p"
	.string "Et si j’apprenais Copie à un\n"
	.string "de tes Pokémon ?\p"
	.string "Qu’en dis-tu, mon p’tit ?$"

MoveTutor_MimicDeclined:
	.string "Boudiou ! Les jeunes d’aujourd’hui,\n"
	.string "quelle ingratitude !$"

MoveTutor_Text_MimicWhichMon:
	.string "Oh, oh ! Je pense bien !\n"
	.string "A quel Pokémon dois-je enseigner\l"
	.string "Copie ?$"

MoveTutor_Text_MimicTaught:
	.string "Copie est une capacité très difficile à\n"
	.string "maîtriser.\p"
	.string "Qui sait, peut-être sauras-tu l’utiliser\n"
	.string "aussi bien que moi ?$"

MoveTutor_Text_MetronomeTeach:
	.string "Moi, j’ai des goûts de luxe !\n"
	.string "Mais je ne suis pas riche…\p"
	.string "Ce que j’aimerais pouvoir faire\n"
	.string "apparaître tout ce que je veux,\p"
	.string "juste en bougeant un doigt !\p"
	.string "Si tu veux, je peux apprendre\n"
	.string "Métronome à tes Pokémon.\p"
	.string "Rien n’apparaîtra mais ton Pokémon\n"
	.string "bougera un doigt. Tu veux ?$"

MoveTutor_Text_MetronomeDeclined:
	.string "D’accord. Si tu changes d’avis, je serai\n"
	.string "là.$"

MoveTutor_Text_MetronomeWhichMon:
	.string "Super ! A quel Pokémon dois-je\n"
	.string "enseigner cette capacité ?$"

MoveTutor_Text_MetronomeTaught:
	.string "Quand un Pokémon bouge le doigt\n"
	.string "comme un Métronome, plein de\l"
	.string "bonnes choses peuvent se produire.\p"
	.string "Ce serait tellement bien, si ça\n"
	.string "marchait aussi pour les humains !$"

MoveTutor_Text_SleepTalkTeach:
	.string "Tu sais, mon p’tit, ma femme a besoin de\n"
	.string "Puissance Cachée pour rester éveillée.\p"
	.string "Pour moi, c’est Blabla Dodo !\n"
	.string "Je dors, un point c’est tout !\p"
	.string "Si tu veux, je peux enseigner Blabla\n"
	.string "Dodo à un de tes Pokémon. Tu veux ?$"

MoveTutor_Text_SleepTalkDeclined:
	.string "Toi aussi, tu préfères lutter contre\n"
	.string "le sommeil avec Puissance Cachée…$"

MoveTutor_Text_SleepTalkWhichMon:
	.string "Ah, voilà qui est bien répondu !\n"
	.string "A quel Pokémon dois-je l’enseigner ?$"

MoveTutor_Text_SleepTalkTaught:
	.string "Je n’ai jamais bien compris le tour\n"
	.string "de magie de ma femme.\p"
	.string "J’aimerais le maîtriser aussi bien\n"
	.string "que Blabla Dodo…$"

MoveTutor_Text_SubstituteTeach:
	.string "Quand j’observe le monde, perchée\n"
	.string "sur ce toit…\p"
	.string "Je me dis qu’il y a tellement de choses\n"
	.string "à faire, de territoires à explorer, que\l"
	.string "j’aimerais vivre plusieurs vies à la fois.\p"
	.string "Je sais bien que c’est impossible,\n"
	.string "mais les journées sont trop courtes…\p"
	.string "Ça me fait penser… Et si j’enseignais\n"
	.string "Clonage à un de tes Pokémon ?$"

MoveTutor_Text_SubstituteDeclined:
	.string "Non ?\p"
	.string "Un Pokémon peut créer un double de\n"
	.string "lui-même avec… Enfin, c’est\l"
	.string "comme tu veux.$"

MoveTutor_Text_SubstituteWhichMon:
	.string "Hi, hi !\n"
	.string "A quel Pokémon dois-je enseigner\l"
	.string "Clonage ?$"

MoveTutor_Text_SubstituteTaught:
	.string "Nous, les humains, devrions profiter\n"
	.string "à fond de l’instant présent !\p"
	.string "Enfin, c’est ce que je pense !$"

MoveTutor_Text_DynamicPunchTeach:
	.string "Je n’en peux plus !\p"
	.string "C’est sans espoir !\p"
	.string "Je suis un Dresseur de type Combat,\n"
	.string "alors je n’arrive à rien dans l’Arène\l"
	.string "de Safrania !\p"
	.string "Tiens ! Prends ça ! Un coup de poing !\n"
	.string "Et encore ça ! Un autre coup de poing !\p"
	.string "Ne me fais pas ces yeux-là !\n"
	.string "Je ne frappe que le sol !\p"
	.string "Tu veux peut-être que j’enseigne\n"
	.string "Dynamopoing à un de tes Pokémon ?$"

MoveTutor_Text_DynamicPunchDeclined:
	.string "Tu te moques de moi ? Je frapperais bien\n"
	.string "autre chose que le sol, tu sais !$"

MoveTutor_Text_DynamicPunchWhichMon:
	.string "Tiens, voilà quelqu’un d’intelligent !\n"
	.string "A quel Pokémon dois-je l’enseigner ?$"

MoveTutor_Text_DynamicPunchTaught:
	.string "Je veux que tu gagnes à l’Arène\n"
	.string "de Safrania grâce à Dynamopoing !$"

MoveTutor_Text_DoubleEdgeTeach:
	.string "Bouh…\p"
	.string "Le Champion D’Arène de Jadielle\n"
	.string "est vraiment admirable.\p"
	.string "Ce qui veut dire que beaucoup de\n"
	.string "gens veulent le défier.\p"
	.string "Je n’ai même pas réussi à attirer son\n"
	.string "attention avec Damoclès !\p"
	.string "Est-ce que je peux enseigner Damoclès\n"
	.string "à un de tes Pokémon ?$"

MoveTutor_Text_DoubleEdgeDeclined:
	.string "Oh…\n"
	.string "Tu vois, toi aussi, tu me rejettes…$"

MoveTutor_Text_DoubleEdgeWhichMon:
	.string "A quel Pokémon dois-je enseigner\n"
	.string "Damoclès ?$"

MoveTutor_Text_DoubleEdgeTaught:
	.string "Je vais m’endurcir !\n"
	.string "Plus question de tomber amoureuse !$"

MoveTutor_Text_ExplosionTeach:
	.string "J’ai la ferme intention de faire quelque\n"
	.string "chose de ma vie, je te le dis !\p"
	.string "Regarde-moi bien, parce que je ne vais\n"
	.string "pas rester longtemps ici.\p"
	.string "On va entendre parler de moi !\n"
	.string "Ce sera une vraie Explosion !\p"
	.string "A propos d’Explosion… J’enseigne\n"
	.string "cette capacité à un de tes Pokémon ?$"

MoveTutor_Text_ExplosionDeclined:
	.string "Tu ne me fais pas confiance parce que\n"
	.string "j’ai décidé de partir, c’est ça ?$"

MoveTutor_Text_ExplosionWhichMon:
	.string "Super, ça va faire du bruit ! A quel\n"
	.string "Pokémon dois-je enseigner Explosion ?$"

MoveTutor_Text_ExplosionTaught:
	.string "Ça fait longtemps que j’enseigne\n"
	.string "Explosion aux Pokémon sans jamais\l"
	.string "penser à ma propre Explosion…\p"
	.string "Peut-être est-ce parce qu’au fond,\n"
	.string "je préfèrerais rester ici…$"
