gText_Oak_Welcome::
	.string "Salut ! Désolé de l’attente !\p"
	.string "Bienvenue dans le monde des Pokémon !\p"
	.string "Mon nom est Chen.\p"
	.string "On m’appelle\n"
	.string "le Professeur Pokémon.\p"
	.string "$"

gText_Oak_Pokemon::
	.string "Voici ce qu’on appelle un “Pokémon”.\p"
	.string "\n"
	.string "$"

gText_Oak_MainSpeech::
	.string "Ce monde est peuplé de créatures\n"
	.string "appelées Pokémon.\p"
	.string "Humains et Pokémon vivent en\n"
	.string "parfaite harmonie…\p"
	.string "Certains jouent avec les Pokémon,\n"
	.string "d’autres font des combats avec eux.\p"
	.string "Mais il reste beaucoup à apprendre\n"
	.string "sur nos amis les Pokémon.\p"
	.string "De nombreux mystères planent à\n"
	.string "leur sujet. Et c’est pourquoi\l"
	.string "j’étudie les Pokémon tous les jours.\p"
	.string "$"

gText_Oak_AndYouAre::
	.string "Et toi, qui es-tu ?$"

gText_Oak_BoyOrGirl::
	.string "Êtes-vous un garçon ou une fille ?$"

gText_Oak_WhatChallenge::
	.string "T’attends-tu à des défis\n"
	.string "durant ton voyage ?$"

gText_Oak_ChallengeSelected::
	.string "Ça m’a l’air d’être le bon\n"
	.string "niveau de défi !$"

gText_Oak_WhatsYourName::
	.string "Heu… C’est quoi ton nom ?$"

gText_Oak_SoItsPlayer::
	.string "Oh ! Tu es donc {PLAYER}{KUN} ?$"

gText_Oak_YourePlayer::
	.string "{PLAYER}{KUN}, on y va ?\p"
	.string "Ta quête est sur le point\n"
	.string "de commencer.\p"
	.string "$"

gText_Oak_AreYouReady::
	.string "Joies et périls paveront ta route…\p"
	.string "Un monde de rêves, de danger et\n"
	.string "de Pokémon t’attend !\p"
	.string "En avant !\p"
	.string "À plus tard !\p"
	.string "$"
