gText_ObtainedTheItem::
    .string "Obtenu : {STR_VAR_2}!$"

gText_TheBagIsFull::
    .string "Le Sac est plein…$"

gText_PutItemInPocket::
    .string "{PLAYER} met {STR_VAR_2} dans\n"
    .string "Poche {STR_VAR_3}.$"

gText_PlayerFoundOneItem::
    .string "{PLAYER} trouve {STR_VAR_2}!$"

gText_TooBadBagIsFull::
    .string "Dommage !\n"
    .string "Le Sac est plein.$"

gText_PlayerPutItemInBag::
    .string "{PLAYER} met {STR_VAR_2} dans\n"
    .string "le Sac.$"

gText_ObtainedTheDecor::
    .string "Obtenu : {STR_VAR_2}!$"

gText_NoRoomLeftForAnother::
    .string "Dommage ! Il n’y a plus assez de place\n"
    .string "pour {STR_VAR_2}…$"

gText_TheDecorWasTransferredToThePC::
    .string "Transfert de {STR_VAR_2} sur le PC.$"

gText_ObtainedTheItems::
    .string "Obtenu : {STR_VAR_1} {STR_VAR_2} !$"

gText_PlayerFoundItems::
    .string "{PLAYER} trouve {STR_VAR_1} {STR_VAR_2} !$"

gText_PutCoinsAwayInCoinCase::
	.string "{PLAYER} put the COINS away in\n"
	.string "the COIN CASE.$"

gText_FoundXCoins::
	.string "{PLAYER} found\n"
	.string "{STR_VAR_1} {STR_VAR_2}!$"

gText_FoundXItems::
	.string "{PLAYER} found\n"
	.string "{STR_VAR_1} {STR_VAR_2}(s)!$"

gText_CoinCaseIsFull::
	.string "Too bad!\n"
	.string "The COIN CASE is full…$"

gText_NothingToPutThemIn::
	.string "Too bad!\n"
	.string "There's nothing to put them in…$"
