gBirchDexRatingText_AreYouCurious::
	.string "Prof. Orme : Ah, {PLAYER}{KUN}!\p"
	.string "Tu veux que je te donne mon avis\n"
	.string "sur ton Pokédex ?$"

gBirchDexRatingText_Cancel::
	.string "Hum ? Oh, tu n’as pas attrapé assez\n"
	.string "de Pokémon pour que ça en vaille\l"
	.string "la peine.$"

gBirchDexRatingText_SoYouveSeenAndCaught::
	.string "Hum…\p"
	.string "Tu as rencontré {STR_VAR_1} Pokémon\n"
	.string "et tu en as attrapé {STR_VAR_2}…$"

gBirchDexRatingText_LessThan10::
	.string "Tu devrais aller plus souvent dans\n"
	.string "les herbes et mieux chercher\l"
	.string "les Pokémon.$"

gBirchDexRatingText_LessThan20::
	.string "Je suppose que tu as bien\n"
	.string "compris ça. Mais désormais,\l"
	.string "ça va devenir plus dur.$"

gBirchDexRatingText_LessThan30::
	.string "Certains Pokémon n’apparaissent\n"
	.string "que dans des zones précises.\l"
	.string "Sois tenace !$"

gBirchDexRatingText_LessThan40::
	.string "Bon, il pourrait être un peu plus\n"
	.string "rempli, mais il ressemble déjà plus\l"
	.string "à un Pokédex.$"

gBirchDexRatingText_LessThan50::
	.string "Hé, il commence à être plutôt\n"
	.string "pas mal. Continue sur ta lancée !$"

gBirchDexRatingText_LessThan60::
	.string "Est-ce que tu utilises des Cannes ?\n"
	.string "Il y a beaucoup de Pokémon\l"
	.string "dans la mer.$"

gBirchDexRatingText_LessThan70::
	.string "Plutôt que juste attraper des\n"
	.string "Pokémon, pourquoi ne pas aussi\l"
	.string "les faire évoluer ?$"

gBirchDexRatingText_LessThan80::
	.string "Ce Pokédex va être formidable.\n"
	.string "J’en ai bien l’impression.$"

gBirchDexRatingText_LessThan90::
	.string "Tu as collecté tout ça…\n"
	.string "Tu as un talent remarquable !$"

gBirchDexRatingText_LessThan100::
	.string "As-tu visité le Parc Safari ?\p"
	.string "J’ai entendu dire que certains\n"
	.string "Pokémon ne s’attrapent que là-bas.$"

gBirchDexRatingText_LessThan110::
	.string "Tu as atteint la barre des 100.\n"
	.string "C’est un Pokédex impressionnant !$"

gBirchDexRatingText_LessThan120::
	.string "En utilisant Éclate-Roc, tu peux\n"
	.string "trouver des Pokémon.$"

gBirchDexRatingText_LessThan130::
	.string "Tu devrais faire des échanges pour\n"
	.string "te procurer d’autres Pokémon.$"

gBirchDexRatingText_LessThan140::
	.string "Certains Pokémon évoluent quand\n"
	.string "ils aiment vraiment leur Dresseur.$"

gBirchDexRatingText_LessThan150::
	.string "Je ne savais pas qu’il y avait\n"
	.string "autant d’espèces de Pokémon\l"
	.string "à Johto.$"

gBirchDexRatingText_LessThan160::
	.string "Il arrive que certains Pokémon\n"
	.string "sortent en grand nombre, telle une\l"
	.string "horde sauvage.\p"
	.string "Ne rate pas ce genre d’occasion !$"

gBirchDexRatingText_LessThan170::
	.string "On a une bonne représentation des\n"
	.string "Pokémon de la région de Johto\l"
	.string "en regardant ton Pokédex.$"

gBirchDexRatingText_LessThan180::
	.string "Je pourrais déjà te donner le titre\n"
	.string "de Professeur Pokémon !$"

gBirchDexRatingText_LessThan190::
	.string "Avec un Pokédex aussi bien rempli,\n"
	.string "tu passes en professionnel !$"

gBirchDexRatingText_LessThan200::
	.string "Tu es à deux doigts de compléter\n"
	.string "ce Pokédex. Je le vois !$"

gBirchDexRatingText_DexCompleted::
	.string "Félicitations !\n"
	.string "Ton Pokédex est complet !$"

gBirchDexRatingText_OnANationwideBasis::
	.string "Hum…\n"
	.string "Sur l’ensemble du territoire…\p"
	.string "Tu as rencontré {STR_VAR_1} Pokémon\n"
	.string "et tu as attrapé {STR_VAR_2} Pokémon…$"

@ FRLG

PokedexRating_Text_HowIsPokedexComingAlong::
	.string "OAK: Good to see you!\n"
	.string "How is your POKéDEX coming along?\p"
	.string "Here, let me take a look.$"

PokedexRating_Text_SeenXOwnedY::
	.string "The amount of progress you've made\n"
	.string "on your POKéDEX is:\p"
	.string "{STR_VAR_1} POKéMON seen and\n"
	.string "{STR_VAR_2} POKéMON owned.\p"
	.string "{FONT_NORMAL}PROF. OAK's rating:$"

PokedexRating_Text_LessThan10::
	.string "You still have lots to do.\p"
	.string "Go into every patch of grass you\n"
	.string "see and look for POKéMON!$"

PokedexRating_Text_LessThan20::
	.string "It looks as if you're getting on\n"
	.string "the right track!\p"
	.string "I've given one of my AIDES a FLASH\n"
	.string "HM. Make sure you go get it!$"

PokedexRating_Text_LessThan30::
	.string "Your POKéDEX could use a bit more\n"
	.string "volume still!\p"
	.string "Try to catch other species of\n"
	.string "POKéMON!$"

PokedexRating_Text_LessThan40::
	.string "Good, it's apparent that you're\n"
	.string "trying hard!\p"
	.string "I've given one of my AIDES an\n"
	.string "ITEMFINDER. Be sure to collect it!$"

PokedexRating_Text_LessThan50::
	.string "Your POKéDEX is coming along quite\n"
	.string "well!\p"
	.string "I've given one of my AIDES an\n"
	.string "AMULET COIN. Be sure to get it!$"

PokedexRating_Text_LessThan60::
	.string "Ah, you've finally topped 50\n"
	.string "species!\p"
	.string "I've given one of my AIDES an EXP.\n"
	.string "SHARE. Be sure to go get it!$"

PokedexRating_Text_LessThan70::
	.string "Hoho! This is turning into quite the\n"
	.string "respectable POKéDEX!$"

PokedexRating_Text_LessThan80::
	.string "Very good!\p"
	.string "I think you'll collect even more\n"
	.string "POKéMON by going fishing!$"

PokedexRating_Text_LessThan90::
	.string "Wonderful! Let me guess… You\n"
	.string "like to collect things, don't you?$"

PokedexRating_Text_LessThan100::
	.string "I'm impressed!\n"
	.string "It must have been difficult to do!$"

PokedexRating_Text_LessThan110::
	.string "You've finally hit 100 species!\n"
	.string "I can't believe how good you are!$"

PokedexRating_Text_LessThan120::
	.string "You even have the evolved forms\n"
	.string "of POKéMON! Super!$"

PokedexRating_Text_LessThan130::
	.string "Excellent! Trade with friends to\n"
	.string "get some more!$"

PokedexRating_Text_LessThan140::
	.string "Outstanding!\n"
	.string "You've become a real pro at this!$"

PokedexRating_Text_LessThan150::
	.string "I have nothing left to say!\n"
	.string "You're the POKéMON PROFESSOR now!$"

PokedexRating_Text_Complete::
	.string "Your POKéDEX is entirely complete!\n"
	.string "Congratulations!!$"

PokedexRating_Text_NationalDexSeenXOwnedY::
	.string "And your NATIONAL POKéDEX is:\p"
	.string "{STR_VAR_1} POKéMON seen and\n"
	.string "{STR_VAR_2} POKéMON owned.$"

PokedexRating_Text_LookForwardToFilledNationalDex::
	.string "I'll be looking forward to seeing\n"
	.string "you fill the NATIONAL POKéDEX!$"

PokedexRating_Text_YouveCompletedDex::
	.string "Finally…\p"
	.string "You've finally completed the\n"
	.string "POKéDEX!\p"
	.string "It's magnificent!\n"
	.string "Truly, this is a fantastic feat!$"

PokedexRating_Text_Wroooaaarrr::
	.string "Wroooooooaaaaaarrrr!$"

PokedexRating_Text_ThankYouMadeDreamReality::
	.string "Thank you, {PLAYER}!\n"
	.string "Sincerely, thank you!\l"
	.string "You've made my dream a reality!$"

PokedexRating_Text_LoveSeeingYourPokedex::
	.string "OAK: Ah, welcome!\p"
	.string "Tell me, how is your POKéDEX\n"
	.string "coming along?\p"
	.string "Wahaha!\p"
	.string "Actually, I know how it is, but I\n"
	.string "love seeing it anyway!\p"
	.string "Let's see…$"

@ HnS (mostly directly copied from HGSS)

gElmDexRatingText_GoFindMrPokemon::
	.string "PROF. ELM: Ah, {PLAYER}{KUN}!\p"
	.string "Have you found MR. POKéMON's\n"
	.string "home yet? It is on ROUTE 30,\p"
	.string "you can't miss it!$"

gElmDexRatingText_Robbery::
	.string "PROF. ELM: {PLAYER}{KUN}!\p"
	.string "Get here quick! Something\n"
	.string "awful has happened!$"

gElmDexRatingText_AreYouCurious::
	.string "PROF. ELM: Ah, {PLAYER}{KUN}!\p"
	.string "Are you curious about how your\n"
	.string "POKéDEX is coming along?$"

gElmDexRatingText_AreYouCuriousNational::
	.string "PROF. ELM: Ah, {PLAYER}{KUN}!\p"
	.string "Are you curious about how your\n"
	.string "National POKéDEX is coming along?$"

gJohtoDexRatingText_LessThan10::
	.string "Look for POKéMON in grassy areas!$"

gJohtoDexRatingText_LessThan20::
	.string "Good. I see you understand how to\n"
	.string "use Poké Balls.$"

gJohtoDexRatingText_LessThan35::
	.string "You're getting good at this,\n"
	.string "but you have a long way to go.$"

gJohtoDexRatingText_LessThan50::
	.string "Hmm, you're catching POKéMON at a\n"
	.string "decent pace!$"

gJohtoDexRatingText_LessThan65::
	.string "You're trying--I can see that.\n"
	.string "Your POKéDEX is coming together.$"

gJohtoDexRatingText_LessThan80::
	.string "You're training them well. You know\n"
	.string "some POKéMON don't evolve just by\p"
	.string "battling with others, right?$"

gJohtoDexRatingText_LessThan95::
	.string "Do you have a Fishing Rod?\n"
	.string "There are some POKéMON that can\p"
	.string "only be found by fishing!$"

gJohtoDexRatingText_LessThan110::
	.string "Excellent! You seem to be good at\n"
	.string "collecting things!$"

gJohtoDexRatingText_LessThan125::
	.string "Some POKéMON only appear during\n"
	.string "certain times of the day.$"

gJohtoDexRatingText_LessThan140::
	.string "Your POKéDEX is really filling up.\n"
	.string "Keep up the good work!$"

gJohtoDexRatingText_LessThan155::
	.string "I'm impressed.\n"
	.string "You're evolving POKéMON, not just\p"
	.string "catching them.$"

gJohtoDexRatingText_LessThan170::
	.string "If you can learn how to use the\n"
	.string "custom Poké Balls made by Kurt\p"
	.string "effectively, you'll be able to catch\n"
	.string "POKéMON better!$"

gJohtoDexRatingText_LessThan185::
	.string "When you trade POKéMON, you can\n"
	.string "also trade information. Your\p"
	.string "friends can really help you!$"

gJohtoDexRatingText_LessThan200::
	.string "Are you trading your POKéMON?\n"
	.string "It's tough to do this alone!$"

gJohtoDexRatingText_LessThan215::
	.string "Wow! You've reached 200!\n"
	.string "Your POKéDEX is looking great!$"

@ Taken from Platinum
gJohtoDexRatingText_LessThan230::
	.string "You've proven yourself capable.\n"
    .string "There's nothing to worry about.\p"
    .string "Keep catching POKéMON the way\n"
    .string "you've been doing so far.$"

@ Taken from Platinum
gJohtoDexRatingText_LessThan245::
	.string "Your POKéDEX is well on the way to\n"
	.string "being filled up.\p"
	.string "This POKéDEX can be considered a\n"
	.string "journal of your adventure.$"

gJohtoDexRatingText_LessThan260::
	.string "You've found so many POKéMON!\n"
	.string "You've really helped my studies!$"

gJohtoDexRatingText_LessThan275::
	.string "Magnificent! You have the ability\n"
	.string "to become a great POKéMON\p"
	.string "Professor someday!$"

gJohtoDexRatingText_LessThanMaxDex::
	.string "Your POKéDEX is amazing!\n"
	.string "You're ready to turn professional!$"

gJohtoDexRatingText_Complete::
	.string "Wow!\n"
	.string "That is a complete Johto POKéDEX!\p"  
	.string "Thanks to you, {PLAYER}, the Johto\n"
	.string "POKéDEX is complete!\p"
	.string "Wow...\n"
	.string "You've done an incredible job!$"

gNationalDexRatingText_LessThan100::
	.string "The goal may be far away, but don't\n"
	.string "give up yet! Keep going!$"

gNationalDexRatingText_LessThan150::
	.string "Don't forget, some POKéMON only\n"
	.string "appear at certain times of the day!$"

gNationalDexRatingText_LessThan200::
	.string "If you break rocks, some POKéMON\n"
	.string "that were hiding there might come\p"
	.string "jumping out!$"

gNationalDexRatingText_LessThan250::
	.string "That's wonderful you've been able\n"
	.string "to gather this many POKéMON!\p"
	.string "The path ahead is long. Keep up the\n"
	.string "great work!$"

gNationalDexRatingText_LessThan300::
	.string "If you Headbutt a tree, sometimes\n"
	.string "a POKéMON might fall out!$"

gNationalDexRatingText_LessThan350::
	.string "A lot of POKéMON not found in the\n"
	.string "Johto region like to congregate\p"
	.string "at the Safari Zone$"

gNationalDexRatingText_LessThan400::
@	.string "Music on the radio might also\n"
@	.string "entice POKéMON to leap out$"
	.string "There are hidden locations all\n"
	.string "over the world containing rare\p"
	.string "and unusual POKéMON, try to find\n"
	.string "them all!$"

gNationalDexRatingText_LessThan435::
	.string "Wow, you've gotten so far...!\n"
	.string "I'm actually a little surprised!$"

gNationalDexRatingText_LessThan465::
	.string "This is a critical moment!\n"
	.string "You can't become discouraged!$"

gNationalDexRatingText_LessThan475::
	.string "Just a little more!\n"
	.string "I've got high expectations for you!$"

gNationalDexRatingText_LessThanMaxDex::
	.string "I have never before in all my years\n"
	.string "seen such an incredible Trainer!$"

gNationalDexRatingText_Complete::
	.string "Excellent! That is an amazing\n"
	.string "National POKéDEX!\p"
	.string "Wow...{PAUSE 10}\p"
	.string "You've lived up to my\n"
	.string "expectations wonderfully!\p"
	.string "No, you've exceeded them, {PLAYER}.\n"
	.string "You've become an amazing Trainer!\p"
	.string "Thank you, {PLAYER}!$"
