gBirchDexRatingText_GoFindMrPokemon::
    .string "Prof. Orme : Ah, {PLAYER}{KUN} !\p"
	.string "As-tu trouvé la maison de\n"
	.string "M. Pokémon ? Elle est sur la route 30,\p"
	.string "tu ne peux pas la louper !$"

gBirchDexRatingText_Robbery::
    .string "Prof. Orme : {PLAYER}{KUN} !\p"
	.string "C'est… C'est terrible ! C'est… Affreux !\n"
	.string "Que faire ? Oh, non… Reviens-vite !$"

gBirchDexRatingText_AreYouCurious::
	.string "Prof. Orme : Ah, {PLAYER}{KUN}!\p"
	.string "Tu veux que je te donne mon avis\n"
	.string "sur ton Pokédex ?$"

gBirchDexRatingText_Cancel::
	.string "Hum ? Oh, tu n’as pas attrapé assez\n"
	.string "de Pokémon pour que ça en vaille\l"
	.string "la peine.$"

gBirchDexRatingText_SoYouveSeenAndCaught::
	.string "Hum…\p"
	.string "Tu as rencontré {STR_VAR_1} Pokémon\n"
	.string "et tu en as attrapé {STR_VAR_2}…$"

gBirchDexRatingText_LessThan10::
	.string "Tu devrais aller plus souvent dans\n"
	.string "les herbes et mieux chercher\l"
	.string "les Pokémon.$"

gBirchDexRatingText_LessThan20::
	.string "Je suppose que tu as bien\n"
	.string "compris ça. Mais désormais,\l"
	.string "ça va devenir plus dur.$"

gBirchDexRatingText_LessThan30::
	.string "Certains Pokémon n’apparaissent\n"
	.string "que dans des zones précises.\l"
	.string "Sois tenace !$"

gBirchDexRatingText_LessThan40::
	.string "Bon, il pourrait être un peu plus\n"
	.string "rempli, mais il ressemble déjà plus\l"
	.string "à un Pokédex.$"

gBirchDexRatingText_LessThan50::
	.string "Hé, il commence à être plutôt\n"
	.string "pas mal. Continue sur ta lancée !$"

gBirchDexRatingText_LessThan60::
	.string "Est-ce que tu utilises des Cannes ?\n"
	.string "Il y a beaucoup de Pokémon\l"
	.string "dans la mer.$"

gBirchDexRatingText_LessThan70::
	.string "Plutôt que juste attraper des\n"
	.string "Pokémon, pourquoi ne pas aussi\l"
	.string "les faire évoluer ?$"

gBirchDexRatingText_LessThan80::
	.string "Ce Pokédex va être formidable.\n"
	.string "J’en ai bien l’impression.$"

gBirchDexRatingText_LessThan90::
	.string "Tu as collecté tout ça…\n"
	.string "Tu as un talent remarquable !$"

gBirchDexRatingText_LessThan100::
	.string "As-tu visité le Parc Safari ?\p"
	.string "J’ai entendu dire que certains\n"
	.string "Pokémon ne s’attrapent que là-bas.$"

gBirchDexRatingText_LessThan110::
	.string "Tu as atteint la barre des 100.\n"
	.string "C’est un Pokédex impressionnant !$"

gBirchDexRatingText_LessThan120::
	.string "En utilisant Éclate-Roc, tu peux\n"
	.string "trouver des Pokémon.$"

gBirchDexRatingText_LessThan130::
	.string "Tu devrais faire des échanges pour\n"
	.string "te procurer d’autres Pokémon.$"

gBirchDexRatingText_LessThan140::
	.string "Certains Pokémon évoluent quand\n"
	.string "ils aiment vraiment leur Dresseur.$"

gBirchDexRatingText_LessThan150::
	.string "Je ne savais pas qu’il y avait\n"
	.string "autant d’espèces de Pokémon\l"
	.string "à Johto.$"

gBirchDexRatingText_LessThan160::
	.string "Il arrive que certains Pokémon\n"
	.string "sortent en grand nombre, telle une\l"
	.string "horde sauvage.\p"
	.string "Ne rate pas ce genre d’occasion !$"

gBirchDexRatingText_LessThan170::
	.string "On a une bonne représentation des\n"
	.string "Pokémon de la région de Johto\l"
	.string "en regardant ton Pokédex.$"

gBirchDexRatingText_LessThan180::
	.string "Je pourrais déjà te donner le titre\n"
	.string "de Professeur Pokémon !$"

gBirchDexRatingText_LessThan190::
	.string "Avec un Pokédex aussi bien rempli,\n"
	.string "tu passes en professionnel !$"

gBirchDexRatingText_LessThan200::
	.string "Tu es à deux doigts de compléter\n"
	.string "ce Pokédex. Je le vois !$"

gBirchDexRatingText_DexCompleted::
	.string "Félicitations !\n"
	.string "Ton Pokédex est complet !$"

gBirchDexRatingText_OnANationwideBasis::
	.string "Hum…\n"
	.string "Sur l’ensemble du territoire…\p"
	.string "Tu as rencontré {STR_VAR_1} Pokémon\n"
	.string "et tu as attrapé {STR_VAR_2} Pokémon…$"

gBirchDexRatingText_CaughtAllNational::
	.string "Hmhm…\n"
	.string "On a nationwide basis…\p"
	.string "You've seen {STR_VAR_1} Pokémon,\n"
	.string "and you've caught {STR_VAR_2} Pokémon…\p"
	.string "C'est incroyable, {PLAYER}!\p"
	.string "Tu as complété le Pokédex \n"
	.string "National ! Félicitations !$"
