Questionnaire_Text_FillOut::
.string "Il y a un questionnaire…\n"
.string "Voulez-vous y répondre ?$"

Questionnaire_Text_ThankYou::
.string "Merci d’avoir pris le temps de\n"
.string "répondre à notre questionnaire.\p"
.string "Vos réponses nous permettront\n"
.string "de mieux vous servir.$"

Questionnaire_Text_YouKnowThoseWordsGift::
.string "Oh, bonjour !\n"
.string "Vous connaissez ces mots ?\p"
.string "Donc vous devez aussi\n"
.string "connaître le Cadeau Mystère.\p"
.string "A partir de maintenant, vous allez\n"
.string "recevoir des Cadeaux Mystères !$"

Questionnaire_Text_YouCanAccessMysteryGift::
.string "Après avoir sauvegardé, vous\n"
.string "aurez accès aux Cadeaux Mystères !$"

Questionnaire_Text_YouKnowThoseWordsEvent::
.string "Oh, bonjour !\n"
.string "Vous connaissez ces mots ?\p"
.string "Donc vous devez aussi\n"
.string "connaître les Évènements Mystère.$"

Questionnaire_Text_YouCanAccessMysteryEvent::
.string "Après avoir sauvegardé, vous\n"
.string "aurez accès aux Évènements Mystère.$"

MysteryGift_Text_TheresATicketForYou::
.string "Merci d’utiliser le système\n"
.string "Évènements Mystère.\p"
.string "Vous devez être {PLAYER}.\n"
.string "Il y a un ticket pour vous.$"

MysteryGift_Text_TryUsingItAtLilycovePort::
.string "Il peut être utilisé au port de\n"
.string "Nénucrique.\p"
.string "Essayez-le pour voir de quoi \n"
.string "il s’agit.$"
