ShoalCave_LowTideEntranceRoom_Text_AreYouPlanningOnGoingInThere:
	.string "Tu as prévu d’aller loin ?\p"
	.string "Et si tu m’apportais des Sels Tréfonds\n"
	.string "et des CO. Tréfonds ?\p"
	.string "Je peux te préparer quelque chose\n"
	.string "de bon si tu m’apportes ce qu’il faut.$"

ShoalCave_LowTideEntranceRoom_Text_BringMe4ShoalSaltAndShells:
	.string "Si tu m’apportais quatre Sels Tréfonds\n"
	.string "et quatre CO. Tréfonds, je pourrais te\l"
	.string "faire un Grelot Coque.\p"
	.string "Tu peux te procurer ces ingrédients\n"
	.string "tous les jours.$"

ShoalCave_LowTideEntranceRoom_Text_WouldYouLikeShellBell:
	.string "Oh, hé ! Des Sels Tréfonds et des \n"
	.string "CO. Tréfonds ! Et suffisamment !\p"
	.string "Tu veux que je les utilise\n"
	.string "pour faire un Grelot Coque ?$"

ShoalCave_LowTideEntranceRoom_Text_MakeShellBellRightAway:
	.string "Bon, d’accord ! Je te fais un\n"
	.string "Grelot Coque sur-le-champ.\p"
	.string "… … … … … … … …\n"
	.string "… … … … … … … …\p"
	.string "Voilà ! C’est prêt !$"

ShoalCave_LowTideEntranceRoom_Text_ExplainShellBell:
	.string "Gardes-en pour un Pokémon.\n"
	.string "Il va adorer ça, c’est sûr !\p"
	.string "Quoi, le carillon du Grelot Coque…\n"
	.string "Sublime !\p"
	.string "Tu peux avoir ses ingrédients tous les\n"
	.string "jours. Alors je peux t’en faire d’autres.$"

ShoalCave_LowTideEntranceRoom_Text_WantedToMakeShellBell:
	.string "Oh… Dans ce cas…\n"
	.string "Je voulais faire un Grelot Coque…$"

ShoalCave_LowTideEntranceRoom_Text_NoSpaceInYourBag:
	.string "Tu n’as pas assez de place dans ton Sac\n"
	.string "pour recevoir ça.\p"
	.string "Tu devrais faire de la place et\n"
	.string "revenir pour avoir un Grelot Coque.$"

ShoalCave_Text_WasShoalSaltNowNothing:
	.string "Il y avait du Sel Tréfonds ici.\n"
	.string "Mais il n’y a plus rien.$"

ShoalCave_Text_WasShoallShellNowNothing:
	.string "Il y avait un CoquilleTréfonds ici.\n"
	.string "Mais il n’y a plus rien.$"
