gTrickHouse_Mechadoll_Oddish::
    .string "Mystherbe$"

gTrickHouse_Mechadoll_Poochyena::
    .string "Medhyèna$"

gTrickHouse_Mechadoll_Taillow::
    .string "Nirondelle$"

gTrickHouse_Mechadoll_Azurill::
    .string "Azurill$"

gTrickHouse_Mechadoll_Lotad::
    .string "Nénupiot$"

gTrickHouse_Mechadoll_Wingull::
    .string "Goélise$"

gTrickHouse_Mechadoll_Dustox::
    .string "Papinox$"

gTrickHouse_Mechadoll_Zubat::
    .string "Nosferapti$"

gTrickHouse_Mechadoll_Nincada::
    .string "Ningale$"

gTrickHouse_Mechadoll_Ralts::
    .string "Tarsal$"

gTrickHouse_Mechadoll_Zigzagoon::
    .string "Zigzaton$"

gTrickHouse_Mechadoll_Slakoth::
    .string "Parecool$"

gTrickHouse_Mechadoll_Poochyena2::
    .string "Medhyèna$"

gTrickHouse_Mechadoll_Shroomish::
    .string "Balignon$"

gTrickHouse_Mechadoll_Zigzagoon2::
    .string "Zigzaton$"

gTrickHouse_Mechadoll_Poochyena3::
    .string "Medhyèna$"

gTrickHouse_Mechadoll_Zubat2::
    .string "Nosferapti$"

gTrickHouse_Mechadoll_Carvanha::
    .string "Carvanha$"

gTrickHouse_Mechadoll_BurnHeal::
    .string "Anti-Brûle$"

gTrickHouse_Mechadoll_HarborMail::
    .string "Lettres Port$"

gTrickHouse_Mechadoll_SamePrice::
    .string "Même prix$"

gTrickHouse_Mechadoll_60Yen::
    .string "60¥$"

gTrickHouse_Mechadoll_55Yen::
    .string "55¥$"

gTrickHouse_Mechadoll_Nothing::
    .string "Rien$"

gTrickHouse_Mechadoll_CostMore::
    .string "Oui$"

gTrickHouse_Mechadoll_CostLess::
    .string "Non$"

gTrickHouse_Mechadoll_SamePrice2::
    .string "Même prix$"

gTrickHouse_Mechadoll_Male::
    .string "Plus d’hommes$"

gTrickHouse_Mechadoll_Female::
    .string "Plus de femmes$"

gTrickHouse_Mechadoll_Neither::
    .string "Aucun des deux$"

gTrickHouse_Mechadoll_ElderlyMen::
    .string "Plus de vieux messieurs$"

gTrickHouse_Mechadoll_ElderlyLadies::
    .string "Plus de vieilles dames$"

gTrickHouse_Mechadoll_SameNumber::
    .string "Le même nombre$"

gTrickHouse_Mechadoll_None::
    .string "Aucune$"

gTrickHouse_Mechadoll_One::
    .string "1$"

gTrickHouse_Mechadoll_Two::
    .string "2$"

gTrickHouse_Mechadoll_Two2::
    .string "2$"

gTrickHouse_Mechadoll_Three::
    .string "3$"

gTrickHouse_Mechadoll_Four::
    .string "4$"

gTrickHouse_Mechadoll_Six::
    .string "6$"

gTrickHouse_Mechadoll_Seven::
    .string "7$"

gTrickHouse_Mechadoll_Eight::
    .string "8$"

gTrickHouse_Mechadoll_Six2::
    .string "6$"

gTrickHouse_Mechadoll_Seven2::
    .string "7$"

gTrickHouse_Mechadoll_Eight2::
    .string "8$"
