LilycoveCity_ContestLobby_Text_InterviewRequest:
	.string "Bonjour ! Vous étiez dans un Concours\n"
	.string "Pokémon, n’est-ce pas ?\p"
	.string "Je reconnais votre Pokémon.\p"
	.string "Je suis journaliste. Je réalise un\n"
	.string "reportage sur les Concours Pokémon.\p"
	.string "Je peux me permettre de vous poser\n"
	.string "quelques questions ?$"

LilycoveCity_ContestLobby_Text_DescribeContest:
	.string "Vous voulez bien ? Super !\n"
	.string "Merci.\p"
	.string "Rapidement, comment décririez-vous le\n"
	.string "Concours auquel vous avez participé ?$"

LilycoveCity_ContestLobby_Text_WhatImageWhenYouHearX:
	.string "Oh, je vois.\n"
	.string "Quelle déclaration incroyable.\p"
	.string "Cela donne un bon aperçu de la\n"
	.string "façon dont s’est déroulé le Concours.\p"
	.string "J’ai une dernière question.\p"
	.string "Lorsque vous entendez\n"
	.string "“{STR_VAR_2}”,\l"
	.string "ça vous évoque quoi ?$"

LilycoveCity_ContestLobby_Text_ThatsAllForInterview:
	.string "Je vois !\p"
	.string "C’est comme ça que vous percevez le\n"
	.string "concept de “{STR_VAR_2}”.\p"
	.string "Merci !\n"
	.string "Vous m’avez donné de bonnes idées.\p"
	.string "Je vais pouvoir réaliser un chouette\n"
	.string "reportage sur les Concours Pokémon.\p"
	.string "Avec un peu de chance, ce reportage\n"
	.string "passera même à la télé.\l"
	.string "J’espère que vous ne le raterez pas !$"

LilycoveCity_ContestLobby_Text_PleaseDoShareStoryWithMe:
	.string "Oh, quel dommage…\p"
	.string "Eh bien, si vous entendez parler d’une\n"
	.string "histoire intéressante, revenez me voir.$"

LilycoveCity_ContestLobby_Text_LookingForwardToNextContest:
	.string "Je suivrai votre prochain Concours\n"
	.string "Pokémon avec intérêt.$"

gTVBravoTrainerText00::
	.string "Youhou !\n"
	.string "C’est l’heure de Dresseur Spécial !\p"
	.string "Nous allons vous présenter un\n"
	.string "Pokémon appartenant à {STR_VAR_1}.\p"
	.string "Sur le thème {STR_VAR_2}, ce Pokémon\n"
	.string "a gagné un Concours\l"
	.string "catégorie {STR_VAR_3}.$"

gTVBravoTrainerText01::
	.string "Et voici {STR_VAR_2} le {STR_VAR_1}!\p"
	.string "Il est surnommé {STR_VAR_2}…\p"
	.string "“{STR_VAR_3}” !\n"
	.string "Son surnom l’évoque déjà !$"

gTVBravoTrainerText02::
	.string "Quoi qu’il en soit, quand le Dresseur\n"
	.string "{STR_VAR_1} a inscrit ce Pokémon dans un \l"
	.string "Concours, nous avons réussi à lui poser\l"
	.string "quelques questions sur son partenaire.$"

gTVBravoTrainerText03::
	.string "A propos du Concours,\n"
	.string "{STR_VAR_1} a déclaré avec un sourire :\l"
	.string "“{STR_VAR_2}” !\p"
	.string "Le Pokémon de {STR_VAR_1} a pris la place\n"
	.string "numéro {STR_VAR_3} du Concours.\p"
	.string "Cette phrase résume bien l’état\n"
	.string "d’esprit de {STR_VAR_1} en ce moment !$"

gTVBravoTrainerText04::
	.string "A propos du Concours,\n"
	.string "{STR_VAR_1} a déclaré avec une pointe\l"
	.string "d’amertume : “{STR_VAR_2}”.\p"
	.string "Le Pokémon de {STR_VAR_1} a pris la place\n"
	.string "numéro {STR_VAR_3} du Concours.\p"
	.string "Il me semble que la déception de\n"
	.string "{STR_VAR_1} est tout à fait évidente !$"

gTVBravoTrainerText05::
	.string "Vous aimeriez peut-être savoir comment\n"
	.string "{STR_VAR_1} conçoit la qualité {STR_VAR_2}?\p"
	.string "Évidemment !\n"
	.string "Donc, nous lui avons demandé !\p"
	.string "La réponse est claire et concise :\n"
	.string "“{STR_VAR_3}”.\p"
	.string "Voilà comment {STR_VAR_1} définit la\n"
	.string "qualité {STR_VAR_2}!$"

gTVBravoTrainerText06::
	.string "La dernière démo, {STR_VAR_2},\n"
	.string "utilisée par {STR_VAR_1} était\l"
	.string "tout à fait “{STR_VAR_3}” !$"

gTVBravoTrainerText07::
	.string "Bravo, {STR_VAR_1}!\n"
	.string "Bravo, {STR_VAR_2}!\p"
	.string "J’espère que nous pourrons encore\n"
	.string "voir {STR_VAR_1} gravir les échelons de\l"
	.string "la gloire !\p"
	.string "Bien, le temps qui nous est accordé est\n"
	.string "désormais écoulé ! A vous les studios !$"

gTVBravoTrainerText08::
	.string "Et voici le {STR_VAR_1} du Dresseur !$"

BattleFrontier_BattleTowerLobby_Text_InterviewRequest::
	.string "Bonjour ! C’est vous qui venez de vous\n"
	.string "battre, n’est-ce pas ?\p"
	.string "J’interviewe tous les Dresseurs\n"
	.string "du coin.\p"
	.string "Vous pouvez me donner vos impressions\n"
	.string "sur le combat ?$"

BattleFrontier_BattleTowerLobby_Text_HowDidBattleTowerTurnOut::
	.string "Vraiment ? Vous acceptez ?\n"
	.string "Merci !\l"
	.string "Donc, heu…\p"
	.string "Comment ça s’est passé dans la Tour de\n"
	.string "Combat ?\p"
	.string "En gardez-vous une bonne impression ?\n"
	.string "Ou une mauvaise impression ?$"

BattleFrontier_BattleTowerLobby_Text_SorryWeDisturbedYou::
	.string "Oh…\n"
	.string "Je m’excuse du dérangement.\p"
	.string "J’espère que vous accepterez\n"
	.string "de nous répondre lors de votre\l"
	.string "prochaîne visite.$"

BattleFrontier_BattleTowerLobby_Text_ObviousYouHadGreatBattle::
	.string "Mais bien sûr !\p"
	.string "Cette incroyable lueur de satisfaction\n"
	.string "dans vos yeux…\p"
	.string "De toute évidence, vous avez fait un\n"
	.string "très beau combat.$"

BattleFrontier_BattleTowerLobby_Text_DifficultToMakeBattleTurnOutAsPlanned::
	.string "Oh, je vois…\p"
	.string "Oui, les combats ne se déroulent pas\n"
	.string "toujours comme prévu.$"

BattleFrontier_BattleTowerLobby_Text_DescribeYourBattle::
	.string "Une dernière petite question ?\p"
	.string "Si vous deviez résumer vos impressions\n"
	.string "sur ce combat, que diriez-vous ?$"

BattleFrontier_BattleTowerLobby_Text_ThatsGreatLine::
	.string "Incroyable !\p"
	.string "Quelle déclaration ! Bonne chance pour\n"
	.string "vos prochains combats.\p"
	.string "A bientôt, j’espère !$"

BattleFrontier_BattleTowerLobby_Text_SilentType::
	.string "Oh, je vois…\p"
	.string "Mais être du genre silencieux, c’est\n"
	.string "bien aussi, non ?\p"
	.string "J’espère avoir de nouveau l’occasion\n"
	.string "de parler avec vous !$"

BattleFrontier_BattleTowerLobby_Text_LookingForwardToNextBattle::
	.string "J’ai hâte que vous fassiez votre\n"
	.string "prochain combat !$"

BravoTrainerBattleTower_Text_Intro::
	.string "Ouais !\n"
	.string "C’est l’heure du Dresseur Spécial !\p"
	.string "Nous allons vous présenter {STR_VAR_1}, qui\n"
	.string "a relevé le défi de la Tour de Combat !\p"
	.string "Pour ce défi, {STR_VAR_1} avait inscrit\n"
	.string "son malicieux {STR_VAR_2}.$"

BravoTrainerBattleTower_Text_NewRecord::
	.string "Ils ont tous les deux établi le nouveau\n"
	.string "record de {STR_VAR_2} victoires consécutives\p"
	.string "au {STR_VAR_1} de la compétition.\n"
	.string "Bravo !$"

BravoTrainerBattleTower_Text_Lost::
	.string "Ils se sont finalement inclinés devant\n"
	.string "{STR_VAR_1} lors du match numéro {STR_VAR_2}.\l"
	.string "Très bel essai, Dresseur !\p"
	.string "Affronter {STR_VAR_1} aussi tôt dans la\n"
	.string "compétition, quelle malchance !\p"
	.string "Nous avons demandé au Dresseur ses\n"
	.string "impressions sur {STR_VAR_1}.$"

BravoTrainerBattleTower_Text_Won::
	.string "Ils ont triomphé en combattant avec\n"
	.string "brio {STR_VAR_2} de {STR_VAR_1}.\l"
	.string "Bravo, Dresseur !\p"
	.string "Ils ont même battu {STR_VAR_1}…\n"
	.string "Étonnant ! Époustouflant !\p"
	.string "Nous avons demandé au Dresseur ses\n"
	.string "impressions au moment de la victoire.$"

BravoTrainerBattleTower_Text_LostFinal::
	.string "Après une série de victoires, ils ont\n"
	.string "perdu devant {STR_VAR_2} de\l"
	.string "{STR_VAR_1}, l’obstacle final.\p"
	.string "Très bel essai, Dresseur !\p"
	.string "Mais il faut bien avouer qu’il y a peu\n"
	.string "de combinaisons aussi réussies que\l"
	.string "{STR_VAR_1} et {STR_VAR_2}.\p"
	.string "Nous avons demandé au Dresseur ses\n"
	.string "impressions sur ce couple infernal.$"

BravoTrainerBattleTower_Text_Satisfied::
	.string "Voici la déclaration du Dresseur :\n"
	.string "“Entière satisfaction !”\p"
	.string "N’est-ce pas rafraîchissant ?\n"
	.string "Bravo, Dresseur !\p"
	.string "N’est-ce pas grandiose de pouvoir se\n"
	.string "battre jusqu’à la satisfaction totale ?\p"
	.string "J’ai vraiment compris l’état d’esprit\n"
	.string "du Dresseur quand il a déclaré :$"

BravoTrainerBattleTower_Text_Unsatisfied::
	.string "Voici la déclaration du Dresseur : “On ne\n"
	.string "peut pas parler de satisfaction…”\p"
	.string "Visiblement, notre Dresseur était \n"
	.string "quelque peu abattu.\p"
	.string "Mais il faut dire qu’il est dur de sortir\n"
	.string "du combat pleinement satisfait, non ?\p"
	.string "J’ai mieux compris l’état d’esprit\n"
	.string "du Dresseur quand il a déclaré :$"

BravoTrainerBattleTower_Text_None1::
	.string "Rien$"

BravoTrainerBattleTower_Text_None2::
	.string "Rien$"

BravoTrainerBattleTower_Text_None3::
	.string "Rien$"

BravoTrainerBattleTower_Text_None4::
	.string "Rien$"

BravoTrainerBattleTower_Text_Response::
	.string "“{STR_VAR_1}”.$"

BravoTrainerBattleTower_Text_ResponseSatisfied::
	.string "“{STR_VAR_1}”.\n"
	.string "N’est-ce pas formidable ?\p"
	.string "Cela exprime parfaitement la joie\n"
	.string "de {STR_VAR_2}, je pense.\p"
	.string "Ce combat contre {STR_VAR_3}, vers\n"
	.string "la fin… “{STR_VAR_1}”,\l"
	.string "c’est vraiment ce que vous en diriez !$"

BravoTrainerBattleTower_Text_ResponseUnsatisfied::
	.string "“{STR_VAR_1}”.\n"
	.string "Voilà qui est judicieux, n’est-ce pas ?\p"
	.string "Et ce dernier combat contre\n"
	.string "{STR_VAR_3}… Je crois que la\l"
	.string "déclaration “{STR_VAR_1}” résume\l"
	.string "parfaitement la situation !\p"
	.string "Il me semble que la déception de\n"
	.string "{STR_VAR_2} ne fait pas de doute !$"

BravoTrainerBattleTower_Text_Outro::
	.string "Bravo, {STR_VAR_1}!\n"
	.string "Bravo, {STR_VAR_2}!\p"
	.string "J’espère que nous pourrons encore\n"
	.string "voir {STR_VAR_1} gravir les échelons\l"
	.string "de la gloire !\p"
	.string "Bien, le temps qui nous est accordé est\n"
	.string "désormais écoulé ! A vous les studios !$"

SlateportCity_PokemonFanClub_Text_InterviewRequestHasName:
	.string "Waouh !\p"
	.string "Apparemment, vous donnez beaucoup\n"
	.string "d’amour à votre {STR_VAR_1}.\p"
	.string "Ah, d’accord, il s’appelle {STR_VAR_2}.\p"
	.string "Je peux vous demander un service ?\p"
	.string "Je suis journaliste pour la télé et je\n"
	.string "réalise un sondage sur les Pokémon.\p"
	.string "Pourriez-vous répondre à quelques\n"
	.string "questions simples, pour moi ?$"

SlateportCity_PokemonFanClub_Text_HereGoesQuickAnswers:
	.string "Super ! Merci beaucoup !\p"
	.string "Très bien, allons-y. Il me faut des\n"
	.string "réponses concises, d’accord ?$"

SlateportCity_PokemonFanClub_Text_DescribeFeelingsFirstMetMon:
	.string "La première fois que vous avez vu\n"
	.string "{STR_VAR_1}, qu’avez-vous ressenti ?\p"
	.string "Comment décririez-vous les sentiments\n"
	.string "que vous avez éprouvés, à l’époque ?$"

SlateportCity_PokemonFanClub_Text_LikenMonToSomethingYouLike:
	.string "Ce {STR_VAR_1} est traité avec amour.\p"
	.string "Si vous le compariez à quelque chose\n"
	.string "que vous aimez, de quoi s’agirait-il ?$"

SlateportCity_PokemonFanClub_Text_WhatAttractedYouAboutMon:
	.string "Cette question est aussi valable pour\n"
	.string "votre {STR_VAR_1} adoré.\p"
	.string "Qu’est-ce que vous aimez\n"
	.string "chez {STR_VAR_1}?$"

SlateportCity_PokemonFanClub_Text_WhatDoPokemonMeanToYou:
	.string "Bien sûr, c’est logique.\p"
	.string "La prochaîne question est un peu\n"
	.string "plus compliquée.\p"
	.string "La voici :\p"
	.string "Pour vous, que signifie Pokémon ?$"

SlateportCity_PokemonFanClub_Text_ThatsAllForInterview:
	.string "Je vois !\p"
	.string "Humm…\p"
	.string "Très bien !\n"
	.string "Merci de votre coopération.\p"
	.string "Cette discussion avec vous a été\n"
	.string "amusante et enrichissante.\p"
	.string "Votre interview passera peut-être à\n"
	.string "la télé. Regardez-la régulièrement !\p"
	.string "Voilà, c’est tout.\n"
	.string "Au revoir !$"

SlateportCity_PokemonFanClub_Text_HereIfYouGetUrgeToTellMe:
	.string "Oh, très bien…\p"
	.string "Si vous changez d’avis et que vous\n"
	.string "voulez parler de Pokémon, je serai là !$"

SlateportCity_PokemonFanClub_Text_EnjoyDoingInterviews:
	.string "J’adore ce métier. On peut apprendre\n"
	.string "tellement de choses sur les Pokémon en\l"
	.string "faisant des interviews.$"

SlateportCity_PokemonFanClub_Text_InterviewRequest:
	.string "Salut ! Vous semblez très proche de\n"
	.string "votre {STR_VAR_1}.\p"
	.string "Vous savez quoi ?\n"
	.string "Je suis journaliste pour la télé.\p"
	.string "Je voyage pour interviewer les gens\n"
	.string "à propos des Pokémon.\p"
	.string "Mais j’y pense, vous voulez peut-être\n"
	.string "me parler de votre {STR_VAR_1}?$"

SlateportCity_PokemonFanClub_Text_TellMeAnythingAboutYourMon:
	.string "Super, merci !\p"
	.string "Bon, eh bien, dites-moi ce que vous\n"
	.string "aimez chez votre {STR_VAR_1}.$"

SlateportCity_PokemonFanClub_Text_ThatsAllForInterview2:
	.string "Oh…\n"
	.string "Voilà des remarques intéressantes.\p"
	.string "Vous êtes vraiment très intime avec\n"
	.string "{STR_VAR_1}, n’est-ce pas ?\p"
	.string "J’ai l’impression que vos déclarations\n"
	.string "feront un chouette sujet pour la télé.\p"
	.string "Je vous promets d’en faire une\n"
	.string "super émission.\l"
	.string "Regardez-nous régulièrement.\p"
	.string "Voilà, c’est tout.\n"
	.string "Au revoir !$"

gTVFanClubOpinionsText00::
	.string "C’est nous, le Fan Club Pokémon !\p"
	.string "Et nous sommes en direct !\p"
	.string "Dans cette émission, nous compilons\n"
	.string "vos opinions et nous les diffusons !\l"
	.string "Super concept d’émission, n’est-ce pas ?\p"
	.string "Aujourd’hui, nous vous présentons un\n"
	.string "reportage de notre journaliste,\l"
	.string "envoyé spécial au Fan Club Pokémon.\p"
	.string "Bien, qui est notre fan de Pokémon,\n"
	.string "aujourd’hui ?\p"
	.string "… … … … … … … …\p"
	.string "{STR_VAR_1}!\p"
	.string "Écoutons ce que {STR_VAR_1} souhaite nous\n"
	.string "raconter sur {STR_VAR_3} le {STR_VAR_2}.\p"
	.string "Puis, je répandrai ces belles paroles\n"
	.string "sur les ondes !\p"
	.string "You-hou !\p"
	.string "C’est parti !$"

gTVFanClubOpinionsText01::
	.string "Nous avons demandé à {STR_VAR_1}: “La\n"
	.string "première fois que vous avez vu votre\l"
	.string "{STR_VAR_2}, qu’avez-vous ressenti ?”\p"
	.string "“{STR_VAR_3}” !\p"
	.string "Hé ! Génial ! Quelles paroles magnifiques !\p"
	.string "Pas de doute, ça nous remet en mémoire\n"
	.string "de magnifiques souvenirs d’autrefois.$"

gTVFanClubOpinionsText02::
	.string "Nous avons demandé à {STR_VAR_1}: “Si vous\n"
	.string "deviez comparer votre {STR_VAR_2} à\l"
	.string "quelque chose, ce serait…”\p"
	.string "… … … … … … … …\p"
	.string "“{STR_VAR_3}” !\p"
	.string "Hé, voilà une idée originale !\p"
	.string "On peut sentir l’intensité des\n"
	.string "sentiments de ce Dresseur pour\l"
	.string "son {STR_VAR_2}.$"

gTVFanClubOpinionsText03::
	.string "Continuons…\n"
	.string "Qu’est-ce qui était si attirant\l"
	.string "chez {STR_VAR_2} pour {STR_VAR_1}?\p"
	.string "… … … … … … … …\p"
	.string "“{STR_VAR_3}” !\p"
	.string "Waouh ! Quelle déclaration fracassante !\p"
	.string "L’amour de ce Dresseur pour son\n"
	.string "{STR_VAR_2} ne fait aucun doute !$"

gTVFanClubOpinionsText04::
	.string "Hein ? Oh, nous avons encore du temps.\n"
	.string "Très bien !\p"
	.string "Voyons donc…\p"
	.string "Nous avons demandé à {STR_VAR_1}: “Pour\n"
	.string "vous, que signifie Pokémon ?”\p"
	.string "… … … … … …\p"
	.string "“{STR_VAR_3}” !\p"
	.string "Bravo !\p"
	.string "Ce sont de bien belles paroles !\p"
	.string "“{STR_VAR_3}” !\p"
	.string "Ça donne envie de le répéter encore et\n"
	.string "encore !\p"
	.string "Bien, après ces belles paroles, il est\n"
	.string "temps de se dire au revoir.\p"
	.string "Et répétons encore une fois ces belles\n"
	.string "paroles ! Tous ensemble…\p"
	.string "“{STR_VAR_3}” !$"

gTVFanClubText00::
    .string "C’est nous, le Fan Club Pokémon !\p"
	.string "Et nous sommes en direct !\p"
	.string "Aujourd’hui, nous allons commencer par\n"
	.string "le QUART D’HEURE DES SONDAGES.\p"
	.string "Parmi les histoires de Pokémon et de\n"
	.string "Dresseurs, quel récit va attirer\l"
	.string "notre attention aujourd’hui ?\p"
	.string "Voyons voir…\p"
	.string "Celui-ci !\p"
	.string "Nous allons commencer par cette lettre !\p"
	.string "Il s’agit d’une lettre de {STR_VAR_1} à\n"
	.string "propos de son {STR_VAR_2}.\p"
	.string "Voyons comment notre écrivain\n"
	.string "exprime son amour pour {STR_VAR_2}!\l"
	.string "Humm…$"

gTVFanClubText01::
	.string "Wouah !\n"
	.string "Quelle lettre incroyable !$"

gTVFanClubText02::
	.string "Elle m’a beaucoup plu. Je vais la relire !$"

gTVFanClubText03::
	.string "Quand une lettre est belle, on peut la\n"
	.string "relire à volonté !$"

gTVFanClubText04::
	.string "La partie “{STR_VAR_3}” met vraiment\n"
	.string "l’accent sur l’impact émotionnel !\p"
	.string "C’est une lettre magnifique d’une\n"
	.string "grande profondeur !$"

gTVFanClubText05::
	.string "Surtout la partie “{STR_VAR_3}” !\p"
	.string "Super utilisation de “{STR_VAR_3}” !$"

gTVFanClubText06::
	.string "D’ailleurs, ça n’est pas important, mais\n"
	.string "“{STR_VAR_3}” est super chouette.\p"
	.string "Ces derniers temps, j’utilise beaucoup\n"
	.string "“{STR_VAR_3}” dans les discussions.$"

gTVFanClubText07::
	.string "Si je devais noter cette lettre, je lui\n"
	.string "donnerais {STR_VAR_3} points.\p"
	.string "La prochaîne fois, j’espère que {STR_VAR_1}\n"
	.string "nous fera une lettre encore meilleure !\p"
	.string "Oh, le temps passe à une vitesse folle !\n"
	.string "Il est l’heure de se dire au revoir ! Bye !$"

SlateportCity_OceanicMuseum_1F_Text_InterviewRequest:
	.string "Oh ?\n"
	.string "Vous aimez peut-être les Pokémon ?\p"
	.string "J’effectue un reportage pour la chaîne\n"
	.string "de TV.\p"
	.string "Je recueille des histoires récentes de\n"
	.string "Pokémon et de Dresseurs.\p"
	.string "Si ça ne vous gêne pas, vous pourriez\n"
	.string "peut-être me parler de vous ?$"

SlateportCity_OceanicMuseum_1F_Text_InterviewRequestShort:
	.string "Je recueille des histoires récentes de\n"
	.string "Pokémon et de Dresseurs.\p"
	.string "Si ça ne vous gêne pas, vous pourriez\n"
	.string "peut-être me parler de vous ?$"

SlateportCity_OceanicMuseum_1F_Text_TellMeExperienceInvolvingPokemon:
	.string "Oh, vous voulez bien ?\n"
	.string "Merci beaucoup !\p"
	.string "Dans ce cas, pouvez-vous me raconter\n"
	.string "une histoire intéressante en rapport\l"
	.string "avec des Pokémon ?$"

SlateportCity_OceanicMuseum_1F_Text_LetMeKnowIfYouHaveStory:
	.string "Bon, tant pis…\p"
	.string "Si vous avez une histoire intéressante\n"
	.string "à raconter, revenez me voir.$"

SlateportCity_OceanicMuseum_1F_Text_ThatsAllForInterview:
	.string "Oh, quelle histoire passionnante !\p"
	.string "Je vais m’arranger pour faire passer\n"
	.string "votre histoire à la télévision.\p"
	.string "Elle sera bientôt sur les écrans.\n"
	.string "Vérifiez régulièrement.$"

SlateportCity_OceanicMuseum_1F_Text_BetterWriteUpStory:
	.string "Humm…\n"
	.string "J’ai une excellente histoire pour une\l"
	.string "émission de télé.\p"
	.string "Je ferais mieux d’aller l’écrire de suite !$"

gTVRecentHappeningsText00::
	.string "Bonjour, bienvenue à Histoires Vécues.\p"
	.string "La vie quotidienne des Dresseurs de\n"
	.string "Pokémon est digne des meilleurs contes.\p"
	.string "Nous allons vous présenter certains de\n"
	.string "ces contes de Pokémon.\p"
	.string "Aujourd’hui, nous allons vous raconter\n"
	.string "l’histoire du Dresseur {STR_VAR_1}.\p"
	.string "Qu’est-il arrivé à {STR_VAR_1} récemment ?\n"
	.string "Découvrons-le ensemble.\p"
	.string "C’est parti…$"

gTVRecentHappeningsText01::
	.string "Une histoire enrichissante,\n"
	.string "n’est-ce pas ?\p"
	.string "Cette histoire vous donne une idée\n"
	.string "des récentes aventures de {STR_VAR_1}.\p"
	.string "C’est comme si nous étions sur place !$"

gTVRecentHappeningsText02::
	.string "“{STR_VAR_3}”. Cela\n"
	.string "donne de la profondeur à l’histoire.$"

gTVRecentHappeningsText03::
	.string "“{STR_VAR_3}”.\n"
	.string "Cela met l’histoire en perspective.\l"
	.string "On en sait plus sur le contexte.$"

gTVRecentHappeningsText04::
	.string "“{STR_VAR_3}”. Cette\n"
	.string "partie de l’histoire est explicite.$"

gTVRecentHappeningsText05::
	.string "{STR_VAR_1} nous a raconté une\n"
	.string "merveilleuse histoire de Pokémon.\p"
	.string "L’histoire de {STR_VAR_1} est désormais\n"
	.string "gravée dans nos esprits pour toujours.\p"
	.string "C’est fini pour aujourd’hui.\n"
	.string "A la prochaîne fois.$"

gTVMassOutbreakText00::
	.string "Bonjour à tous !\n"
	.string "C’est l’heure du Bulletin Pokémon.\p"
	.string "Nous venons d’apprendre l’apparition\n"
	.string "d’un phénomène très rare.\p"
	.string "Des témoignages affirment l’arrivée\n"
	.string "massive de {STR_VAR_2} du côté de la\l"
	.string "{STR_VAR_1}.\p"
	.string "Les {STR_VAR_2}, comme vous le savez\n"
	.string "déjà, sont des Pokémon très rares et\l"
	.string "difficiles à trouver.\p"
	.string "Voici donc une chance unique de voir\n"
	.string "ce débarquement en masse de\l"
	.string "{STR_VAR_2} sauvages dans la nature.\p"
	.string "C’était le scoop du Bulletin Pokémon.$"

gTV3CheersForPokeblocksText00::
	.string "Animatrice : C’est l’heure de retrouver\n"
	.string "“Vive les {POKEBLOCK}s” !\p"
	.string "Aujourd’hui, nous allons tester le\n"
	.string "{POKEBLOCK} créé avec l’aide de {STR_VAR_1}.\p"
	.string "Sans attendre, je vais le faire goûter\n"
	.string "à mon Gloupti.\p"
	.string "… …\n"
	.string "… … … … … …$"

gTV3CheersForPokeblocksText01::
	.string "Gloupti : Gloup… Tiiii !\p"
	.string "Animatrice : Le {POKEBLOCK} est très\n"
	.string "{STR_VAR_1}!\p"
	.string "Gloupti dit que c’est {STR_VAR_2}!\p"
	.string "Merci beaucoup {STR_VAR_3}!$"

gTV3CheersForPokeblocksText02::
	.string "Le résultat de {STR_VAR_1} laisse\n"
	.string "à désirer.\p"
	.string "Si ce Dresseur pouvait mieux mixer,\n"
	.string "le {POKEBLOCK} aurait plus de goût.$"

gTV3CheersForPokeblocksText03::
	.string "Gloupti : Gloup… Tiiii !\p"
	.string "Animatrice : Le {POKEBLOCK} est trop\n"
	.string "{STR_VAR_1}!\p"
	.string "Gloupti dit que c’est {STR_VAR_2}!\p"
	.string "On dirait que les erreurs de {STR_VAR_3}\n"
	.string "se ressentent sur la qualité du mixage.$"

gTV3CheersForPokeblocksText04::
	.string "Les efforts de {STR_VAR_1} n’ont servi\n"
	.string "à rien.\p"
	.string "Espérons que {STR_VAR_2} fera mieux\n"
	.string "la prochaîne fois !$"

gTV3CheersForPokeblocksText05::
	.string "A la prochaîne !\n"
	.string "Et n’oubliez pas :\l"
	.string "“Vive les {POKEBLOCK}s” !$"

LilycoveCity_PokemonTrainerFanClub_Text_WhatsYourOpinionOfTrainer::
	.string "Salut !\p"
	.string "Je suis fan de {STR_VAR_1}.\n"
	.string "Je l’adore !\p"
	.string "Et toi, tu penses quoi de {STR_VAR_1}?$"

LilycoveCity_PokemonTrainerFanClub_Text_ThatsWhatYouThink::
	.string "Je vois, je vois. C’est donc ce que tu\n"
	.string "penses de ce Dresseur.$"

LilycoveCity_PokemonTrainerFanClub_Text_HaveYouForgottenTrainer::
	.string "Est-ce que tu as tout oublié sur\n"
	.string "{STR_VAR_1}?$"

LilycoveCity_PokemonTrainerFanClub_Text_WhatsYourOpinionOfTrainer2::
	.string "Je suis fan de {STR_VAR_1}.\n"
	.string "Je l’adore !\p"
	.string "Et toi, tu penses quoi de {STR_VAR_1}?$"

LilycoveCity_PokemonTrainerFanClub_Text_HowStrongRateTrainer::
	.string "Sur 100, tu mettrais combien à\n"
	.string "{STR_VAR_1}?$"

LilycoveCity_PokemonTrainerFanClub_Text_HaveYouForgottenTrainer2::
	.string "Est-ce que tu as tout oublié sur\n"
	.string "{STR_VAR_1}?$"

LilycoveCity_PokemonTrainerFanClub_Text_YouShouldMeetTrainer::
	.string "Oh, je vois !\p"
	.string "Mais tu devrais vraiment rencontrer\n"
	.string "{STR_VAR_1}.\p"
	.string "Tu deviendras vite fan, je n’ai aucun\n"
	.string "doute là-dessus.$"

LilycoveCity_PokemonTrainerFanClub_Text_ThankYouIllShareThisInfo::
	.string "Je vois, je vois.\p"
	.string "Merci !\n"
	.string "C’est bon à savoir.\p"
	.string "Je partagerai l’info avec d’autres\n"
	.string "fans de {STR_VAR_1} et en discuterai\l"
	.string "avec eux !$"

LilycoveCity_PokemonTrainerFanClub_HopeYouCatchTVSpecial::
	.string "Il va bientôt y avoir un reportage sur\n"
	.string "{STR_VAR_1} à la télé.\p"
	.string "J’espère que tu pourras le voir !$"

gTVTrainerFanClubSpecialText00::
	.string "Fan Club des Dresseurs\n"
	.string "Reportage Spécial sur {STR_VAR_1}!\p"
	.string "Ceci est une émission spéciale pour\n"
	.string "tous les fans de {STR_VAR_1}\l"
	.string "à travers Hoenn !\p"
	.string "Aujourd’hui, nous vous avons demandé\n"
	.string "ce que vous pensiez de {STR_VAR_1}.\p"
	.string "Nous avons posé la question à\n"
	.string "{STR_VAR_2} comme représentant des\l"
	.string "Dresseurs.\p"
	.string "Nous avons demandé : “En un mot,\n"
	.string "comment décririez-vous {STR_VAR_1}?”\p"
	.string "Sa réponse : “{STR_VAR_3}”.\p"
	.string "Bravo à {STR_VAR_2}!\n"
	.string "Quelle perspicacité !\p"
	.string "{STR_VAR_2} a également noté la force\n"
	.string "de {STR_VAR_1} de 0 à 100.$"

gTVTrainerFanClubSpecialText01::
	.string "Le score est de {STR_VAR_3} points !\n"
	.string "C’est un score vraiment très important !\p"
	.string "{STR_VAR_2} doit certainement avoir\n"
	.string "une très haute opinion de {STR_VAR_1}!$"

gTVTrainerFanClubSpecialText02::
	.string "Le score est de {STR_VAR_3} points !\n"
	.string "C’est un bon score !\p"
	.string "{STR_VAR_2} doit considérer\n"
	.string "{STR_VAR_1} comme un véritable\l"
	.string "adversaire !$"

gTVTrainerFanClubSpecialText03::
	.string "Le score est de {STR_VAR_3} points !\n"
	.string "C’est un score plutôt faible !\p"
	.string "{STR_VAR_2} doit juste considérer\n"
	.string "{STR_VAR_1} comme une simple relation.$"

gTVTrainerFanClubSpecialText04::
	.string "Le score est de {STR_VAR_3} point(s) !\n"
	.string "C’est un score ridicule !\p"
	.string "{STR_VAR_2} doit avoir une bien\n"
	.string "mauvaise impression de {STR_VAR_1}.$"

gTVTrainerFanClubSpecialText05::
	.string "Voilà les amis !\p"
	.string "Je crois que nous venons d’apprendre\n"
	.string "quelque chose sur {STR_VAR_1}.\p"
	.string "Pour finir, je vous laisse avec la\n"
	.string "parole du jour de {STR_VAR_2}.\p"
	.string "{STR_VAR_3} {STR_VAR_1}!$"

gTVNameRaterText00::
	.string "Et maintenant, c’est l’heure de…\n"
	.string "Voyance Pokémon.\p"
	.string "Je peux prédire l’avenir de votre\n"
	.string "Pokémon en fonction de son surnom.\p"
	.string "Je ne donne que des conseils, mais\n"
	.string "croyez-moi, ces conseils sont utiles.\p"
	.string "Aujourd’hui, je vais lire l’avenir dans\n"
	.string "le surnom {STR_VAR_3} du {STR_VAR_2}\l"
	.string "de {STR_VAR_1}.\p"
	.string "Humm…\p"
	.string "Hum…\n"
	.string "Ce surnom est…$"

gTVNameRaterText01::
	.string "Un surnom qui laisse deviner de\n"
	.string "nombreux talents, divers et variés.\p"
	.string "Je recommande à ce Dresseur de relever\n"
	.string "courageusement un max de défis.$"

gTVNameRaterText02::
	.string "Un surnom qui complète parfaitement\n"
	.string "{STR_VAR_1}, le nom du Dresseur.\p"
	.string "Cela suggère qu’ils forment une bonne\n"
	.string "équipe en parfaite harmonie.$"

gTVNameRaterText03::
	.string "Un surnom qui met en avant la\n"
	.string "personnalité unique du Pokémon !\p"
	.string "S’il est élevé correctement, ce Pokémon\n"
	.string "affinera son caractère exceptionnel !$"

gTVNameRaterText04::
	.string "Un surnom qui montre bien l’attention\n"
	.string "et la compassion de ce Pokémon.\p"
	.string "S’il est élevé correctement, ce Pokémon\n"
	.string "fera preuve d’une grande affection.$"

gTVNameRaterText05::
	.string "Un très joli surnom qui suggère un\n"
	.string "avenir prometteur.\p"
	.string "Je me demande ce que l’avenir réserve\n"
	.string "à ce Pokémon.$"

gTVNameRaterText06::
	.string "Un chouette surnom qui devrait\n"
	.string "garantir une bonne santé à ce Pokémon !\p"
	.string "Ce Pokémon aura une constitution\n"
	.string "robuste pendant très longtemps.$"

gTVNameRaterText07::
	.string "Un chouette surnom qui donnera\n"
	.string "beaucoup d’énergie à ce Pokémon !\p"
	.string "Tout porte à croire que ce Pokémon\n"
	.string "sera excellent pendant les combats.$"

gTVNameRaterText08::
	.string "Un surnom plaisant qui rend ce\n"
	.string "Pokémon très charmant !\p"
	.string "Aucun doute possible, ce Pokémon aura\n"
	.string "du succès pendant les Concours.$"

gTVNameRaterText09::
	.string "La racine du surnom {STR_VAR_1}\n"
	.string "s’appuie sur la lettre “{STR_VAR_3}”.\p"
	.string "Cette lettre est soutenue par la\n"
	.string "première lettre, “{STR_VAR_2}”, qui confère\l"
	.string "une forte présence au surnom.$"

gTVNameRaterText10::
	.string "Le surnom {STR_VAR_1} est très\n"
	.string "harmonieux et très agréable.\p"
	.string "La présence des lettres “{STR_VAR_2}” et\n"
	.string "“{STR_VAR_3}” est particulièrement bienvenue !$"

gTVNameRaterText11::
	.string "Le surnom {STR_VAR_1} révèle une\n"
	.string "magnificence et une fluidité certaines.\p"
	.string "Le passage de la lettre “{STR_VAR_2}” à la lettre\n"
	.string "“{STR_VAR_3}” est formidable.$"

gTVNameRaterText12::
	.string "Étudions d’autres exemples de surnoms,\n"
	.string "si vous le voulez bien !$"

gTVNameRaterText13::
	.string "Par exemple, prenons une partie du nom\n"
	.string "du Dresseur {STR_VAR_1}, ce qui\l"
	.string "pourrait donner un super surnom : {STR_VAR_2}{STR_VAR_3}.$"

gTVNameRaterText14::
	.string "{STR_VAR_2}{STR_VAR_3} pourrait aussi être une\n"
	.string "bonne idée de surnom.$"

gTVNameRaterText15::
	.string "Le nom de l’espèce du Pokémon,\n"
	.string "{STR_VAR_2}, pourrait servir de point de\l"
	.string "départ au surnom {STR_VAR_1}{STR_VAR_3}.$"

gTVNameRaterText16::
	.string "{STR_VAR_1}{STR_VAR_3} serait également un\n"
	.string "surnom efficace.$"

gTVNameRaterText17::
	.string "En revanche, il faut éviter d’utiliser le\n"
	.string "nom d’espèce d’un autre Pokémon.\p"
	.string "Par exemple, il ne faut pas prendre le\n"
	.string "nom {STR_VAR_2} pour créer le surnom\l"
	.string "{STR_VAR_1}{STR_VAR_3}. C’est inacceptable.$"

gTVNameRaterText18::
	.string "Mais il faut bien admettre que\n"
	.string "{STR_VAR_1} est un bon surnom.\p"
	.string "Espérons que ce Dresseur continuera\n"
	.string "à traiter {STR_VAR_1} avec amour.\p"
	.string "Voilà ! C’est fini pour aujourd’hui.\n"
	.string "Ne ratez pas notre prochaîne émission.$"

gTVPokemonAnglerText00::
	.string "Pêche au {STR_VAR_2}\p"
	.string "Présentateur : Salut ! Aujourd’hui, nous\n"
	.string "apprenons à pêcher le {STR_VAR_2}.\p"
	.string "Vous, le Pro de la Pêche, quel\n"
	.string "conseil donneriez-vous pour la pêche\l"
	.string "au {STR_VAR_2}?\p"
	.string "Pro de la Pêche : Hein ? La pêche au\n"
	.string "{STR_VAR_2}? Eh bien, tout d’abord,\l"
	.string "soyez patients. C’est la base de tout.\p"
	.string "Vous voyez {STR_VAR_1}, là-bas ?\n"
	.string "Ce Dresseur est un bon exemple.\p"
	.string "Il a déjà laissé filer {STR_VAR_3}\n"
	.string "Pokémon.\p"
	.string "Et pourtant, {STR_VAR_1} attend, sans\n"
	.string "abandonner. C’est ainsi qu’on attrape\l"
	.string "des {STR_VAR_2}.\p"
	.string "Présentateur : Je vois…\p"
	.string "Oh ! {STR_VAR_1} a finalement attrapé\n"
	.string "un {STR_VAR_2} récalcitrant !\p"
	.string "Le Dresseur est sur le point\n"
	.string "de pleurer de joie !\p"
	.string "Quand je vois ce genre de regard, ça\n"
	.string "me donne envie de pêcher !\p"
	.string "Téléspectateurs, pourquoi ne pas\n"
	.string "vous mettre à la pêche au {STR_VAR_2}?\p"
	.string "En attendant notre prochaîne émission,\n"
	.string "bonne pêche à tous !$"

gTVPokemonAnglerText01::
	.string "Pêche AU {STR_VAR_2}\p"
	.string "Présentateur : Salut ! Aujourd’hui, nous\n"
	.string "apprenons à pêcher le {STR_VAR_2}.\p"
	.string "Vous, le Pro de la Pêche, quel\n"
	.string "conseil donneriez-vous pour la pêche\l"
	.string "au {STR_VAR_2}?\p"
	.string "Pro de la Pêche : Hein ? La pêche au\n"
	.string "{STR_VAR_2}? Eh bien, tout d’abord,\l"
	.string "tenez votre Canne énergiquement !\p"
	.string "Vous voyez {STR_VAR_1}, là-bas ?\n"
	.string "Vous voyez comment il tient sa Canne ?\p"
	.string "Ce Dresseur vient d’en attraper\n"
	.string "{STR_VAR_3} de suite.\p"
	.string "Présentateur : C’est incroyable !\n"
	.string "C’est une véritable razzia…\p"
	.string "Quand je vois une telle technique, ça\n"
	.string "me donne envie de pêcher !\p"
	.string "Téléspectateurs, pourquoi ne pas\n"
	.string "vous mettre à la pêche au {STR_VAR_2}?\p"
	.string "En attendant notre prochaîne émission,\n"
	.string "bonne pêche à tous !$"

gTVPokemonTodayFailedText00::
	.string "Bonjour !\p"
	.string "C’est l’heure de Pokémon d’un Jour !\p"
	.string "Frangine : Salut à tous ! Est-ce que\n"
	.string "tout le monde a la pêche aujourd’hui ?\p"
	.string "Dans cette émission, nous allons voir\n"
	.string "{STR_VAR_2}, le Pokémon de {STR_VAR_1}!\p"
	.string "Frangin : Absolument ! C’est notre\n"
	.string "programme de la journée !$"

gTVPokemonTodayFailedText01::
	.string "Oh !\n"
	.string "Puisqu’on parle de {STR_VAR_1}…\p"
	.string "Frangine, j’ai vu ce Dresseur de\n"
	.string "mes propres yeux !\p"
	.string "Frangine : Oh, vraiment ?\p"
	.string "Frangin : Oui, j’étais en voyage à\n"
	.string "{STR_VAR_2}.\p"
	.string "Et je suis tombé sur {STR_VAR_1}, qui\n"
	.string "essayait d’attraper le Pokémon\l"
	.string "{STR_VAR_3}, mais malheureusement…$"

gTVPokemonTodayFailedText02::
	.string "Le Pokémon a réussi à s’échapper !\p"
	.string "Finalement, le Dresseur a gaspillé\n"
	.string "{STR_VAR_2} POKé Balls !\p"
	.string "Il fallait voir la déception dans les\n"
	.string "yeux de {STR_VAR_1} au moment où\l"
	.string "le Pokémon s’est enfui !$"

gTVPokemonTodayFailedText03::
	.string "{STR_VAR_1} a fait une gaffe et le Pokémon\n"
	.string "s’est retrouvé K.O. !\p"
	.string "Finalement, le Dresseur a gaspillé\n"
	.string "{STR_VAR_2} POKé Balls !\p"
	.string "Il fallait voir le désarroi dans les\n"
	.string "yeux de {STR_VAR_1} au moment où\l"
	.string "le Pokémon a été mis K.O. !$"

gTVPokemonTodayFailedText04::
	.string "Frangine : Hé !\n"
	.string "Ce n’est pas très sympa !\p"
	.string "Il ne faut pas se moquer du malheur\n"
	.string "des autres !\p"
	.string "Pauvre {STR_VAR_1}.\n"
	.string "Quel dommage !\p"
	.string "Frangin : C’est vrai !\n"
	.string "Désolé de m’être moqué.$"

gTVPokemonTodayFailedText05::
	.string "Frangine : Hi hi hi…\p"
	.string "Frangin : Hé !\n"
	.string "Tu viens de rire !\p"
	.string "Frangine : Hein ?!\p"
	.string "Je n’ai pas rigolé !\n"
	.string "Honnêtement !\p"
	.string "Pauvre {STR_VAR_1}.\n"
	.string "Quel dommage !\p"
	.string "Frangin : …$"

gTVPokemonTodayFailedText06::
	.string "Frangine : Finies les bêtises !\n"
	.string "Voyons donc le Pokémon du jour…\p"
	.string "Quoi ?\n"
	.string "Notre temps est déjà écoulé ?\p"
	.string "Oh non !\n"
	.string "Nous n’avons eu le temps de\l"
	.string "présenter aucun Pokémon !\p"
	.string "Frangin : A la prochaîne !\p"
	.string "Frangine : Hé, ne terminez pas\n"
	.string "l’émission sans moi !$"

gTVPokemonTodaySuccessfulText00::
	.string "Bonjour !\p"
	.string "C’est l’heure de Pokémon d'un Jour !\p"
	.string "Frangine : Salut à tous ! Est-ce que\n"
	.string "tout le monde a la pêche aujourd’hui ?\p"
	.string "Dans cette émission, nous allons voir\n"
	.string "{STR_VAR_2}, le Pokémon de {STR_VAR_1}!\p"
	.string "Frangin : Absolument ! C’est notre\n"
	.string "programme de la journée !$"

gTVPokemonTodaySuccessfulText01::
	.string "Frangine : {STR_VAR_1} a surnommé son\n"
	.string "{STR_VAR_2} {STR_VAR_3}!\p"
	.string "Apparemment, {STR_VAR_3} est\n"
	.string "particulièrement choyé !$"

gTVPokemonTodaySuccessfulText02::
	.string "Frangin : Ce Dresseur a dû lancer\n"
	.string "{STR_VAR_3} Ball(S) pour l’attraper !\p"
	.string "Hé, tu te rends compte ? Une seule\n"
	.string "{STR_VAR_2} a suffi à l’attraper !$"

gTVPokemonTodaySuccessfulText03::
	.string "Frangine : S’il était si facile à\n"
	.string "attraper, c’est que le destin a voulu\l"
	.string "réunir {STR_VAR_1} et {STR_VAR_2}!$"

gTVPokemonTodaySuccessfulText04::
	.string "Frangine : Ouah ! C’est génial !\p"
	.string "Mais comme on dit, un Pokémon\n"
	.string "difficile à attraper est assuré\l"
	.string "d’obtenir l’amour de son Dresseur !$"

gTVPokemonTodaySuccessfulText05::
	.string "Frangine : Le {STR_VAR_2} de {STR_VAR_1}\n"
	.string "est un Pokémon mémorable car il a\l"
	.string "fallu une Master Ball pour l’attraper !\p"
	.string "Frangin : Ouah ! C’est incroyable !\p"
	.string "Frangine : {STR_VAR_1} devait vraiment\n"
	.string "vouloir ce {STR_VAR_2}, pas de doute !$"

gTVPokemonTodaySuccessfulText06::
	.string "Frangin : Puis, ce Dresseur a surnommé\n"
	.string "son {STR_VAR_2} {STR_VAR_3}…\p"
	.string "Ça donne une bonne idée de l’état\n"
	.string "d’esprit de {STR_VAR_1}.\p"
	.string "Frangine : Je suis d’accord !$"

gTVPokemonTodaySuccessfulText07::
	.string "Moi en revanche, j’aurais donné ce\n"
	.string "surnom à un {STR_VAR_3}!\p"
	.string "Frangin : Hé ! Mais ça pourrait être\n"
	.string "le début d’une nouvelle mode !$"

gTVPokemonTodaySuccessfulText08::
	.string "{STR_VAR_2} le {STR_VAR_1}!\n"
	.string "Ça sonne bien, non ?\p"
	.string "Les lettres, la prononciation, tout\n"
	.string "colle parfaitement au Pokémon\l"
	.string "{STR_VAR_1}!\p"
	.string "Frangin : Oui, c’est vrai !$"

gTVPokemonTodaySuccessfulText09::
	.string "A ma connaissance, aucun Dresseur\n"
	.string "n’a jamais donné le surnom {STR_VAR_2}\l"
	.string "à un {STR_VAR_1}!\p"
	.string "Frangin : Cela prouve le bon goût de\n"
	.string "ce Dresseur en matière de surnoms !$"

gTVPokemonTodaySuccessfulText10::
	.string "La prochaîne fois que j’attrape un\n"
	.string "Pokémon, je l’appelle {STR_VAR_2}.\p"
	.string "Frangin : Vraiment ? Moi aussi !\n"
	.string "Je l’appellerai {STR_VAR_2}!$"

gTVPokemonTodaySuccessfulText11::
	.string "Frangine : Oh, non !\n"
	.string "L’heure tourne !\p"
	.string "Bon, les amis, c’est fini pour\n"
	.string "aujourd’hui. Au revoir et à bientôt !\p"
	.string "Frangin : N’oubliez pas, votre\n"
	.string "Pokémon pourrait être le sujet\l"
	.string "de la prochaîne émission !$"

SmartShopper_Text_Intro::
	.string "Bonjour à tous !\p"
	.string "C’est l’heure du Pokéachat.\p"
	.string "Journaliste : Comment vont nos\n"
	.string "téléspectateurs ?\p"
	.string "Aujourd’hui, nous visitons une boutique\n"
	.string "à {STR_VAR_2}.\p"
	.string "Voyons donc ce que nos vendeuses\n"
	.string "ont à nous proposer !$"

SmartShopper_Text_ClerkNormal::
	.string "Interrogeons cette vendeuse pour\n"
	.string "savoir quelle est la tendance.\p"
	.string "Bonjour, comment vont les affaires ?\p"
	.string "Vendeuse : Oh, très très bien.\p"
	.string "En ce moment, l’objet {STR_VAR_2} se\n"
	.string "vend beaucoup.\p"
	.string "Par exemple, l’autre jour, un Dresseur\n"
	.string "appelé {STR_VAR_1} en a acheté {STR_VAR_3}.$"

SmartShopper_Text_RandomComment1::
	.string "Journaliste : Le Dresseur en a acheté\n"
	.string "{STR_VAR_3}? Impressionnant !\p"
	.string "A mon avis, {STR_VAR_1} se préparait à\n"
	.string "effectuer un long voyage dans des\l"
	.string "contrées lointaines.\p"
	.string "Il faut toujours avoir ce type\n"
	.string "d’objet quand on voyage !$"

SmartShopper_Text_RandomComment2::
	.string "Journaliste : Puisqu’on parle de l’objet\n"
	.string "{STR_VAR_2}, j’en ai justement acheté\l"
	.string "{STR_VAR_3} récemment.\p"
	.string "Après tout, c’est un super objet !$"

SmartShopper_Text_RandomComment3::
	.string "Journaliste : Combien de fois l’objet\n"
	.string "{STR_VAR_2}?! {STR_VAR_3}?!\p"
	.string "Je n’aurais jamais cru que quelqu’un\n"
	.string "en achèterait autant.\p"
	.string "Bon sang, je ne peux pas me permettre\n"
	.string "d’en acheter autant que ça, moi…$"

SmartShopper_Text_RandomComment4::
	.string "Journaliste : Une fois, j’ai acheté\n"
	.string "un lot complet de l’objet {STR_VAR_2}.\p"
	.string "Mais finalement, il y en avait trop.\n"
	.string "J’ai fini par le regretter…\p"
	.string "Depuis, je n’achète que ce qui est\n"
	.string "strictement nécessaire…\p"
	.string "Heu…\p"
	.string "Évidemment, ça n’intéresse personne !$"

SmartShopper_Text_SecondItem::
	.string "Vendeuse : {STR_VAR_1} a aussi acheté\n"
	.string "l’objet {STR_VAR_2}. Il en a pris {STR_VAR_3}.\p"
	.string "Journaliste : Oh, bonne idée.\n"
	.string "C’est un objet très utile aussi.$"

SmartShopper_Text_ThirdItem::
	.string "Vendeuse : Et le Dresseur a aussi\n"
	.string "acheté {STR_VAR_3} exemplaires de\l"
	.string "l’objet {STR_VAR_2}.$"

SmartShopper_Text_DuringSale::
	.string "Vendeuse : En plus, c’était pendant les\n"
	.string "soldes. Malin, non ?$"

SmartShopper_Text_OutroNormal::
	.string "Journaliste : Hum… {STR_VAR_1} semble\n"
	.string "aimer faire des économies !\p"
	.string "Le total des achats de {STR_VAR_1}\n"
	.string "s’est finalement élevé à…\p"
	.string "{STR_VAR_2}¥ ?!\n"
	.string "Une sacrée somme !\p"
	.string "Oh ! Mince ! Notre temps est écoulé !\n"
	.string "Rendez-vous à la prochaîne émission !$"

SmartShopper_Text_IsVIP::
	.string "Vendeuse : {STR_VAR_1} fait partie de ma\n"
	.string "clientèle privilégiée, c’est sûr.$"

SmartShopper_Text_ClerkMax::
	.string "Interrogeons cette vendeuse pour\n"
	.string "savoir quelle est la tendance.\p"
	.string "Bonjour, comment vont les affaires ?\p"
	.string "Vendeuse : Oh, les affaires marchent\n"
	.string "très fort. Nous avons du mal à suivre.\p"
	.string "Récemment, un Dresseur du nom\n"
	.string "de {STR_VAR_1} a acheté un lot de l’objet\l"
	.string "{STR_VAR_2}.\p"
	.string "Le Dresseur a pratiquement épuisé\n"
	.string "notre stock pour cet objet.\p"
	.string "Je n’aurais jamais espéré qu’une seule\n"
	.string "personne m’en achète autant.\l"
	.string "Je n’avais jamais vu ça !\p"
	.string "Journaliste : Combien en avez-vous\n"
	.string "vendu, finalement ? 100, 200 ?\p"
	.string "Vendeuse : Oh, non, bien plus que ça !\p"
	.string "Journaliste : Bon sang, {STR_VAR_1} aime\n"
	.string "vraiment faire du shopping !\p"
	.string "Vendeuse : {STR_VAR_1} fait partie de ma\n"
	.string "clientèle privilégiée, c’est sûr.$"

SmartShopper_Text_OutroMax::
	.string "Journaliste : Hum…\n"
	.string "C’est vraiment étonnant.\p"
	.string "Pourquoi un Dresseur a-t-il\n"
	.string "besoin d’en acheter autant ?\p"
	.string "… …\p"
	.string "Le mystère demeure, mais nous\n"
	.string "n’avons malheureusement plus de temps.\p"
	.string "Rendez-vous à la prochaîne émission !\p"
	.string "Le mystère de {STR_VAR_1} reste entier…$"

gTVWorldOfMastersText00::
	.string "Culture Pokémon\p"
	.string "Bonjour, chers téléspectateurs.\p"
	.string "Vous avez peut-être déjà entendu\n"
	.string "parler d’un Dresseur appelé {STR_VAR_1}.\p"
	.string "{STR_VAR_1} est célèbre dans l’art\n"
	.string "d’attraper des Pokémon.\p"
	.string "La quête de Pokémon de {STR_VAR_1}\n"
	.string "dépend essentiellement de ses longues\l"
	.string "recherches effectuées à pied.\p"
	.string "Lors d’un jour mémorable, ce Dresseur\n"
	.string "a effectué {STR_VAR_2} pas.\p"
	.string "Le nombre total de Pokémon attrapés\n"
	.string "ce jour-là fut de {STR_VAR_3}!$"

gTVWorldOfMastersText01::
	.string "Cet exploit remarquable n’a été\n"
	.string "possible que grâce à la formidable\l"
	.string "entente entre le Dresseur et son\l"
	.string "{STR_VAR_1}.$"

gTVWorldOfMastersText02::
	.string "Le Dresseur a attrapé son dernier\n"
	.string "{STR_VAR_3} près de {STR_VAR_2}.\p"
	.string "Ce Pokémon a la particularité d’être\n"
	.string "un véritable détenteur de records.\p"
	.string "Nous espérons que ça donnera envie aux\n"
	.string "Dresseurs expérimentés de faire mieux.\p"
	.string "C’est tout pour aujourd’hui.\n"
	.string "A la prochaîne.$"

gTVTodaysRivalTrainerText00::
	.string "Le Rival du Jour !\p"
	.string "Bonjour, chers Dresseurs de Pokémon !\n"
	.string "Comment allez-vous, aujourd’hui ?\p"
	.string "Comme chaque jour, nous allons\n"
	.string "parler d’un Dresseur rival !$"

gTVTodaysRivalTrainerText07::
	.string "Le rival du jour est {STR_VAR_1}.\n"
	.string "Où est notre rival ? {STR_VAR_3}!\p"
	.string "{STR_VAR_1} a enregistré {STR_VAR_2}\n"
	.string "Pokémon dans son Pokédex.$"

gTVTodaysRivalTrainerText08::
	.string "Le rival du jour est {STR_VAR_1}.\n"
	.string "Notre rival est dans une Base Secrète !\p"
	.string "{STR_VAR_1} a enregistré {STR_VAR_2}\n"
	.string "Pokémon dans son Pokédex.$"

gTVTodaysRivalTrainerText09::
	.string "Le rival du jour est {STR_VAR_1}.\p"
	.string "{STR_VAR_1} a enregistré {STR_VAR_2}\n"
	.string "Pokémon dans son Pokédex.$"

gTVTodaysRivalTrainerText10::
	.string "Le rival du jour est {STR_VAR_1}.\n"
	.string "Notre rival se trouve sur le ferry.\p"
	.string "{STR_VAR_1} a enregistré {STR_VAR_2}\n"
	.string "Pokémon dans son Pokédex.$"

	.string "$"

gTVTodaysRivalTrainerText01::
	.string "Combien de Badges a notre rival ?\n"
	.string "Eh bien, il en a {STR_VAR_1}!$"

gTVTodaysRivalTrainerText02::
	.string "Mais notre rival n’a aucun Badge !$"

gTVTodaysRivalTrainerText03::
	.string "Notre rival n’a aucun symbole de la\n"
	.string "Zone de Combat.$"

gTVTodaysRivalTrainerText04::
	.string "Voyons combien de symboles de la\n"
	.string "Zone de Combat notre rival a-t-il.\p"
	.string "Symboles or : {STR_VAR_1}!\n"
	.string "Symboles argent : {STR_VAR_2}!$"

gTVTodaysRivalTrainerText05::
	.string "Notre rival a obtenu {STR_VAR_1} Point(s)\n"
	.string "DE Combat à la Zone de Combat.$"

gTVTodaysRivalTrainerText06::
	.string "Alors ? Feriez-vous le poids face\n"
	.string "à {STR_VAR_1}?\p"
	.string "L’aventure continue !\p"
	.string "Très chers Dresseurs !\p"
	.string "Il faut toujours aller de l’avant et\n"
	.string "surtout aller au devant de ses rivaux !$"

TrendWatcher_Text_Intro::
	.string "Chaîne “IN” DE Myokara !\p"
	.string "Animateur : Quoi d’neuf chez vous ?\n"
	.string "Nous vous tenons au courant des\l"
	.string "dernières modes à Myokara.\p"
	.string "Avec nous aujourd’hui, un vieux loup de\n"
	.string "mer. Il en sait un paquet sur Myokara !\p"
	.string "Vieil homme : Je suis content\n"
	.string "d’être ici.\p"
	.string "Animateur : Allons, pas de blabla,\n"
	.string "pas de chichi entre nous ! Droit au but !\p"
	.string "Qu’est-ce qui est à la mode à\n"
	.string "Myokara, en ce moment ?\p"
	.string "Vieil homme : {STR_VAR_1}\n"
	.string "{STR_VAR_2}.\p"
	.string "Animateur : {STR_VAR_1}\n"
	.string "{STR_VAR_2}?\p"
	.string "Vieil homme : Non.\p"
	.string "{STR_VAR_1} {STR_VAR_2} n’a jamais\n"
	.string "été très à la mode.\p"
	.string "Je peux en parler, si vous le\n"
	.string "souhaitez.\p"
	.string "Animateur : Heu… Non merci !\n"
	.string "On s’intéresse à ce qui est à la mode…$"

TrendWatcher_Text_MaleTaughtMePhrase::
	.string "Vieil homme : {STR_VAR_3} de\n"
	.string "Bourg-en-Vol m’a dit que {STR_VAR_1}\l"
	.string "{STR_VAR_2} était à la mode…$"

TrendWatcher_Text_FemaleTaughtMePhrase::
	.string "Vieil homme : {STR_VAR_3} de\n"
	.string "Bourg-en-Vol m’a dit que {STR_VAR_1}\l"
	.string "{STR_VAR_2} était à la mode…$"

TrendWatcher_Text_PhraseWasHopeless::
	.string "Mais ça n’a pas marché.\p"
	.string "Festival {STR_VAR_1} {STR_VAR_2}!\p"
	.string "Concours {STR_VAR_1} {STR_VAR_2}!\p"
	.string "J’ai essayé d’en parler autour\n"
	.string "de moi, mais…\p"
	.string "Peut-être que c’est {STR_VAR_1} qui\n"
	.string "n’a pas plu…\p"
	.string "Animateur : C’est bien joli, tout ça…\n"
	.string "Mais qu’est-ce qui est à la mode, alors ?$"

TrendWatcher_Text_MaleTellMeBigger::
	.string "Vieil homme : {STR_VAR_3}!\n"
	.string "Y a-t-il quelque chose au-dessus de\l"
	.string "{STR_VAR_1} {STR_VAR_2}?$"

TrendWatcher_Text_FemaleTellMeBigger::
	.string "Vieil homme : {STR_VAR_3}!\n"
	.string "Y a-t-il quelque chose au-dessus de\l"
	.string "{STR_VAR_1} {STR_VAR_2}?$"

TrendWatcher_Text_Outro::
	.string "Animateur : Hum… Heu, c’était l’info\n"
	.string "du jour !\p"
	.string "{STR_VAR_1} {STR_VAR_2}… Eh bien…\n"
	.string "Ce n’est pas à la mode à Myokara !\p"
	.string "C’est fini pour aujourd’hui. A plus !\p"
	.string "Vieil homme : {STR_VAR_1}\n"
	.string "{STR_VAR_2}!$"

gTVHoennTreasureInvestigatorsText00::
	.string "Chasse au Trésor à Hoenn !\p"
	.string "Salut, vous… De nouveaux objets\n"
	.string "secrets ont-il été trouvés ?\p"
	.string "Nous sommes avides de témoignages\n"
	.string "sur les trésors qui nous entourent !\p"
	.string "Nous avons reçu une lettre. Son sujet\n"
	.string "est “Découverte {STR_VAR_1}” !$"

gTVHoennTreasureInvestigatorsText01::
	.string "Oh ! Je ferais bien de lire cette lettre\n"
	.string "jusqu’au bout !\p"
	.string "“Chers Chasseurs,\n"
	.string "j’espère que vous vous portez bien.\p"
	.string "Récemment, j’ai vu {STR_VAR_2} dans les\n"
	.string "environs de {STR_VAR_3}.\p"
	.string "Ce Dresseur a trouvé l’objet\n"
	.string "{STR_VAR_1}. Comme je l’envie !”\p"
	.string "Eh bien, nous nous réjouissons\n"
	.string "pour {STR_VAR_2}!\p"
	.string "Chers téléspectateurs, à vos\n"
	.string "Cherch’Objets !\p"
	.string "Et pensez à nous si vous tombez sur\n"
	.string "la perle rare !$"

gTVHoennTreasureInvestigatorsText02::
	.string "Oh ! Je ferais bien de lire cette lettre\n"
	.string "jusqu’au bout !\p"
	.string "“Chers Chasseurs,\n"
	.string "j’espère que vous vous portez bien.\p"
	.string "Récemment, j’ai vu {STR_VAR_2} sur un\n"
	.string "ferry.\p"
	.string "Ce Dresseur a trouvé l’objet\n"
	.string "{STR_VAR_1}. Comme je l’envie !”\p"
	.string "Eh bien, nous nous réjouissons\n"
	.string "pour {STR_VAR_2}!\p"
	.string "Chers téléspectateurs, à vos\n"
	.string "Cherch’Objets !\p"
	.string "Et pensez à nous si vous tombez sur\n"
	.string "la perle rare !$"

gTVFindThatGamerText00::
	.string "Le Joueur du Jour !\p"
	.string "Bien le bonjour, amis joueurs !\n"
	.string "Tout se passe bien avec la\l"
	.string "{STR_VAR_2}?\p"
	.string "Comme d’habitude, nous vous présentons\n"
	.string "un Dresseur qui est venu tenter sa\l"
	.string "chance au Casino !\p"
	.string "Notre joueur du jour est…\n"
	.string "{STR_VAR_1}!$"

gTVFindThatGamerText01::
	.string "{STR_VAR_1} a gagné {STR_VAR_3} Jetons à\n"
	.string "la {STR_VAR_2}.\p"
	.string "“{STR_VAR_1} est là, rassemblez tous\n"
	.string "les Jetons, on en aura besoin !”\p"
	.string "C’est ce que les employés du Casino\n"
	.string "disent quand {STR_VAR_1} arrive !\p"
	.string "Si vous rencontrez {STR_VAR_1} au\n"
	.string "Casino, regardez comme ce Dresseur\l"
	.string "s’y prend à la {STR_VAR_2}.\p"
	.string "Nous étions en direct du Casino.\n"
	.string "La tension est à son comble, ici !\p"
	.string "Ce sera tout pour aujourd’hui !$"

gTVFindThatGamerText02::
	.string "{STR_VAR_1} a perdu {STR_VAR_3} Jetons à\n"
	.string "la {STR_VAR_2}.\p"
	.string "“Quand {STR_VAR_1} est là, notre vente\n"
	.string "de Jetons augmente.”\p"
	.string "C’est ce que les employés du Casino\n"
	.string "disent sur {STR_VAR_1}!$"

gTVFindThatGamerText03::
	.string "Si vous rencontrez {STR_VAR_1} au\n"
	.string "Casino devant une {STR_VAR_2},\l"
	.string "ne l’imitez pas !\p"
	.string "Nous étions en direct du Casino.\n"
	.string "La tension est à son comble, ici !\p"
	.string "Ce sera tout pour aujourd’hui !$"

gTVBreakingNewsText00::
	.string "Chaîne des Scoops !$"

gTVBreakingNewsText01::
	.string "Un {STR_VAR_2} rare attrapé par\n"
	.string "{STR_VAR_1}!\p"
	.string "Nous sommes en direct à proximité\n"
	.string "de {STR_VAR_3}!\p"
	.string "{STR_VAR_1} a réussi à capturer un\n"
	.string "{STR_VAR_2} rare ici même !$"

gTVBreakingNewsText02::
	.string "Quand {STR_VAR_1} a rencontré le\n"
	.string "{STR_VAR_2} rare, le Pokémon\l"
	.string "{STR_VAR_3} a été envoyé au combat.$"

gTVBreakingNewsText03::
	.string "Le Dresseur a naturellement eu recours\n"
	.string "aux POKé Balls. Il en a lancé {STR_VAR_1}.\p"
	.string "C’est avec une {STR_VAR_2} que le\n"
	.string "Pokémon rare a été attrapé.$"

gTVBreakingNewsText04::
	.string "Les cris de triomphe de {STR_VAR_1}\n"
	.string "ont résonné sur {STR_VAR_2}.\p"
	.string "Je dois dire que la prouesse de\n"
	.string "{STR_VAR_1} fait envie.\p"
	.string "Voilà, je vous dis à très bientôt !$"

gTVBreakingNewsText05::
	.string "{STR_VAR_1} a failli attraper un\n"
	.string "{STR_VAR_2} rare !\p"
	.string "Nous sommes en direct à proximité\n"
	.string "de {STR_VAR_3}!\p"
	.string "C’est ici que {STR_VAR_1} a failli\n"
	.string "attraper un {STR_VAR_2} rare !$"

gTVBreakingNewsText06::
	.string "Quand {STR_VAR_1} a rencontré le\n"
	.string "{STR_VAR_2} rare, le Pokémon\l"
	.string "{STR_VAR_3} a été envoyé au combat.$"

gTVBreakingNewsText07::
	.string "Le Dresseur a fait utiliser\n"
	.string "{STR_VAR_1} par {STR_VAR_2}.\p"
	.string "Le Pokémon rare s’est\n"
	.string "malheureusement évanoui…$"

gTVBreakingNewsText12::
	.string "{STR_VAR_1} a paniqué à la vue\n"
	.string "du {STR_VAR_2} rare.\p"
	.string "Le Dresseur a ordonné au\n"
	.string "{STR_VAR_3} d’attaquer.\p"
	.string "Le Pokémon rare s’est\n"
	.string "malheureusement évanoui…$"

gTVBreakingNewsText08::
	.string "Les cris de frustration de {STR_VAR_1}\n"
	.string "ont résonné sur {STR_VAR_2}…$"

gTVBreakingNewsText09::
	.string "{STR_VAR_1} était à court de\n"
	.string "POKé Balls.\p"
	.string "Ce Dresseur a dû arrêter le\n"
	.string "combat contre le {STR_VAR_2} rare.\p"
	.string "Les cris de frustration de {STR_VAR_1}\n"
	.string "ont résonné sur {STR_VAR_3}…$"

gTVBreakingNewsText10::
	.string "{STR_VAR_2} a fui sans prévenir.\p"
	.string "Les cris de frustration de {STR_VAR_1}\n"
	.string "ont résonné sur {STR_VAR_3}…$"

gTVBreakingNewsText11::
	.string "Je dois dire que c’est triste pour\n"
	.string "{STR_VAR_1}. J’ai envie de hurler aussi !\p"
	.string "Voilà, je vous dis à très bientôt !$"

gTVSecretBaseVisitText00::
	.string "Salut les amis !\n"
	.string "C’est le moment d’effectuer une petite\l"
	.string "Visite de Base Secrète.\p"
	.string "Aujourd’hui, nous allons découvrir la\n"
	.string "Base Secrète de {STR_VAR_1}.\p"
	.string "A quoi ressemble la Base Secrète\n"
	.string "de {STR_VAR_1}?\p"
	.string "Nous allons voir ça tout de suite !\n"
	.string "… … … … … …$"

gTVSecretBaseVisitText01::
	.string "Oh !\n"
	.string "Merveilleux !\p"
	.string "{STR_VAR_2}…\n"
	.string "Ceci est pour le moins surprenant !$"

gTVSecretBaseVisitText02::
	.string "Oh !\n"
	.string "Remarquable !\p"
	.string "Il n’y a pas un seul élément de\n"
	.string "décoration !\p"
	.string "C’est un très bon exemple de\n"
	.string "minimalisme !\p"
	.string "C’est très simple, mais ça en jette !\p"
	.string "Chapeau, {STR_VAR_1}.\n"
	.string "Je te reconnais bien là !$"

gTVSecretBaseVisitText03::
	.string "Oh ! Je vois !\n"
	.string "C’est très clair !\p"
	.string "{STR_VAR_2}… A cet endroit…\n"
	.string "Le message est fort !$"

gTVSecretBaseVisitText04::
	.string "Oh ! Je vois !\n"
	.string "C’est très clair !\p"
	.string "Les décorations ne se bousculent\n"
	.string "pas !\p"
	.string "Le message n’en est que plus fort !$"

gTVSecretBaseVisitText05::
	.string "Waouh !\p"
	.string "{STR_VAR_2}, {STR_VAR_3}…\n"
	.string "Ça se marie à merveille !\p"
	.string "On ne pouvait pas rêver de meilleur\n"
	.string "choix !$"

gTVSecretBaseVisitText06::
	.string "Waouh !\p"
	.string "{STR_VAR_2}…\n"
	.string "Cet élément de décoration\l"
	.string "est très bien placé !\p"
	.string "Sa présence remplit toute la\n"
	.string "Base Secrète !$"

gTVSecretBaseVisitText07::
	.string "Waouh !\p"
	.string "Il n’y a absolument rien ici.\p"
	.string "Cet espace vide donne un certain\n"
	.string "cachet à la Base Secrète.$"

gTVSecretBaseVisitText08::
	.string "Oh !\n"
	.string "Voici {STR_VAR_1}!\l"
	.string "Testons un peu ce Dresseur !\p"
	.string "… … … … … …\n"
	.string "… … … … … …$"

gTVSecretBaseVisitText09::
	.string "Oh…\n"
	.string "{STR_VAR_1} a gagné, je m’incline.\p"
	.string "Les Pokémon de ce Dresseur ont aussi\n"
	.string "mérité le titre de Maitre.\p"
	.string "Ils reflètent la résistance de\n"
	.string "{STR_VAR_1} en tant que Dresseur.\p"
	.string "Le {STR_VAR_2} connaissait même\n"
	.string "{STR_VAR_3}…\p"
	.string "Ça nous en dit long sur\n"
	.string "{STR_VAR_1}.\p"
	.string "Quelle belle leçon !$"

gTVSecretBaseVisitText10::
	.string "Aïe…\n"
	.string "{STR_VAR_1} a gagné, je m’incline.\p"
	.string "Les Pokémon de ce Dresseur sont\n"
	.string "incroyablement forts !\p"
	.string "Ils reflètent la ténacité de\n"
	.string "{STR_VAR_1} en tant que Dresseur.\p"
	.string "Le {STR_VAR_2} connaissait même\n"
	.string "{STR_VAR_3}…\p"
	.string "Ça nous en dit long sur\n"
	.string "{STR_VAR_1}.\p"
	.string "Quelle belle leçon !$"

gTVSecretBaseVisitText11::
	.string "Waouh !\n"
	.string "{STR_VAR_1} a gagné, je m’incline.\p"
	.string "Les Pokémon de ce Dresseur sont\n"
	.string "très équilibrés.\p"
	.string "Ils reflètent le sérieux de\n"
	.string "{STR_VAR_1} en tant que Dresseur.\p"
	.string "Le {STR_VAR_2} connaissait même\n"
	.string "{STR_VAR_3}…\p"
	.string "Ça nous en dit long sur\n"
	.string "{STR_VAR_1}.\p"
	.string "Quelle belle leçon !$"

gTVSecretBaseVisitText12::
	.string "Bien, bien !\n"
	.string "{STR_VAR_1} a gagné, je m’incline.\p"
	.string "Les Pokémon de ce Dresseur\n"
	.string "sont très prometteurs.\p"
	.string "Ils reflètent les espoirs et les\n"
	.string "rêves de {STR_VAR_1}.\p"
	.string "Le {STR_VAR_2} connaissait même\n"
	.string "{STR_VAR_3}…\p"
	.string "Ça nous en dit long sur\n"
	.string "{STR_VAR_1}.\p"
	.string "Quelle belle leçon !$"

gTVSecretBaseVisitText13::
	.string "Cette Base Secrète était vraiment\n"
	.string "superbe, les amis ! \p"
	.string "Si vous avez l’occasion, visitez la\n"
	.string "Base Secrète de {STR_VAR_1}.\p"
	.string "Allez, à la prochaîne !$"

gTVPokemonLotteryWinnerFlashReportText00::
	.string "Quel suspense !\n"
	.string "Quelle tension !\p"
	.string "Voici le Flash Spécial de la\n"
	.string "Loterie Pokémon !\p"
	.string "Bonjour à tous, en direct de la Loterie\n"
	.string "Pokémon, au rez-de-chaussée du\l"
	.string "Centre Commercial Nénucrique !\p"
	.string "Comme d’habitude, nous avons\n"
	.string "un heureux Dresseur !\p"
	.string "Ce Dresseur s’appelle…\n"
	.string "{STR_VAR_1}!\p"
	.string "{STR_VAR_1} a gagné le\n"
	.string "{STR_VAR_2}, {STR_VAR_3}!\p"
	.string "Félicitations,\n"
	.string "{STR_VAR_1}!\p"
	.string "Chers téléspectateurs,\n"
	.string "à vous de jouer maintenant !\p"
	.string "Nous vous attendons avec impatience\n"
	.string "au Centre Commercial Nénucrique !\p"
	.string "Nous étions en direct du Centre\n"
	.string "Commercial Nénucrique pour\l"
	.string "vous, résidents de Hoenn !$"

gTVThePokemonBattleSeminarText00::
	.string "Travaux Pratiques Pokémon !\p"
	.string "Nous étudions les combats de Pokémon\n"
	.string "des autres et en tirons des leçons.\p"
	.string "Notre sujet d’aujourd’hui sera un\n"
	.string "combat mené par {STR_VAR_1}.\p"
	.string "Le {STR_VAR_2} de {STR_VAR_1} s’est\n"
	.string "battu contre un {STR_VAR_3}…$"

gTVThePokemonBattleSeminarText01::
	.string "Il a utilisé {STR_VAR_3} contre\n"
	.string "le {STR_VAR_2}…\p"
	.string "Hum… {STR_VAR_1}!\n"
	.string "Ça ne va pas du tout !$"

gTVThePokemonBattleSeminarText02::
	.string "Notez que le {STR_VAR_1} de ce\n"
	.string "Dresseur connaissait également$"

gTVThePokemonBattleSeminarText03::
	.string "{STR_VAR_1}, {STR_VAR_2}\n"
	.string "et {STR_VAR_3}.$"

gTVThePokemonBattleSeminarText04::
	.string "{STR_VAR_1} et\n"
	.string "{STR_VAR_2}.$"

gTVThePokemonBattleSeminarText05::
	.string "{STR_VAR_2}.$"

gTVThePokemonBattleSeminarText06::
	.string "Quelle capacité ce Dresseur aurait-il\n"
	.string "dû utiliser ?\p"
	.string "… … … … … …\n"
	.string "{STR_VAR_1}, voyons !\p"
	.string "{STR_VAR_1} aurait été bien plus\n"
	.string "efficace que {STR_VAR_2}!\p"
	.string "Chers téléspectateurs, j’espère que\n"
	.string "l’erreur de ce Dresseur vous servira !\p"
	.string "A la prochaîne !$"

gTVTrainerFanClubText00::
	.string "Allez, tous ensemble !\n"
	.string "Le Fan Club des Dresseurs !\p"
	.string "Animateur : Alors, ça groove chez vous ?\n"
	.string "Aujourd’hui, nous avons réuni tous\l"
	.string "les Dresseurs fans de {STR_VAR_1}!\p"
	.string "Fans : Ouais !!!!!!!\p"
	.string "Fans : {STR_VAR_1}!\p"
	.string "Animateur : Tous ensemble !\n"
	.string "Est-ce que vous aimez {STR_VAR_1}?\p"
	.string "Fans : On aime {STR_VAR_1}!\p"
	.string "Animateur : Qu’est-ce qui vous plaît\n"
	.string "chez {STR_VAR_1}?!$"

gTVTrainerFanClubText01::
	.string "Fans : Ce Dresseur a un super\n"
	.string "lancer de POKé Balls !$"

gTVTrainerFanClubText02::
	.string "Fans : On adore sa façon de courir !$"

gTVTrainerFanClubText03::
	.string "Fans : Ce Dresseur sait se montrer\n"
	.string "fort quand les choses se corsent !$"

gTVTrainerFanClubText04::
	.string "Fans : Ce Dresseur en connaît un rayon\n"
	.string "sur les Pokémon !$"

gTVTrainerFanClubText05::
	.string "Fans : Ce Dresseur est d’une telle\n"
	.string "gentillesse avec les Pokémon !$"

gTVTrainerFanClubText06::
	.string "Fans : Ce Dresseur a une super\n"
	.string "technique à Vélo !$"

gTVTrainerFanClubText07::
	.string "Fans : Sa façon d’acheter des objets !$"

gTVTrainerFanClubText08::
	.string "Fans : Les surnoms que ce Dresseur\n"
	.string "donne aux Pokémon !$"

gTVTrainerFanClubText09::
	.string "Fans : Le goût avec lequel ce\n"
	.string "Dresseur a décoré sa Base Secrète !$"

gTVTrainerFanClubText10::
	.string "Fans : Ce Dresseur utilise les CT\n"
	.string "avec un tel aplomb !$"

gTVTrainerFanClubText11::
	.string "Animateur : Comme vous avez vu,\n"
	.string "{STR_VAR_1} en jette !\p"
	.string "Les Fans de {STR_VAR_1}\n"
	.string "ont un slogan !\p"
	.string "Animateur : Quand je dis {STR_VAR_1},\n"
	.string "vous dites…\p"
	.string "Fans : {STR_VAR_2}!\p"
	.string "Fans : {STR_VAR_3}!\p"
	.string "Fans : {STR_VAR_2}!\p"
	.string "Fans : {STR_VAR_3}!\p"
	.string "Animateur : Exactement ! Si quelqu’un dit\n"
	.string "“{STR_VAR_1}”…\p"
	.string "Il faut répondre “{STR_VAR_2}\n"
	.string "{STR_VAR_3}” !\p"
	.string "Je dois avouer que ça sonne bien !\n"
	.string "Je comprends les Fans de {STR_VAR_1}!\p"
	.string "Toi, en face de ta télé, avec nous !\n"
	.string "Tous ensemble !\p"
	.string "Animateur : Quand je dis {STR_VAR_1},\n"
	.string "vous dites…\p"
	.string "Fans : {STR_VAR_2}!\p"
	.string "Fans : {STR_VAR_3}!\p"
	.string "Fans : {STR_VAR_2}!\p"
	.string "Fans : {STR_VAR_3}!\p"
	.string "Animateur : Je remercie tous les\n"
	.string "Fans de {STR_VAR_1}!\l"
	.string "Quelle ambiance ici !\p"
	.string "Animateur : Quand je dis {STR_VAR_1},\n"
	.string "vous dites…\p"
	.string "Fans : {STR_VAR_2}!\p"
	.string "Fans : {STR_VAR_3}!$"

TVSpotTheCuties_Text_Intro::
	.string "Qu’Ils Sont Mignons !\n"
	.string "Pokémon Enrubannés !\p"
	.string "Bonjour, téléspectateurs chéris !\p"
	.string "Il n’y a rien de plus craquant qu’un\n"
	.string "Pokémon avec des Rubans, non ?\p"
	.string "Aujourd’hui, j’aimerais vous présenter\n"
	.string "un adorable Pokémon que j’ai remarqué\l"
	.string "en ville.\p"
	.string "C’est le petit {STR_VAR_2}\n"
	.string "de {STR_VAR_1}.$"

TVSpotTheCuties_Text_RibbonsLow::
	.string "Le nombre de Rubans que\n"
	.string "{STR_VAR_2} portait était de {STR_VAR_3}.\p"
	.string "Ça montre à quel point {STR_VAR_1}\n"
	.string "adore ses Pokémon.$"

TVSpotTheCuties_Text_RibbonsMid::
	.string "{STR_VAR_2} porte le nombre incroyable\n"
	.string "de {STR_VAR_3} Rubans !\p"
	.string "Ça nous en dit long sur l’engagement\n"
	.string "de {STR_VAR_1} envers ses Pokémon !$"

TVSpotTheCuties_Text_RibbonsHigh::
	.string "{STR_VAR_2} porte le nombre incroyable\n"
	.string "de {STR_VAR_3} Rubans !\p"
	.string "Ça nous montre bien que {STR_VAR_1} se\n"
	.string "consacre totalement à ses Pokémon !$"

TVSpotTheCuties_Text_RibbonIntro::
	.string "Regardons de plus près les\n"
	.string "Rubans de {STR_VAR_2}.$"

TVSpotTheCuties_Text_RibbonChampion::
	.string "Le Ruban Champion est\n"
	.string "particulièrement seyant.\p"
	.string "{STR_VAR_2} l’a reçu à son entrée au\n"
	.string "Panthéon des Dresseurs.\p"
	.string "Il témoigne du courage de\n"
	.string "{STR_VAR_2}.\p"
	.string "{STR_VAR_2} avec le Ruban Champion !\n"
	.string "Il lui va vraiment très bien !$"

TVSpotTheCuties_Text_RibbonCool::
	.string "Le Ruban Sang-Froid est\n"
	.string "particulièrement seyant.\p"
	.string "{STR_VAR_2} l’a obtenu en remportant\n"
	.string "un Concours de Sang-Froid.\p"
	.string "Il témoigne du sang-froid\n"
	.string "de {STR_VAR_2}.\p"
	.string "{STR_VAR_2} avec le Ruban Sang-Froid !\n"
	.string "Il lui va vraiment très bien !$"

TVSpotTheCuties_Text_RibbonBeauty::
	.string "Le Ruban Beauté est\n"
	.string "particulièrement seyant.\p"
	.string "{STR_VAR_2} l’a obtenu en remportant\n"
	.string "un Concours de Beauté.\p"
	.string "Il rend hommage à la beauté\n"
	.string "de {STR_VAR_2}.\p"
	.string "{STR_VAR_2} avec le Ruban Beauté !\n"
	.string "Il lui va vraiment très bien !$"

TVSpotTheCuties_Text_RibbonCute::
	.string "Le Ruban Grâce est\n"
	.string "particulièrement seyant.\p"
	.string "{STR_VAR_2} l’a obtenu en remportant\n"
	.string "un Concours de Grâce.\p"
	.string "Il témoigne de la grâce\n"
	.string "de {STR_VAR_2}.\p"
	.string "{STR_VAR_2} avec le Ruban Grâce !\n"
	.string "Il lui va vraiment très bien !$"

TVSpotTheCuties_Text_RibbonSmart::
	.string "Le Ruban Intelligence est\n"
	.string "particulièrement seyant.\p"
	.string "{STR_VAR_2} l’a obtenu en remportant\n"
	.string "un Concours D’Intelligence.\p"
	.string "Il témoigne de l’intelligence\n"
	.string "de {STR_VAR_2}.\p"
	.string "{STR_VAR_2} avec le Ruban Intelli-\n"
	.string "Gence ! Il lui va vraiment très bien !$"

TVSpotTheCuties_Text_RibbonTough::
	.string "Le Ruban Robustesse est\n"
	.string "particulièrement seyant.\p"
	.string "{STR_VAR_2} l’a obtenu en remportant\n"
	.string "un Concours de Robustesse.\p"
	.string "Il témoigne de la robustesse\n"
	.string "de {STR_VAR_2}.\p"
	.string "{STR_VAR_2} avec le Ruban Robustesse !\n"
	.string "Il lui va vraiment très bien !$"

TVSpotTheCuties_Text_RibbonWinning::
	.string "Le Ruban Gagnant est\n"
	.string "particulièrement seyant.\p"
	.string "{STR_VAR_2} l’a obtenu pour ses\n"
	.string "exploits à la Tour de Combat.\p"
	.string "Il témoigne de la puissance\n"
	.string "de {STR_VAR_2}.\p"
	.string "{STR_VAR_2} avec le Ruban Gagnant !\n"
	.string "Il lui va vraiment très bien !$"

TVSpotTheCuties_Text_RibbonVictory::
	.string "Le Ruban Victoire est\n"
	.string "particulièrement seyant.\p"
	.string "{STR_VAR_2} l’a obtenu pour ses\n"
	.string "exploits à la Tour de Combat.\p"
	.string "Il témoigne de la puissance\n"
	.string "incroyable de {STR_VAR_2}.\p"
	.string "{STR_VAR_2} avec le Ruban Victoire !\n"
	.string "Il lui va vraiment très bien !$"

TVSpotTheCuties_Text_RibbonArtist::
	.string "Le Ruban Artiste est\n"
	.string "particulièrement seyant.\p"
	.string "{STR_VAR_2} l’a obtenu en servant de\n"
	.string "modèle à un artiste.\p"
	.string "Il témoigne du charme\n"
	.string "de {STR_VAR_2}.\p"
	.string "{STR_VAR_2} avec le Ruban Artiste !\n"
	.string "Il lui va vraiment très bien !$"

TVSpotTheCuties_Text_RibbonEffort::
	.string "Le Ruban Effort est\n"
	.string "particulièrement seyant.\p"
	.string "{STR_VAR_2} l’a obtenu pour avoir\n"
	.string "été un travailleur dévoué.\p"
	.string "Il témoigne de la détermination\n"
	.string "de {STR_VAR_2}.\p"
	.string "{STR_VAR_2} avec le Ruban travailleur !\n"
	.string "Il lui va vraiment très bien !$"

TVSpotTheCuties_Text_Outro::
	.string "Oh…\p"
	.string "Les Rubans et les Pokémon…\n"
	.string "Ils vont si bien ensemble !\p"
	.string "Je vais défaillir, je préfère vous\n"
	.string "dire au revoir !$"

gTVPokemonNewsBattleFrontierText00::
	.string "Bonjour à tous !\n"
	.string "C’est l’heure du Bulletin Pokémon.\p"
	.string "Nous avons des informations\n"
	.string "étonnantes en provenance de la\l"
	.string "Zone de Combat.$"

gTVPokemonNewsBattleFrontierText01::
	.string "Le Dresseur {STR_VAR_1} a établi un\n"
	.string "record de {STR_VAR_2} victoires consécutives\l"
	.string "au défi de la Salle de Combat Solo\l"
	.string "de la Tour de Combat.\p"
	.string "Bien joué, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText02::
	.string "Le Dresseur {STR_VAR_1} a établi un\n"
	.string "record de {STR_VAR_2} victoires consécutives\l"
	.string "au défi de la Salle de Combat Duo\l"
	.string "de la Tour de Combat.\p"
	.string "Bien joué, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText03::
	.string "Le Dresseur {STR_VAR_1} a établi un\n"
	.string "record de {STR_VAR_2} victoires consécutives\l"
	.string "au défi de la Salle de Combat Multi\l"
	.string "de la Tour de Combat.\p"
	.string "Bien joué, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText04::
	.string "Le Dresseur {STR_VAR_1} a établi un\n"
	.string "record de {STR_VAR_2} victoires consécutives\l"
	.string "au défi de la Salle de Combat Multi\l"
	.string "Link de la Tour de Combat.\p"
	.string "Bien joué, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText05::
	.string "Le Dresseur {STR_VAR_1} a établi un\n"
	.string "record au Tournoi de Combat Solo du\l"
	.string "Dôme de Combat en gagnant {STR_VAR_2} fois.\p"
	.string "Bien joué, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText06::
	.string "Le Dresseur {STR_VAR_1} a établi un\n"
	.string "record au Tournoi de Combat Duo du\l"
	.string "Dôme de Combat en gagnant {STR_VAR_2} fois.\p"
	.string "Bien joué, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText07::
	.string "Le Dresseur {STR_VAR_1} a établi un\n"
	.string "record de {STR_VAR_2} victoires consécutives\l"
	.string "au défi du Combat Échange Solo\l"
	.string "de l’Usine de Combat.\p"
	.string "Bien joué, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText08::
	.string "Le Dresseur {STR_VAR_1} a établi un\n"
	.string "record de {STR_VAR_2} victoires consécutives\l"
	.string "au défi du Combat Échange Duo\l"
	.string "de l’Usine de Combat.\p"
	.string "Bien joué, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText09::
	.string "Le Dresseur {STR_VAR_1} a établi un\n"
	.string "record ! Il a terminé {STR_VAR_2} salles lors\l"
	.string "du défi du Combat Hasard du\l"
	.string "Reptile de Combat.\p"
	.string "Bien joué, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText10::
	.string "Le Dresseur {STR_VAR_1} a établi un\n"
	.string "record de {STR_VAR_2} victoires consécutives\l"
	.string "au Tournoi K.O. du Dojo de Combat.\p"
	.string "Bien joué, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText11::
	.string "Le Dresseur {STR_VAR_1} a établi un\n"
	.string "record de {STR_VAR_2} victoires consécutives\l"
	.string "au défi du Hall de Combat Solo du\l"
	.string "Palace de Combat.\p"
	.string "Bien joué, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText12::
	.string "Le Dresseur {STR_VAR_1} a établi un\n"
	.string "record de {STR_VAR_2} victoires consécutives\l"
	.string "au défi du Hall de Combat Duo du\l"
	.string "Palace de Combat.\p"
	.string "Bien joué, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText13::
	.string "Le Dresseur {STR_VAR_1} a établi un\n"
	.string "record ! Il a terminé {STR_VAR_2} niveaux\l"
	.string "lors du défi du Combat Quête de\l"
	.string "la Pyramide de Combat.\p"
	.string "Bien joué, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText14::
	.string "Ainsi qu’aux trois Pokémon : {STR_VAR_1},\n"
	.string "{STR_VAR_2}, et {STR_VAR_3}!\p"
	.string "Félicitations pour cet exploit\n"
	.string "époustouflant !!$"

gTVPokemonNewsBattleFrontierText15::
	.string "Ainsi qu’aux deux Pokémon : {STR_VAR_1},\n"
	.string "et {STR_VAR_2}!\p"
	.string "Félicitations pour cet exploit\n"
	.string "époustouflant !!$"

gTVPokemonNewsBattleFrontierText16::
	.string "Et aux quatre Pokémon : {STR_VAR_1}!\p"
	.string "{STR_VAR_2}!\p"
	.string "{STR_VAR_3}!$"

gTVPokemonNewsBattleFrontierText17::
	.string "Et {STR_VAR_1}!\p"
	.string "Félicitations pour cet exploit\n"
	.string "époustouflant !!$"

gTVPokemonNewsBattleFrontierText18::
	.string "Nous attendons avec impatience de\n"
	.string "connaître les prochains exploits de\l"
	.string "{STR_VAR_1} et de ses fidèles Pokémon !\p"
	.string "C’était le scoop du Bulletin Pokémon !$"

gTVWhatsNo1InHoennTodayText00::
	.string "Quoi de Neuf Dans Hoenn ?\n"
	.string "C’est reparti pour une émission\l"
	.string "de folie !\p"
	.string "Salut les amis, ça roule pour vous ?\p"
	.string "Penchons-nous sur le Dresseur\n"
	.string "qui a fait parler de lui aujourd’hui !\p"
	.string "Le Dresseur nº 1 du jour n’est\n"
	.string "autre que {STR_VAR_1}!$"

gTVWhatsNo1InHoennTodayText01::
	.string "Dans la même journée, {STR_VAR_1} a joué\n"
	.string "{STR_VAR_2} fois aux Machines A\l"
	.string "Sous du Casino.\p"
	.string "Des témoins auraient entendu\n"
	.string "{STR_VAR_1} murmurer : “Pour moi, les\l"
	.string "rouleaux ne bougent même pas…”\l"
	.string "Intéressant, non ?$"

gTVWhatsNo1InHoennTodayText02::
	.string "Dans la même journée, {STR_VAR_1} a joué\n"
	.string "{STR_VAR_2} fois à la Roulette du\l"
	.string "Casino.\p"
	.string "En plein jeu, on a entendu {STR_VAR_1}\n"
	.string "crier : “Que la bille décide !”\p"
	.string "Le visage du Dresseur affichait une\n"
	.string "concentration extrême.$"

gTVWhatsNo1InHoennTodayText03::
	.string "Dans la même journée, {STR_VAR_1} a\n"
	.string "battu des Pokémon sauvages {STR_VAR_2} fois !\p"
	.string "Les Pokémon de {STR_VAR_1} semblent\n"
	.string "être devenus beaucoup plus forts.\p"
	.string "Ils aiment se battre, peu importe\n"
	.string "l’endroit, le moment ou la manière !$"

gTVWhatsNo1InHoennTodayText04::
	.string "Dans la même journée, {STR_VAR_1} a\n"
	.string "utilisé le Mixeur {STR_VAR_2} fois !\p"
	.string "A la fin, {STR_VAR_1} avait la tête\n"
	.string "qui tournait.\p"
	.string "Le Dresseur titubait comme un\n"
	.string "Spinda !$"

gTVWhatsNo1InHoennTodayText05::
	.string "Dans la même journée, {STR_VAR_1} a\n"
	.string "planté {STR_VAR_2} Baies !\p"
	.string "Du coup, les vêtements de {STR_VAR_1}\n"
	.string "étaient couverts de terre.\p"
	.string "Là où ce Dresseur a semé, de\n"
	.string "nombreuses fleurs ont fleuri.\p"
	.string "On dit que les fleurs apaisent\n"
	.string "les gens.$"

gTVWhatsNo1InHoennTodayText06::
	.string "Dans la même journée, {STR_VAR_1} a\n"
	.string "cueilli {STR_VAR_2} Baies !\p"
	.string "Le Sac de {STR_VAR_1} était tellement\n"
	.string "plein que ce Dresseur avait du\l"
	.string "mal à marcher !$"

gTVWhatsNo1InHoennTodayText07::
	.string "Dans la même journée, {STR_VAR_1} a\n"
	.string "obtenu {STR_VAR_2} Points de Combat !\p"
	.string "{STR_VAR_1} a eu du mal à décider contre\n"
	.string "quoi échanger ses Points de Combat.\l"
	.string "Il a longuement hésité entre un objet\l"
	.string "sympa et une décoration chic.\p"
	.string "Trop de choix s’offraient à ce\n"
	.string "Dresseur.$"

gTVWhatsNo1InHoennTodayText08::
	.string "N’est-ce pas incroyable ?\p"
	.string "{STR_VAR_1}!\n"
	.string "Le Dresseur nº 1 !\p"
	.string "Prenez exemple sur {STR_VAR_1}!\n"
	.string "Devenez le nº 1 du jour !$"

TVSecretBaseSecrets_Text_Intro::
	.string "Secrets de Bases Secrètes !\p"
	.string "Si les murs pouvaient parler, que nous\n"
	.string "diraient ceux des Bases Secrètes ?\p"
	.string "Aujourd’hui, nous allons observer\n"
	.string "la Base Secrète de {STR_VAR_1}.\p"
	.string "Oh ? On dirait que {STR_VAR_2} vient\n"
	.string "d’arriver.\p"
	.string "Observons discrètement cette visite !\p"
	.string "Que va faire {STR_VAR_2}?$"

TVSecretBaseSecrets_Text_WhatWillPlayerDoNext1::
	.string "Que va faire {STR_VAR_2} maintenant ?$"

TVSecretBaseSecrets_Text_WhatWillPlayerDoNext2::
	.string "Et maintenant, que va faire\n"
	.string "{STR_VAR_2}?$"

TVSecretBaseSecrets_Text_TookXStepsBeforeLeaving::
	.string "Finalement, {STR_VAR_2} a fait {STR_VAR_3} pas\n"
	.string "dans la Base Secrète de {STR_VAR_1}\l"
	.string "avant de partir.$"

TVSecretBaseSecrets_Text_BaseFailedToInterestPlayer::
	.string "Hum…\p"
	.string "La Base Secrète de {STR_VAR_1} ne\n"
	.string "semble pas intéresser {STR_VAR_2}…$"

TVSecretBaseSecrets_Text_PlayerEnjoyedBase::
	.string "{STR_VAR_2} a l’air de beaucoup aimer la\n"
	.string "Base Secrète de {STR_VAR_1}.$"

TVSecretBaseSecrets_Text_PlayerHugeFanOfBase::
	.string "{STR_VAR_2} semble se trouver très à\n"
	.string "l’aise dans la Base Secrète de\l"
	.string "{STR_VAR_1}.$"

TVSecretBaseSecrets_Text_Outro::
	.string "J’espère que nous vous aurons donné\n"
	.string "envie d’aller faire un tour dans la Base\l"
	.string "Secrète de {STR_VAR_1}!\p"
	.string "A bientôt dans une autre Base Secrète !\n"
	.string "Mais chut… c’est un secret…$"

TVSecretBaseSecrets_Text_StoppedMoving1::
	.string "Notre visiteur est immobile !\p"
	.string "Une vraie statue !\p"
	.string "La Base Secrète de {STR_VAR_1}\n"
	.string "serait-elle soporifique ?$"

TVSecretBaseSecrets_Text_StoppedMoving2::
	.string "Notre visiteur est immobile !\p"
	.string "Une vraie statue !\p"
	.string "Serait-ce un accès de fatigue ? Ou\n"
	.string "le signe d’un ennui profond ?$"

TVSecretBaseSecrets_Text_UsedChair::
	.string "Notre visiteur s’assoit sur une chaise !\p"
	.string "Cette Base Secrète a l’air\n"
	.string "confortable !\p"
	.string "Cette chaise semble lui plaire\n"
	.string "énormément !$"

TVSecretBaseSecrets_Text_UsedBalloon::
	.string "Notre visiteur s’en prend à un ballon !\p"
	.string "Oh, non ! Le ballon a éclaté,\n"
	.string "chers téléspectateurs !\p"
	.string "Le bruit semble avoir surpris notre\n"
	.string "visiteur !$"

TVSecretBaseSecrets_Text_UsedTent::
	.string "Notre visiteur est dans une Tente !\p"
	.string "Notre visiteur se promène !\p"
	.string "Notre visiteur gambade !\p"
	.string "La taille de cette Tente a dû le\n"
	.string "surprendre !$"

TVSecretBaseSecrets_Text_UsedPlant::
	.string "Notre visiteur observe une\n"
	.string "plante !\p"
	.string "Notre visiteur semble avoir un\n"
	.string "goût très sûr.$"

TVSecretBaseSecrets_Text_UsedGoldShield::
	.string "Notre visiteur observe un\n"
	.string "Bouclier Or !\p"
	.string "L’émerveillement se lit dans les yeux de\n"
	.string "notre visiteur !$"

TVSecretBaseSecrets_Text_UsedSilverShield::
	.string "Notre visiteur observe un\n"
	.string "Bouclier Argent !\p"
	.string "Notre visiteur en prend plein les\n"
	.string "mirettes !$"

TVSecretBaseSecrets_Text_UsedGlassOrnament::
	.string "Notre visiteur observe un\n"
	.string "Ornement Verre !\p"
	.string "Oh, non !\p"
	.string "Notre visiteur le touche !\p"
	.string "Il va être couvert de traces de\n"
	.string "doigts…$"

TVSecretBaseSecrets_Text_UsedTV::
	.string "Notre visiteur regarde la télévision !\p"
	.string "Cela semble l’intéresser au plus haut\n"
	.string "point !$"

TVSecretBaseSecrets_Text_UsedMudBall::
	.string "Notre visiteur a vu une\n"
	.string "Boule de Boue !\p"
	.string "Cela semble lui plaire !$"

TVSecretBaseSecrets_Text_UsedBag::
	.string "Oh ?\p"
	.string "Notre visiteur a ouvert son Sac\n"
	.string "et y cherche quelque chose !\p"
	.string "{STR_VAR_2}? C’est donc ça que notre\n"
	.string "visiteur cherchait !\p"
	.string "Regardez le sourire de notre visiteur\n"
	.string "alors qu’il brandit l’objet !\p"
	.string "On pourrait en faire une pub pour un\n"
	.string "dentifrice !$"

TVSecretBaseSecrets_Text_UsedCushion::
	.string "Notre visiteur saisit un coussin et…$"

TVSecretBaseSecrets_Text_HitCushion::
	.string "le frappe ?!?\p"
	.string "Notre visiteur semble avoir besoin de\n"
	.string "se défouler un peu.$"

TVSecretBaseSecrets_Text_HuggedCushion::
	.string "le sert bien fort dans ses bras !\p"
	.string "Notre visiteur a visiblement\n"
	.string "besoin d’affection !$"

TVSecretBaseSecrets_Text_BattledWon::
	.string "Notre visiteur est en pleine discussion\n"
	.string "avec {STR_VAR_1}!\p"
	.string "On dirait qu’un combat se prépare !\p"
	.string "Et…\p"
	.string "C’est notre visiteur qui\n"
	.string "remporte le combat !\p"
	.string "Notre visiteur entame une danse de la\n"
	.string "victoire !$"

TVSecretBaseSecrets_Text_BattledLost::
	.string "Notre visiteur est en pleine discussion\n"
	.string "avec {STR_VAR_1}!\p"
	.string "On dirait qu’un combat se prépare !\p"
	.string "Et…\p"
	.string "C’est {STR_VAR_1} qui l’emporte !\n"
	.string "Notre pauvre visiteur a perdu !\p"
	.string "Notre visiteur a l’air de s’en\n"
	.string "vouloir !$"

TVSecretBaseSecrets_Text_DeclinedBattle::
	.string "Notre visiteur est en pleine discussion\n"
	.string "avec {STR_VAR_1}!\p"
	.string "On dirait qu’un combat se prépare !\p"
	.string "Et…\p"
	.string "Non, notre visiteur refuse de se\n"
	.string "battre !\p"
	.string "Il n’y aura pas de combat !\p"
	.string "{STR_VAR_1} ne lui a pas plu ?$"

TVSecretBaseSecrets_Text_UsedPoster::
	.string "Notre visiteur a les yeux rivés sur\n"
	.string "un poster !\p"
	.string "Ce poster est-il au goût de notre\n"
	.string "visiteur ?\p"
	.string "Mais… Le regard de notre\n"
	.string "visiteur est pour le moins troublant.$"

TVSecretBaseSecrets_Text_UsedNoteMat::
	.string "Notre visiteur a marché sur un Tapis\n"
	.string "Note !\p"
	.string "Tiens… Notre visiteur a composé\n"
	.string "un air entraînant !$"

TVSecretBaseSecrets_Text_BattledDraw::
	.string "Notre visiteur est en pleine discussion\n"
	.string "avec {STR_VAR_1}!\p"
	.string "On dirait qu’un combat se prépare !\p"
	.string "Et…\p"
	.string "Égalité !\n"
	.string "Un combat pour rien.\p"
	.string "On peut lire la déception sur le visage\n"
	.string "des deux Dresseurs !$"

TVSecretBaseSecrets_Text_UsedSpinMat::
	.string "Notre visiteur a marché sur un Tapis\n"
	.string "Tournant !\p"
	.string "On dirait que sa tête tourne !\p"
	.string "Notre visiteur ne marche plus très\n"
	.string "droit !$"

TVSecretBaseSecrets_Text_UsedSandOrnament::
	.string "Notre visiteur s’approche d’une\n"
	.string "Déco de Sable !\p"
	.string "Oh !\p"
	.string "L’objet s’effrite !\n"
	.string "Il s’est cassé !\p"
	.string "Notre visiteur a l’air penaud !$"

TVSecretBaseSecrets_Text_UsedDesk::
	.string "Notre visiteur passe son doigt sur\n"
	.string "le bureau !\p"
	.string "La poussière semble l’agacer !\p"
	.string "Eh bien, notre visiteur semble être\n"
	.string "très attaché à la propreté !$"

TVSecretBaseSecrets_Text_UsedBrick::
	.string "Notre visiteur regarde une Brique !\p"
	.string "Peut-être est-ce l’objet sur la Brique\n"
	.string "qui intéresse notre visiteur ?$"

TVSecretBaseSecrets_Text_UsedSolidBoard::
	.string "Notre visiteur marche sur une\n"
	.string "Planche Solide.\p"
	.string "Notre visiteur regarde en bas !\p"
	.string "Notre visiteur ne semble pas être\n"
	.string "très téméraire !$"

TVSecretBaseSecrets_Text_UsedFence::
	.string "Notre visiteur contemple une\n"
	.string "Barrière !\p"
	.string "Notre visiteur serait-il en train de\n"
	.string "manigancer quelque chose ?$"

TVSecretBaseSecrets_Text_UsedGlitterMat::
	.string "Notre visiteur est sur un\n"
	.string "Tapis Brillant !\p"
	.string "Notre visiteur semble prendre la pose !\p"
	.string "Notre visiteur se prendrait-il pour une\n"
	.string "star ?$"

TVSecretBaseSecrets_Text_UsedTire::
	.string "Notre visiteur regarde un Pneu !\p"
	.string "Notre visiteur penserait-il à s’acheter\n"
	.string "une voiture ?$"

TVSecretBaseSecrets_Text_UsedStand::
	.string "Notre visiteur se trouve sur une\n"
	.string "Estrade !\p"
	.string "Notre visiteur regarde la Base Secrète\n"
	.string "de {STR_VAR_1} d’en haut !\p"
	.string "Et…\p"
	.string "Notre visiteur se met à hurler !\n"
	.string "Incroyable !$"

TVSecretBaseSecrets_Text_BrokeDoor::
	.string "Notre visiteur a foncé tête la première\n"
	.string "dans une Porte Cassable !\p"
	.string "Notre visiteur est pris d’un fou rire !$"

TVSecretBaseSecrets_Text_UsedDoll::
	.string "Notre visiteur parle à une Poupée !\p"
	.string "Ça donne la chair de poule…$"

TVSecretBaseSecrets_Text_UsedSlide::
	.string "Notre visiteur monte sur un\n"
	.string "Toboggan !\p"
	.string "Et…\p"
	.string "glisse jusqu’en bas !\p"
	.string "On dirait que notre visiteur\n"
	.string "s’amuse bien !$"

TVSecretBaseSecrets_Text_UsedSlideButDidntGoDown::
	.string "Notre visiteur monte sur un\n"
	.string "Toboggan !\p"
	.string "Et…\p"
	.string "Apparemment, il préfère redescendre !\p"
	.string "Notre visiteur aurait-il le vertige ?$"

TVSecretBaseSecrets_Text_UsedJumpMat::
	.string "Notre visiteur se trouve sur un\n"
	.string "Tapis Sauteur !\p"
	.string "Notre visiteur saute !\p"
	.string "Et saute encore !\p"
	.string "Belle réception au sol !\p"
	.string "Notre visiteur s’applaudit !\n"
	.string "Une jolie performance en solo !$"

gTVSafariFanClubText00::
	.string "Fan Club Safari !\p"
	.string "Journaliste : Alors, les amis !\n"
	.string "En train de lancer des Safari Balls ?\p"
	.string "Comme vous vous en doutez, je suis\n"
	.string "au Parc Safari !\p"
	.string "Discutons un peu avec le Guide\n"
	.string "Safari !\p"
	.string "Comment se débrouillent les\n"
	.string "Dresseurs aujourd’hui ?$"

gTVSafariFanClubText01::
	.string "Guide : Ils ont tous l’air d’y mettre\n"
	.string "du leur et de s’appliquer.\p"
	.string "{STR_VAR_1} réussit particulièrement\n"
	.string "bien.\p"
	.string "{STR_VAR_1} a attrapé {STR_VAR_2} Pokémon.$"

gTVSafariFanClubText02::
	.string "Ce Dresseur sait utiliser les {POKEBLOCK}s.\n"
	.string "Je crois qu’il en a utilisé {STR_VAR_2}.$"

gTVSafariFanClubText03::
	.string "Ce Dresseur n’a pas utilisé un\n"
	.string "seul {POKEBLOCK}!\p"
	.string "Du travail de pro.$"

gTVSafariFanClubText04::
	.string "Journaliste : Vraiment ?\p"
	.string "On dirait que notre {STR_VAR_1}\n"
	.string "excelle au Safari !\p"
	.string "Guide : J’espère que ce Dresseur va\n"
	.string "revenir nous montrer sa technique.$"

gTVSafariFanClubText05::
	.string "Guide : Ils ne semblent pas avoir\n"
	.string "beaucoup de succès.\p"
	.string "{STR_VAR_1} s’est particulièrement\n"
	.string "mal débrouillé.\p"
	.string "Ce Dresseur n’a attrapé que\n"
	.string "{STR_VAR_2} Pokémon.$"

gTVSafariFanClubText06::
	.string "Guide : Ils ne semblent pas avoir\n"
	.string "beaucoup de succès.\p"
	.string "{STR_VAR_1} s’est particulièrement\n"
	.string "mal débrouillé.\p"
	.string "Ce Dresseur n’a attrapé aucun\n"
	.string " Pokémon.$"

gTVSafariFanClubText07::
	.string "Ce Dresseur utilise des {POKEBLOCK}s.\n"
	.string "Je crois qu’il en a utilisé {STR_VAR_2}.\p"
	.string "J’aimerais bien que ce Dresseur\n"
	.string "s’améliore un peu.$"

gTVSafariFanClubText08::
	.string "Je pense que ce Dresseur aurait\n"
	.string "eu plus de chance en utilisant des\l"
	.string "{POKEBLOCK}s, chose qu’il n’a pas faite.$"

gTVSafariFanClubText09::
	.string "Journaliste : Vraiment ?\p"
	.string "On dirait que le Safari et\n"
	.string "{STR_VAR_1}, ça fait deux !\p"
	.string "Guide : J’espère que ce Dresseur\n"
	.string "reviendra souvent pour s’entraîner.$"

gTVSafariFanClubText10::
	.string "Journaliste : Bien sûr !\n"
	.string "Il ne faut pas baisser les bras !\p"
	.string "Téléspectateurs, venez au\n"
	.string "Parc Safari vous aussi !\p"
	.string "A la prochaîne, ciao !$"

ContestLiveUpdates_Text_Intro::
	.string "“Infos Concours Pokémon”\p"
	.string "Animatrice : Merci de nous retrouver !\p"
	.string "Nous sommes en direct depuis\n"
	.string "le nouveau site {STR_VAR_1}.\p"
	.string "Le hall est rempli du public\n"
	.string "qui ne souhaite pas partir.\p"
	.string "Spectateur : {STR_VAR_2}!\p"
	.string "Spectateur : {STR_VAR_3}!\p"
	.string "Animatrice : Comme vous venez de\n"
	.string "l’apprendre, le Concours a été\l"
	.string "remporté par le {STR_VAR_2} de {STR_VAR_3}.\p"
	.string "Spectateur : {STR_VAR_2}!\n"
	.string "Tu es le meilleur !\p"
	.string "Spectateur : {STR_VAR_3}!\n"
	.string "Bien joué !\p"
	.string "Animatrice : Écoutons voir ce que\n"
	.string "les fans ont à dire à propos\l"
	.string "de ce Concours.$"

ContestLiveUpdates_Text_WonBothRounds::
	.string "Spectateur : {STR_VAR_2} était en tête\n"
	.string "aux jugements préliminaire et\l"
	.string "secondaire !\p"
	.string "Ce {STR_VAR_2} est sur la bonne voie !$"

ContestLiveUpdates_Text_BetterRound2::
	.string "Spectateur : {STR_VAR_2} n’a pas eu un\n"
	.string "bon résultat au jugement préliminaire,\p"
	.string "mais s’est rattrapé au jugement\n"
	.string "secondaire !$"

ContestLiveUpdates_Text_EqualRounds::
	.string "Spectateur : {STR_VAR_2} est resté\n"
	.string "constant durant les deux jugements.\p"
	.string "{STR_VAR_3} et {STR_VAR_2} forment une\n"
	.string "sacrée paire !$"

ContestLiveUpdates_Text_BetterRound1::
	.string "Spectateur : Du point de vue {STR_VAR_1},\n"
	.string "ce {STR_VAR_2} a été exceptionnel.\p"
	.string "Mais j’espère qu’il arrivera à nous\n"
	.string "surprendre encore plus la prochaîne\l"
	.string "fois.$"

ContestLiveUpdates_Text_GotNervous::
	.string "Spectateur : Quand le {STR_VAR_2} a\n"
	.string "commencé à se montrer nerveux,\p"
	.string "je n’ai pas pu m’empêcher de crier\n"
	.string "pour l’encourager.\p"
	.string "Je n’ai qu’un mot à dire à ce\n"
	.string "{STR_VAR_2}: félicitations !$"

ContestLiveUpdates_Text_StartledFoes::
	.string "Spectateur : Ce {STR_VAR_2} a réussi à\n"
	.string "m’enflammer !\p"
	.string "{STR_VAR_2}, tu as été formidable !$"

ContestLiveUpdates_Text_UsedCombo::
	.string "Spectateur : Ce combo de {STR_VAR_2}\n"
	.string "était à couper le souffle !\p"
	.string "J’en tremble encore !$"

ContestLiveUpdates_Text_ExcitingAppeal::
	.string "Spectateur : La démonstration du\n"
	.string "{STR_VAR_2} gagnant a fait vibrer\l"
	.string "mon cœur !$"

ContestLiveUpdates_Text_WasCool::
	.string "{STR_VAR_2}! Tu as fait preuve d’un\n"
	.string "sang-froid incroyable !$"

ContestLiveUpdates_Text_WasBeautiful::
	.string "{STR_VAR_2}!\n"
	.string "C’était de toute beauté !$"

ContestLiveUpdates_Text_WasCute::
	.string "{STR_VAR_2}!\n"
	.string "C’était super gracieux !$"

ContestLiveUpdates_Text_WasSmart::
	.string "{STR_VAR_2}!\n"
	.string "Tu as fait preuve d’intelligence !$"

ContestLiveUpdates_Text_WasTough::
	.string "{STR_VAR_2}!\n"
	.string "Tu as su montrer ta robustesse !$"

ContestLiveUpdates_Text_VeryExcitingAppeal::
	.string "Spectateur : La démonstration du\n"
	.string "{STR_VAR_2} gagnant fait toujours\l"
	.string "vibrer mon cœur !$"

ContestLiveUpdates_Text_VeryCool::
	.string "{STR_VAR_2}!\n"
	.string "Tu incarnes le sang-froid !$"

ContestLiveUpdates_Text_VeryBeautiful::
	.string "{STR_VAR_2}!\n"
	.string "Tu incarnes la beauté !$"

ContestLiveUpdates_Text_VeryCute::
	.string "{STR_VAR_2}!\n"
	.string "Tu incarnes la grâce !$"

ContestLiveUpdates_Text_VerySmart::
	.string "{STR_VAR_2}!\n"
	.string "Comment fais-tu pour être aussi\l"
	.string "intelligent ?$"

ContestLiveUpdates_Text_VeryTough::
	.string "{STR_VAR_2}!\n"
	.string "Quelle robustesse !$"

ContestLiveUpdates_Text_TookBreak::
	.string "Spectateur : Je n’ai pas réussi à quitter\n"
	.string "{STR_VAR_2} du regard, même après\l"
	.string "sa démonstration.\p"
	.string "Ce {STR_VAR_2} arrive vraiment à me\n"
	.string "captiver !$"

ContestLiveUpdates_Text_GotStartled::
	.string "Spectateur : J’étais au bord des larmes\n"
	.string "quand {STR_VAR_2} s’est fait surprendre\p"
	.string "par la démonstration d’un\n"
	.string "autre Pokémon.\p"
	.string "Mais tu as su tenir, {STR_VAR_2}!\n"
	.string "Bien joué !$"

ContestLiveUpdates_Text_MoveWonderful::
	.string "Spectateur : Oh !\p"
	.string "Cette capacité {STR_VAR_3} de\n"
	.string "{STR_VAR_2}!\p"
	.string "Comment arrive-t-il à faire des\n"
	.string "choses pareilles ?$"

ContestLiveUpdates_Text_TalkAboutAnotherMon::
	.string "Animatrice : Cet endroit est rempli\n"
	.string "de fans de {STR_VAR_1}!\p"
	.string "Mais je dois vous avouer qu’un autre\n"
	.string "Pokémon a attiré mon attention,\l"
	.string "le {STR_VAR_3} de {STR_VAR_2}!\p"
	.string "{STR_VAR_3}…$"

ContestLiveUpdates_Text_FailedToAppeal::
	.string "A cause de sa nervosité, il n’a pas\n"
	.string "pu réussir une seule démonstration\l"
	.string "durant le jugement secondaire.\p"
	.string "La prochaîne fois, j’aimerais que\n"
	.string "{STR_VAR_1} en réussisse au moins une.$"

ContestLiveUpdates_Text_LastInBothRounds::
	.string "Il est arrivé bon dernier aux deux\n"
	.string "jugements.\p"
	.string "J’espère que {STR_VAR_1} va se rattraper\n"
	.string "avec {STR_VAR_2} pour se faire\l"
	.string "pardonner cette dernière place !$"

ContestLiveUpdates_Text_NotExcitingEnough::
	.string "Il n’a pas réussi à profiter de\n"
	.string "l’ambiance dans le public pour\l"
	.string "faire une démonstration appropriée.\p"
	.string "Nous espérons que {STR_VAR_1} apprendra\n"
	.string "à saisir leur humeur pour changer leurs\l"
	.string "encouragements en une vraie clameur !$"

ContestLiveUpdates_Text_LostAfterWinningRound1::
	.string "Bien qu’étant en tête à la fin du\n"
	.string "jugement préliminaire, il n’a pas réussi\p"
	.string "à en tirer avantage pendant le\n"
	.string "jugement secondaire.\p"
	.string "Quelle humiliation, tout ça pour\n"
	.string "rien !\p"
	.string "{STR_VAR_1} doit certainement être en\n"
	.string "train de réfléchir à la manière de\l"
	.string "réussir ses prochaînes démonstrations.$"

ContestLiveUpdates_Text_NeverExciting::
	.string "Le public ne s’est jamais véritablement\n"
	.string "enflammé pour ses démonstrations\l"
	.string "pendant le jugement secondaire.\p"
	.string "Nous espérons qu’il arrêtera de trop\n"
	.string "penser aux autres Pokémon pour\l"
	.string "se concentrer sur ses démonstrations !$"

ContestLiveUpdates_Text_LostBySmallMargin::
	.string "Il a perdu de peu contre le {STR_VAR_2}\n"
	.string "de {STR_VAR_1}!\p"
	.string "Je n’ose imaginer ce qu’il doit ressentir\n"
	.string "après avoir échoué si près de la\l"
	.string "victoire !\p"
	.string "Ça ne me surprendrait pas que\n"
	.string "{STR_VAR_3} craque et se mette à pleurer.$"

ContestLiveUpdates_Text_RepeatedAppeals::
	.string "Il a déçu le Juge en répétant encore\n"
	.string "et encore les mêmes démonstrations.\p"
	.string "C’est une erreur impardonnable dans\n"
	.string "un Concours, et ce Pokémon\l"
	.string "en fait les frais.\p"
	.string "{STR_VAR_1} devrait avoir honte de nous\n"
	.string "avoir montré ça.$"

ContestLiveUpdates_Text_ValiantEffortButLost::
	.string "{STR_VAR_1} a vraiment fait de son mieux,\n"
	.string "mais…\p"
	.string "Ça n’a servi à rien, il est arrivé dernier.\p"
	.string "{STR_VAR_1} devrait réfléchir à cette\n"
	.string "défaite et en tirer les conclusions.$"

ContestLiveUpdates_Text_Outro::
	.string "J’aimerais terminer cette émission\n"
	.string "en félicitant les gagnants.\p"
	.string "Cette fois, il s’agit de {STR_VAR_2}\n"
	.string "et {STR_VAR_1}!\p"
	.string "Animatrice : Est-ce que tout le\n"
	.string "monde est prêt ?\l"
	.string "Tous ensemble !\p"
	.string "Public : {STR_VAR_1}! {STR_VAR_2}!\n"
	.string "Félicitations !\l"
	.string "Vous avez gagné le Concours !$"

gTVPokemonBattleUpdateText00::
	.string "“Infos Combats Pokémon”\p"
	.string "Nous vous donnons les derniers\n"
	.string "résultats des combats de Pokémon !$"

gTVPokemonBattleUpdateText01::
	.string "Les Dresseurs {STR_VAR_1} et\n"
	.string "{STR_VAR_2} étaient face à face dans\l"
	.string "un Combat {STR_VAR_3}.\p"
	.string "Ce match s’est terminé sur une\n"
	.string "victoire de {STR_VAR_1}!$"

gTVPokemonBattleUpdateText02::
	.string "Dans le combat, le {STR_VAR_2} de\n"
	.string "{STR_VAR_1} a très efficacement\l"
	.string "utilisé {STR_VAR_3}!$"

gTVPokemonBattleUpdateText03::
	.string "Le {STR_VAR_2} de {STR_VAR_1} n’a pas\n"
	.string "su montrer son vrai niveau.$"

gTVPokemonBattleUpdateText04::
	.string "Bravo pour votre victoire,\n"
	.string "{STR_VAR_1}!\p"
	.string "Quant à vous, {STR_VAR_2},\n"
	.string "nous espérons que vous ferez mieux\l"
	.string "la prochaîne fois !\p"
	.string "Ainsi se termine cette émission\n"
	.string "d’“Infos Combats Pokémon” !$"

gTVPokemonBattleUpdateText05::
	.string "Les équipes des Dresseurs {STR_VAR_1}\n"
	.string "et {STR_VAR_2} se sont affrontées en\l"
	.string "Combat Multi.\p"
	.string "Ce match s’est terminé sur une\n"
	.string "victoire de l’équipe de {STR_VAR_1}!$"

gTVPokemonBattleUpdateText06::
	.string "Dans le combat, le {STR_VAR_2} de\n"
	.string "l’équipe de {STR_VAR_1} a très\l"
	.string "efficacement utilisé {STR_VAR_3}!$"

gTVPokemonBattleUpdateText07::
	.string "Le {STR_VAR_3} n’a pas su montrer\n"
	.string "son vrai niveau face à l’équipe de\l"
	.string "{STR_VAR_2}.\p"
	.string "Félicitations sur la victoire de votre\n"
	.string "équipe, {STR_VAR_1}!\p"
	.string "Quand à vous {STR_VAR_2},\n"
	.string "nous espérons que votre équipe\l"
	.string "fera mieux la prochaîne fois !\p"
	.string "Ainsi se termine cette émission\n"
	.string "d’“Infos Combats Pokémon” !$"

GabbyAndTy_Text_GabbyPreFirstBattle:
	.string "Inès : Oh ! Nous venons de repérer un\n"
	.string "Dresseur qui a l’air costaud !\p"
	.string "OK, caméra, action !\n"
	.string "Allons l’interviewer.$"

GabbyAndTy_Text_GabbyIntro:
	.string "Inès : Oh ! Tu es {PLAYER}! Bonjour !\n"
	.string "Tu te souviens de nous ?\p"
	.string "Nous sommes devenus bien plus forts.\n"
	.string "On peut te montrer ? Caméra, ça tourne !$"

GabbyAndTy_Text_GabbyDefeatFirstTime:
	.string "Inès : Je ne me suis pas trompée !\n"
	.string "J’ai découvert un Dresseur incroyable !$"

GabbyAndTy_Text_WhoAreYouInterview:
	.string "Inès : Incroyable ! Génial !\n"
	.string "Qui es-tu ?!\p"
	.string "Je savais qu’on était sur un bon coup\n"
	.string "quand on est tombés sur toi !\p"
	.string "Oh, laisse-moi t’expliquer. Nous\n"
	.string "voyageons un peu partout pour\l"
	.string "interviewer des Dresseurs.\p"
	.string "Pourrais-tu nous accorder un peu de\n"
	.string "ton temps pour une interview ?$"

GabbyAndTy_Text_QuoteFromLastInterview:
	.string "Inès : “{STR_VAR_1}!”\p"
	.string "Tu te souviens ? C’est ta conclusion\n"
	.string "après ton dernier combat.\p"
	.string "Je n’oublie jamais ce genre de truc !$"

GabbyAndTy_Text_YouStompedUsInterviewAgain:
	.string "La dernière fois qu’on s’est battus,\n"
	.string "tu nous as écrasés avant qu’on ait eu\l"
	.string "le temps de dire ouf…\p"
	.string "Alors, qu’en penses-tu ?\n"
	.string "Tu veux qu’on t’interviewe de nouveau ?$"

GabbyAndTy_Text_YouThrewABallAtUsInterviewAgain:
	.string "La dernière fois qu’on s’est battus, tu\n"
	.string "nous as jeté une POKé Ball, non ?\p"
	.string "Nous étions si choqués. Nous en avons\n"
	.string "parlé à tout le monde. Tout le monde !\p"
	.string "Alors, qu’en penses-tu ?\n"
	.string "Tu veux qu’on t’interviewe de nouveau ?$"

GabbyAndTy_Text_CleverItemSkillsInterviewAgain:
	.string "La dernière fois qu’on s’est battus, tu\n"
	.string "as utilisé tes objets avec brio.\p"
	.string "Alors, qu’en penses-tu ?\n"
	.string "Tu veux qu’on t’interviewe de nouveau ?$"

GabbyAndTy_Text_WeLookedRespectableInterviewAgain:
	.string "La dernière fois qu’on s’est battus, on\n"
	.string "a réussi à éviter l’humiliation.\p"
	.string "Alors, qu’en penses-tu ?\n"
	.string "Tu veux qu’on t’interviewe de nouveau ?$"

GabbyAndTy_Text_InterviewAgain:
	.string "Alors, qu’en penses-tu ?\n"
	.string "Tu veux qu’on t’interviewe de nouveau ?$"

GabbyAndTy_Text_DescribeYourFeelings:
	.string "Tu veux bien ?\n"
	.string "Merci mille fois !\p"
	.string "Bien, je voudrais que tu décrives\n"
	.string "ta perception de notre combat.\l"
	.string "Sois précis et concis. Allez !$"

GabbyAndTy_Text_PerfectWellBeSeeingYou:
	.string "Inès : Mmm, mouais !\n"
	.string "C’est une excellente conclusion !\p"
	.string "J’ai l’impression qu’on va faire un tabac\n"
	.string "avec cette émission de télé.\p"
	.string "Ils vont sûrement la diffuser,\n"
	.string "alors regarde-nous souvent à la télé !\p"
	.string "Bon, allez !\n"
	.string "A bientôt !$"

GabbyAndTy_Text_DontGiveUpKeepingEyeOut:
	.string "Inès : Oh…\p"
	.string "Tant pis, mais n’abandonne pas ! Nous\n"
	.string "allons continuer à suivre ton parcours !$"

GabbyAndTy_Text_KeepingAnEyeOutForYou:
	.string "Inès : Nous allons continuer à\n"
	.string "suivre ton parcours !$"

GabbyAndTy_Text_GabbyNotEnoughMons:
	.string "Inès : Y a-t-il un vrai Dresseur, ici,\n"
	.string "avec beaucoup de Pokémon ?$"

GabbyAndTy_Text_GiveUsAnInterviewThisTime:
	.string "Inès : Ouah, tu es un sacré\n"
	.string "personnage !\p"
	.string "Tu as gagné en puissance depuis notre\n"
	.string "dernier combat. Et pas qu’un peu !\p"
	.string "Nous avions raison quand nous avons\n"
	.string "dit que tu étais un Dresseur balèze.\p"
	.string "Alors, qu’en penses-tu ?\n"
	.string "Tu veux bien qu’on t’interviewe,\l"
	.string "cette fois ?$"

GabbyAndTy_Text_GabbyDefeat:
	.string "Inès : Ça, c’était du combat !\n"
	.string "Tu as pu tout filmer ?$"

GabbyAndTy_Text_TyPreFirstBattle:
	.string "Guy : Hé, mate un peu, là ! Ce Dresseur\n"
	.string "a l’air d’être balèze !\p"
	.string "On tourne !$"

GabbyAndTy_Text_TyIntro:
	.string "Guy : Hé, mate un peu, là !\n"
	.string "Je me souviens de toi !\p"
	.string "Je vais filmer ce combat avec ma\n"
	.string "caméra !$"

GabbyAndTy_Text_TyPostBattle:
	.string "Guy : Tu as ça dans le sang ! J’ai une\n"
	.string "vidéo de premier choix, maintenant !$"

GabbyAndTy_Text_TyNotEnoughMons:
	.string "Guy : Quoi ? Tu n’as qu’un Pokémon ?\n"
	.string "Et c’est tout ?\p"
	.string "Si tu avais plus de Pokémon, ça me\n"
	.string "ferait une super vidéo, mais bon…$"

GabbyAndTy_Text_TyDefeatFirstTime:
	.string "Guy : Ouais, on a repéré un super\n"
	.string "Dresseur. C’est un super scoop !$"

GabbyAndTy_Text_TyDefeat:
	.string "Guy : Ouais, j’ai tout.\n"
	.string "C’est dans la boîte !$"

gTVInSearchOfTrainersText00::
	.string "En Quête de Dresseurs…\p"
	.string "Inès : Bonjour ! Aujourd’hui, je suis\n"
	.string "du côté de la {STR_VAR_1}.\p"
	.string "Nous sommes sur le terrain pour essayer\n"
	.string "de repérer les talents qui montent.\p"
	.string "Aujourd’hui, nous braquons notre\n"
	.string "objectif sur le Dresseur {PLAYER}.\p"
	.string "Quelque chose à propos de ce Dresseur\n"
	.string "a éveillé notre curiosité.$"

gTVInSearchOfTrainersText01::
	.string "Nous nous étions déjà battus contre\n"
	.string "{PLAYER}, mais nous pouvons vous jurer\l"
	.string "que sa technique s’est améliorée.\p"
	.string "Je savais que nous tenions un scoop\n"
	.string "quand nous avons repéré ce Dresseur !$"

gTVInSearchOfTrainersText02::
	.string "La meilleure façon de déterminer la\n"
	.string "force d’un Dresseur est de…\p"
	.string "Heu, enfin, la façon la plus rapide est\n"
	.string "de se battre. C’est comme ça que\l"
	.string "nous avons commencé notre enquête !\p"
	.string "… …\p"
	.string "Nous nous sommes donc battus contre\n"
	.string "{PLAYER}.\p"
	.string "Au cours de cette performance\n"
	.string "éprouvante, nous avons été aplatis,\l"
	.string "écrasés et terriblement humiliés !\p"
	.string "{PLAYER} est d’une force redoutable…\p"
	.string "Nous avons alors tenu à connaître ses\n"
	.string "impressions sur le combat.$"

gTVInSearchOfTrainersText03::
	.string "L’enchaînement de {STR_VAR_1} et\n"
	.string "de {STR_VAR_3} était divin !\p"
	.string "La vue de {STR_VAR_1} et de {STR_VAR_3}\n"
	.string "se soutenant mutuellement\l"
	.string "en plein milieu du combat…\p"
	.string "Ce sont des images qui font\n"
	.string "chaud au cœur !\p"
	.string "Le Dresseur a utilisé {STR_VAR_2}\n"
	.string "pour clore le combat.\p"
	.string "L’attaque {STR_VAR_2} montre l’amitié\n"
	.string "entre {STR_VAR_1} et {STR_VAR_3}!$"

gTVInSearchOfTrainersText04::
	.string "… Après notre rencontre, j’ai perdu\n"
	.string "toute confiance en moi.\p"
	.string "Nous avons été battus avant même de\n"
	.string "pouvoir frapper.\l"
	.string "Ohhh… Sniff…\p"
	.string "En tout cas, les combats de {PLAYER}\n"
	.string "sont des spectacles à ne pas manquer.\p"
	.string "J’encourage les Dresseurs confiants\n"
	.string "à défier {PLAYER}.$"

gTVInSearchOfTrainersText05::
	.string "Juste une précision.\n"
	.string "Il ne faut jamais jeter de POKé Ball\l"
	.string "pendant un combat de Dresseurs !\p"
	.string "{PLAYER} a de toute évidence une grande\n"
	.string "force, mais ne respecte pas les règles.\p"
	.string "Un message pour notre public :\p"
	.string "Si vous croisez {PLAYER},\n"
	.string "dites-le-lui !$"

gTVInSearchOfTrainersText06::
	.string "{PLAYER} adore anticiper les actions de\n"
	.string "l’adversaire.\p"
	.string "Le timing de l’utilisation des objets\n"
	.string "était tout simplement remarquable !$"

gTVInSearchOfTrainersText07::
	.string "Honnêtement, j’ai vraiment fait de\n"
	.string "mon mieux.\p"
	.string "Même si nous avons perdu, le\n"
	.string "combat a été particulièrement tendu.\p"
	.string "Mais si tu as du mal à me battre,\n"
	.string "c’est que tu as encore du chemin\l"
	.string "à parcourir, {PLAYER}!$"

gTVInSearchOfTrainersText08::
	.string "Après notre combat, nous avons demandé\n"
	.string "à {PLAYER} un bref résumé.\p"
	.string "Le Dresseur a répondu :\n"
	.string "“{STR_VAR_1}”.\p"
	.string "Les Pokémon de {PLAYER} étaient\n"
	.string "{STR_VAR_2} et {STR_VAR_3}…\l"
	.string "Et “{STR_VAR_1}”…\p"
	.string "Mmm ! Voilà qui est profond ! Il y a\n"
	.string "un sens caché derrière ça !\p"
	.string "Ce n’est pas étonnant. C’est toujours\n"
	.string "intéressant d’écouter un bon Dresseur.\p"
	.string "Voilà, c’est tout pour aujourd’hui !\n"
	.string "Ne ratez pas la prochaîne émission !$"

ContestLadyShow_Text_Intro::
	.string "“Infos Concours Pokémon”\p"
	.string "Animatrice : Désolée d’interrompre\n"
	.string "vos programmes, et merci de nous\l"
	.string "retrouver !\p"
	.string "Nous sommes en direct pour vous\n"
	.string "montrer le résultat d’un Concours\p"
	.string "catégorie {STR_VAR_1} qui vient de\n"
	.string "se terminer !\p"
	.string "Spectateurs : ?!!!\p"
	.string "Animatrice : Oh, on dirait bien que\n"
	.string "les participants du Concours se\l"
	.string "dirigent par ici !\p"
	.string "Je vais tenter de les interviewer en\n"
	.string "direct pour vous !\p"
	.string "Spectateurs : ?!!!\n"
	.string "?!!!$"

ContestLadyShow_Text_Won::
	.string "Animatrice : Excusez-moi !\n"
	.string "Merci de répondre à nos questions\l"
	.string "en direct !\p"
	.string "Puis-je vous féliciter pour votre\n"
	.string "victoire ?\p"
	.string "Qu’est-ce qui vous a permis de\n"
	.string "remporter cette victoire si\l"
	.string "brillamment ?\p"
	.string "Canon : Nous nous sommes donnés\n"
	.string "à fond aujourd’hui, mon {STR_VAR_2}\l"
	.string "et moi !\p"
	.string "Mais je suis sûre que nous n’aurions\n"
	.string "pas réussi sans le soutien que nous\l"
	.string "avons reçu pendant le Concours !\p"
	.string "Animatrice : Y a-t-il quelqu’un en\n"
	.string "particulier avec qui vous souhaiteriez\l"
	.string "partager votre joie ?\p"
	.string "Allez-y, tous nos téléspectateurs vous\n"
	.string "regardent !\p"
	.string "Canon : Hé, tu es là ?\p"
	.string "{STR_VAR_3}! Est-ce que tu regardes ?\n"
	.string "On a réussi !\l"
	.string "Merci, {STR_VAR_3}!$"

ContestLadyShow_Text_Lost::
	.string "Animatrice : Excusez-moi !\n"
	.string "Merci de répondre à nos questions\l"
	.string "en direct !\p"
	.string "Vous devez être déçue par la tournure\n"
	.string "des évènements. Avez-vous des\l"
	.string "commentaires ?\p"
	.string "Canon : Ça me brise le cœur…\n"
	.string "Nous nous sommes pourtant donnés\l"
	.string "à fond, mon {STR_VAR_2} et moi !\p"
	.string "Mais j’ai l’impression d’avoir trahi\n"
	.string "tous ceux qui nous ont supportés.\p"
	.string "Animatrice : Je ne devrais pas le dire,\n"
	.string "mais il manquait quelque chose\l"
	.string "à votre Pokémon.\p"
	.string "Canon : {STR_VAR_3}, je suis désolée…\n"
	.string "Je ferai mieux la prochaîne fois…\l"
	.string "Je le jure… Sniff… sniff…\p"
	.string "Spectateurs : Vous avez vu ?\n"
	.string "La pauvre fille !\p"
	.string "Animatrice : Oh… oh…\n"
	.string "Hum… C’est tout pour aujourd’hui !\l"
	.string "Merci de nous avoir suivis !$"

ContestLadyShow_Text_LostBadly::
	.string "Animatrice : Excusez-moi !\n"
	.string "Merci de répondre à nos questions\l"
	.string "en direct !\p"
	.string "Comment s’est passé ce Concours\n"
	.string "pour vous ?\p"
	.string "Canon : Tout s’est mal passé…\n"
	.string "Pour une raison qui m’échappe,\l"
	.string "mon {STR_VAR_2} n’a pas réussi à attirer\l"
	.string "l’attention du public.\p"
	.string "Animatrice : Je ne devrais pas le dire,\n"
	.string "mais il manquait quelque chose\l"
	.string "à votre Pokémon.\p"
	.string "Canon : … … … … … …\n"
	.string "…Sniff… Ouin !!\p"
	.string "Spectateurs : Vous avez vu ?\n"
	.string "La pauvre fille !\p"
	.string "Animatrice : Oh… oh…\n"
	.string "Hum… C’est tout pour aujourd’hui !\l"
	.string "Merci de nous avoir suivis !$"

